### ISSUE TITLE
No visualisation with Denoise

### ISSUE THREAD

**Issue by mifth** [bsavery/PRMan-for-Blender#100]
Hi.

No progress visualisation in 'it' when Denoise is switched on.
But if i switch Denoise off - i can see rendering progress in 'it'.

**Comment by bsavery** [comment]
Yes this is a limitation. The issue is that the Denise data has to be written to a separate file which kills interactivity to it. It's really meant to be used for final renders

**Comment by mifth** [comment]
Ok. Close it.
