### ISSUE TITLE
Border and Crop features

### ISSUE THREAD

**Issue by mifth** [bsavery/PRMan-for-Blender#103]
Hi.

Border and Crop features dunno work. When i use Ctrl+B in the camera view. Could you add them as they save much time.

http://i.imgur.com/zJcBGBu.jpg

**Comment by bsavery** [comment]
https://github.com/bsavery/PRMan-for-Blender/commit/622f136163e3926db4160285ae3744cd27e4cf68 Confusingly... what Blender calls "Border", PRMan calls crop windows.

**Comment by bsavery** [comment]
Fixed btw.

**Comment by mifth** [comment]
Hi.

Wait a bit. I updated the code. You have fixed only one part of the issue.

In blender - crop and border work in a different way.
Border - renders a region.
Crop - it crops an image according to the border.

Here is how it works in cycles with crop and without the crop:
![selection_004](https://cloud.githubusercontent.com/assets/2251298/9318731/3c710144-454f-11e5-9830-d91d51c02c40.png)
![selection_005](https://cloud.githubusercontent.com/assets/2251298/9318733/41e27180-454f-11e5-879b-f4923ce5b347.png)


And how it looks with the PR-Man:
![selection_006](https://cloud.githubusercontent.com/assets/2251298/9318740/585ed818-454f-11e5-94dc-3224f604fb92.png)
![selection_007](https://cloud.githubusercontent.com/assets/2251298/9318742/5b6b20b6-454f-11e5-8ba9-b4e8a5158b4b.png)

As you can see - crop does not crop the canvas of the image. I suppose this issue is not fixed.

I cannot reopen the bug. No button to reopen. Please, reopen it till this issue is not fixed.

Thanks.

**Comment by bsavery** [comment]
Thanks.  Sorry If I wasn't clear in my previous comment.  I'm aware that would be the case.  (I'll change my comment to put it in Blender terms.  Border = what prman thinks of crop, and there's not really an idea of doing what Blender calls a crop in prman)

However, I guess I'm confused on really what the point of the blender "Crop" feature is anyway.  It's the same amount of data in the image file (at least on openexr files), you just want the pixels to go from 0 - (max_x - min_x) and 0 - (max_y - min_y)?  Openexr files have the concept of a "data window" which in the case of a border just sets them to the border window size.  Why do you want the crop setting?

There is a way to pass the some stuff into the "it" display driver that would do what you want, but not a huge issue.  I'd also argue that what Blender calls a Border, the rest of the industry calls a Crop, but that's just confusing the issue further.

**Comment by mifth** [comment]
I work at social game called supecity. It'a citybuilder. It has small objects which i render.
I use blender's crop to crop some objects on a canvas.
Sometimes i have many objects on a canvas. I just need to crop one object sometimes.

I can make a screenshot when i get to work if you want.

About pixels you mentioned - i guess yes. Just like blender does it.

**Comment by bsavery** [comment]
Fixed.

**Comment by mifth** [comment]
Yes! This is fixed. Thank you!

I found another thing:
If i save to png - i get defferent colors: http://i.imgur.com/Ltb2QZR.png
This is because IT uses gamma? 

I just pressed Export Image in IT.

**Comment by bsavery** [comment]
Yes to gamma, right click got to catalog->burn in mapping on save

**Comment by mifth** [comment]
THanks!
