### ISSUE TITLE
Group Instances have no material

### ISSUE THREAD

**Issue by mifth** [bsavery/PRMan-for-Blender#104]
Hi.

I have just tested Group instances. And the instances are rendered without a material.

Here is the test:
http://i.imgur.com/HPqQHjx.jpg

File:
https://dl.dropboxusercontent.com/u/26887202/blender/temp_prman_3.blend

**Comment by bsavery** [comment]
Works for me.
![untitled](https://cloud.githubusercontent.com/assets/1892220/9280459/492b30f0-4273-11e5-8574-3c68ca219b91.jpg)

**Comment by mifth** [comment]
I updated the plugin and now it works ok. Thanks.
