### ISSUE TITLE
PxrSeExpr  pattern.  Is this something that is supported in the addon?

### ISSUE THREAD

**Issue by MarshallRoss** [bsavery/PRMan-for-Blender#106]
I was just looking at the set of pattern nodes and noticed this one.  PxrSeExpr looks to be a scriptable expression generator.  I was just wondering if it's supported in our blender set up.  The node has a slot for "expression", but it's just a single line.  There's also 4 color inputs and 4 float inputs...not sure what those are for.  Anyway, just curious about this one--I'm sure it's not mission critical or anything.  Thx.

**Comment by bsavery** [comment]
Good question. Yes the interface kinda sucks for this now. However you can do expressions in there. Take a look in the RenderMan docs how to use seexpr. I used it for the flaming monkey example on the forums.  Basically I found it easier to write the seexpr in a text editor and paste it in

**Comment by MarshallRoss** [comment]
Ya...totally works.  The only caveat is that you have to script everything on a single line, it seems.  (e.g. $val=noise(10*$P);$color=ccurve($val,0.000, [1.000, 1.000, 0.498], 4,0.590, [0.333, 0.000, 0.000], 4, 0.665, [1.000, 1.000, 0.000], 4);$color)

**Comment by MarshallRoss** [comment]
![testseexpr](https://cloud.githubusercontent.com/assets/4689949/9192544/e129c66a-3fc0-11e5-9186-c35c9ed38abf.jpg)
Here's the PxrSeExpr node at work.  Pretty cool that you can script targeted parameters within other nodes.

**Comment by MWY3510** [comment]
Did you guys want something like what we have in the OSL node? An external and internal script selection.

**Comment by MarshallRoss** [comment]
Yea, that'd probably make sense: you can either load and external script, or type one into a full-fledged text field.  Sounds good.

**Comment by MWY3510** [comment]
Quick question, do people just want a place to enter a file location like the OSL node or do you want dynamically generated inputs and outputs also.

**Comment by MarshallRoss** [comment]
Both, if possible.  I think the more flexibility with this feature, the better.

**Comment by MWY3510** [comment]
I was just asking because making it dynamic will take longer and might be a touch more prone to user error. Thanks for the feedback.

**Comment by bsavery** [comment]
I'm not even sure how you can make it dynamic without doing some code introspection on the code in the seexpr.  Personally especially with this and maybe with the osl node I'd prefer to just have a larger text area in the node editor.  Is that possible in the blender UI?

**Comment by MarshallRoss** [comment]
Thank you for working on it.  

Yea, if nothing else a larger (multi-line) text field would be great. The current single line text field isn't ideal, though it seems to work, at least for small scripts.  btw, it seemed like the Disney SeExpr tools were all written for Windows.  Has anyone ported them to Mac?

**Comment by MWY3510** [comment]
I don't believe that multi-line properties are possible in the node editor. Would you like just a simple text search property instead so the user can use the internal text editor?

**Comment by MarshallRoss** [comment]
"Would you like just a simple text search property instead so the user can use the internal text editor?"  Yea, that would work.  So, probably either load an external file, or open the text editor.  Thx!

**Comment by MWY3510** [comment]
Ok, from what I hear I think I will try adding the same switch that is on the OSL node but leave the other properties. The plug-in should be able to simply export the read in file to the rib archive.

**Comment by MWY3510** [comment]
Does this work for everyone? You can ignore the extra input I have, it will not be there for long.
![pxrseexprnode](https://cloud.githubusercontent.com/assets/9410101/9297227/e95cd568-4469-11e5-96c6-4d9ddd732b32.png)

**Comment by MWY3510** [comment]
Some progress has been made. Stay tuned for more details.

**Comment by MWY3510** [comment]
Ok, first pass of the code is done. Now awaiting merge.
MWY3510

**Comment by MWY3510** [comment]
This is now in master. I am closing this issue unless someone has any other remarks.
