### ISSUE TITLE
Metaballs created in edit mode under a single object are not exported properly.

### ISSUE THREAD

**Issue by rendermouse** [bsavery/PRMan-for-Blender#107]
Regression Suite No. 3 fails because the metaballs are all within a single object, and the exporter doesn't inspect within to find them. It only exports and blends separate metaball objects in a meta-family.

**Comment by rendermouse** [comment]
It looks like we need to iterate through the bpy.data.metaballs collection, and each member's .elements collection, in order to export all meta elements used in the scene. We may just need to export these in a separate pass, skipping any meta objects found during the main object tree export loop.

**Comment by rendermouse** [comment]
I'm redoing the blob export code to fix this up. Going well, but not there yet.

**Comment by bsavery** [comment]
nice.

**Comment by rendermouse** [comment]
I am still working on this. I got tripped up a bit, because meta elements nested under one object share a single parent, and therefore share a single parent transform. 

Meta elements that are completely separate objects but share the same family name should also blend as one blobby, but each inherits a completely different parent transform.

**Comment by rendermouse** [comment]
I updated my repo to fix up the transforms.  There are still some minor scaling issues.

**Comment by rendermouse** [comment]
Also, particle-system emitted blobs have not been addressed.

**Comment by bsavery** [comment]
Do you want me to look at the changes?  What are the scaling issues?  I can do particles as well.

**Comment by rendermouse** [comment]
The scaling issues are mainly to do with the Threshold of a MetaBall and Stiffness of a MetaElement not being properly mapped to the exported data. I couldn't figure out how to map these properties to RIS blobs.

Feel free to have a look, and also let me know if you're ok with how the other MetaBall code works. It was a challenging task, for sure.

**Comment by bsavery** [comment]
With your latest pull request can we close this issue?

**Comment by rendermouse** [comment]
We can close it. There is a ton of stuff that could still be done with metaballs (segments, planes, subtraction, etc), those can be addressed later.

**Comment by rendermouse** [comment]
Thanks for doing the blobby particles code, works great!
