### ISSUE TITLE
denoiser behavior questions

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#110]
Hi,
Couple of questions on denoiser behavior.....

Also, my main rendering machine is an i7 Linux Mint system.  When I render normally, all 8 logical cores are used at 100%.  A relatively noise free image straight from the renderer takes about sixteen minutes for the file I'm testing.  Activating the denoiser causes my CPU use to drop.  All logical cores will ramp up to 100% for about five seconds, and then 30-40 seconds will pass with all but one core at idle.  Nothing seems to be happening during this downtime.  An output EXR and a denoise EXR get written at each of these lulls in activity, but that only takes a second or two, not 30.

**Comment by jdent02** [comment]
It has something to do with the display driver.  If I select "openEXR" for the driver, it displays the above described action.  If I select 'it' then it renders like it normally should, with all cores at 100%.

**Comment by bsavery** [comment]
Here's what I think is happening.  And this might give some background.

Basically when we're doing a "render to the viewport" of Blender we use a feature in renderman called Checkpointing.  http://renderman.pixar.com/resources/current/RenderMan/risRecovery.html
So the pauses you see are the stops for writing out data and image.  The reason we need to do those checkpoints is so we can write out the current state of the image so we have something to display in the Blender ui.

If you're rendering to 'it' we don't need to pause to do that.

So I guess maybe this brings back around to the question of batch rendering and what that ui would be.  Here's a thought for reorganizing the "RenderMan output" section of Scene settings:

Batch/Test render settings.  - if doing a batch render you might want to use denoise but I'm not sure denoise has any real **practical** uses for test renders.  (other than seeing what the effect of it is)

When doing a test render it makes sense to render to the blender ui or 'IT' but otherwise if you're batch rendering you probably want a file no?

**Comment by jdent02** [comment]
Thanks for the clarification on what PRMan is doing to display in Blender.  I had a feeling that was what was going on.

Normally I would agree that the denoiser isn't useful in test renders, except for the fact that it has some eccentric behavior that can lead to ugly artifacts in the image, especially around certain high contrast details, and t's good to see this and correct for it before final rendering.  Maybe you could make 'it' the only driver option available when denoiser is active?

As far as final rendering I've found the most reliable (and fastest) method is to export the RIB's and render through the command line tools (including denoising).  I've tried low res test animations using this method and it seems to work fine (so long as you account for frame numbers in the RIB names).  Only annoyance is that Blender will still export an image for each frame of the animation, so you end up with numerous empty image files since nothing is being rendered back into the display.  

How's this for a RenderMan ouput remake: If the export option is set to 'export RIB and render' the normal options remain as they are now.  If you select 'export RIB only' all the normal Blender rendering ('render', 'animation' and 'audio') and image output panels (location, image type and bit depth/channels option) are replaced by a panel with two buttons: 'export frame' or 'export sequence'.  if you select 'export sequence' the exporter could then automatically append the RIB export name and image output names with frame numbers.......  As far as the denoiser, you could do what I mentioned above and make 'it' the only available display driver, so long as the user is rendering from within Blender.  If they are exporting RIB's only, all display drivers should be available as they are now.

Not sure how difficult this would be to implement or if it's even necessary, as the above described batch export functionality already exists, albeit in a somewhat convoluted form.

**Comment by bsavery** [comment]
Good thoughts.  Let me think about it more.  

Mainly what I'm coming around to is there should be a "batch render" mode and a "preview render" mode which may have different settings or act different.

**Comment by jdent02** [comment]
Another quick behavior question.  when you render through IT normally you see the image constantly refining in front of you.  When you activate the denoiser though the IT screen remains black until the whole rendering process finishes.

**Comment by bsavery** [comment]
Yes.  That's because of the way our display drivers work.  When doing
denoise you are writing pixels to 'it' and to openexr at the same time
(openexr for the denoise data).  The 'it' display driver can only finish
when all the pixels are done for the openexr data part.

Really the point is that denoise is not meant as an interactive tool...

On Wed, Aug 19, 2015 at 12:23 PM, jdent02 <notifications@github.com> wrote:

> Another quick behavior question. when you render through IT normally you
> see the image constantly refining in front of you. When you activate the
> denoiser though the IT screen remains black until the whole rendering
> process finishes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/110#issuecomment-132750215>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
Thanks!

**Comment by bsavery** [comment]
So I've thought a bit about the preview/batch render thing.  Here's an idea, and in essence we *kinda* do it now, but it's hardcoded.  Basically each render would have three steps:

1. Generate Job tree (A list of "tasks" to do for the render:  ex Generate Rib, convert textures, render, etc)
2.  Run local tasks in job tree.  For example if ribs and textures are being generated locally do that.  Or Render locally if this is something like a preview render.
3.  Do remote tasks.  Basically we could convert this job tree to an alfred script for rendering through tractor/localqueue/cloud, of if some other queueing system wants to convert it... and spool said alfred script.

Thoughts?

**Comment by jdent02** [comment]
So this workflow would allow you to do something like convert textures locally, then export a RIB with the denoiser passes included for later offline rendering and denoising?  Or it can be set to render and denoise through Blender?  Sounds pretty slick and it would be nice to have that level of control over the process.

Although for less technical users you might want to have an option where they can just hit one button and the exporter auto generates a task list and executes (kinda like the 'render' button does now if you don't change any of the RenderMan export options).  Maybe another use for the 'advanced' checkbox?

**Comment by bsavery** [comment]
Yeah, nothing too revolutionary, this is basically what Rendeman for Maya
does.  And yes of course this would be hidden if you just want to hit
render!

On Tue, Aug 25, 2015 at 5:57 AM, jdent02 <notifications@github.com> wrote:

> So this workflow would allow you to do something like convert textures
> locally, then export a RIB with the denoiser passes included for later
> offline rendering and denoising? Or it can be set to render and denoise
> through Blender? Sounds pretty slick and it would be nice to have that
> level of control over the process.
>
> Although for less technical users you might want to have an option where
> they can just hit one button and the exporter auto generates a task list
> and executes (kinda like the 'render' button does now if you don't change
> any of the RenderMan export options). Maybe another use for the 'advanced'
> checkbox?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/110#issuecomment-134577318>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
Cool.

**Comment by jdent02** [comment]
So sorry to revive this one but I'm getting some odd behavior when exporting a .rib with the denoiser active and then manually rendering it with the prman and denoiser command lines.  First off the render stops pretty quickly.  When I run the denoiser and point it to the .exr file I get these errors:

denoise /media/jon/2296653896650E1B/cg_artwork/Orbital_Gun_Project/Models/Station/station_test/Scene_0001.denoise.exr
Filtering to produce /media/jon/2296653896650E1B/cg_artwork/Orbital_Gun_Project/Models/Station/station_test/Scene_0001.denoise_filtered.exr
Warning: at pixel (1377,0), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0907931, 0.0898317, 0.057912).  abs diff=0.238537; rel diff=340.186615%
Warning: at pixel (1378,0), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0213221, 0.0213221, 0.0137706).  abs diff=0.056415; rel diff=340.365295%
Warning: at pixel (1377,1), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.111711, 0.10521, 0.0642172).  abs diff=0.281138; rel diff=338.008026%
Warning: at pixel (1378,1), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.017965, 0.0172078, 0.0122588).  abs diff=0.047432; rel diff=342.057098%
Warning: at pixel (1376,2), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.000708195, 0.000708195, 0.000397684).  abs diff=0.001814; rel diff=336.686218%
Warning: at pixel (1377,2), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.110195, 0.101239, 0.0677182).  abs diff=0.279152; rel diff=339.911591%
Warning: at pixel (1378,2), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.01548, 0.0134882, 0.0112705).  abs diff=0.040239; rel diff=343.598694%
Warning: at pixel (1376,3), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.00520999, 0.00520999, 0.00247983).  abs diff=0.012900; rel diff=331.863861%
Warning: at pixel (1377,3), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.124083, 0.11107, 0.0776738).  abs diff=0.312827; rel diff=340.480133%
Warning: at pixel (1378,3), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0137208, 0.00829133, 0.00799326).  abs diff=0.030005; rel diff=335.000214%
Warning: at pixel (1376,4), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.012687, 0.0121055, 0.0099082).  abs diff=0.034701; rel diff=344.571045%
Warning: at pixel (1377,4), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.138511, 0.120274, 0.108819).  abs diff=0.367604; rel diff=344.698425%
Warning: at pixel (1378,4), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0188331, 0.012406, 0.0107602).  abs diff=0.041999; rel diff=336.162140%
Warning: at pixel (1376,5), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0109784, 0.0107101, 0.00855162).  abs diff=0.030240; rel diff=344.415955%
Warning: at pixel (1377,5), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.145003, 0.13581, 0.145038).  abs diff=0.425851; rel diff=346.248230%
Warning: at pixel (1378,5), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0113719, 0.00890184, 0.00755397).  abs diff=0.027828; rel diff=341.485901%
Warning: at pixel (1376,6), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0164937, 0.0164937, 0.0160861).  abs diff=0.049073; rel diff=346.386292%
Warning: at pixel (1377,6), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.149793, 0.140991, 0.140357).  abs diff=0.431141; rel diff=346.254761%
Warning: at pixel (1378,6), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.00899388, 0.00779733, 0.00898336).  abs diff=0.025775; rel diff=345.672485%
Warning: at pixel (1365,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0299874, 0.0299874, 0.0279729).  abs diff=0.087948; rel diff=346.228546%
Warning: at pixel (1366,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0835604, 0.0835604, 0.0696953).  abs diff=0.236816; rel diff=345.228790%
Warning: at pixel (1367,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.00154426, 0.00154426, 0.00113605).  abs diff=0.004225; rel diff=343.220459%
Warning: at pixel (1376,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0179814, 0.0179814, 0.010563).  abs diff=0.046526; rel diff=337.925323%
Warning: at pixel (1377,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.150422, 0.144509, 0.141138).  abs diff=0.436068; rel diff=346.289520%
Warning: at pixel (1378,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0092806, 0.00741826, 0.00565097).  abs diff=0.022350; rel diff=339.753326%
Warning: at pixel (1365,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.09544, 0.09544, 0.0919048).  abs diff=0.282785; rel diff=346.356049%
Warning: at pixel (1366,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.253711, 0.253275, 0.255921).  abs diff=0.762907; rel diff=346.406555%
Warning: at pixel (1367,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.00383117, 0.00368878, 0.00732171).  abs diff=0.014842; rel diff=328.012665%
Warning: at pixel (1376,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0234216, 0.0234216, 0.0355131).  abs diff=0.082356; rel diff=339.176056%
Warning: at pixel (1377,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.164256, 0.158162, 0.17207).  abs diff=0.494488; rel diff=346.203796%
Warning: at pixel (1378,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.00851284, 0.00851284, 0.00489691).  abs diff=0.021923; rel diff=337.353821%
Warning: at pixel (1365,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.107132, 0.107132, 0.103143).  abs diff=0.317408; rel diff=346.355438%
Warning: at pixel (1366,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.259914, 0.259749, 0.271894).  abs diff=0.791557; rel diff=346.329742%
Warning: at pixel (1367,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.00263505, 0.00263505, 0.00207483).  abs diff=0.007345; rel diff=344.412354%
Warning: at pixel (1376,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0255601, 0.0252333, 0.0383218).  abs diff=0.089115; rel diff=339.341888%
Warning: at pixel (1377,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.156805, 0.153534, 0.20814).  abs diff=0.518480; rel diff=342.839996%
Warning: at pixel (1378,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.00902769, 0.00902769, 0.00465251).  abs diff=0.022708; rel diff=334.225006%
Warning: at pixel (1365,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.117233, 0.117233, 0.116308).  abs diff=0.350775; rel diff=346.407776%
Warning: at pixel (1366,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.250938, 0.250938, 0.27099).  abs diff=0.772867; rel diff=346.177216%
Warning: at pixel (1367,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.00109624, 0.00109624, 0.000655966).  abs diff=0.002848; rel diff=338.419312%
Warning: at pixel (1376,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0396203, 0.0374552, 0.0552703).  abs diff=0.132346; rel diff=340.935944%
Warning: at pixel (1377,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.171048, 0.169803, 0.162587).  abs diff=0.503438; rel diff=346.324615%
Warning: at pixel (1378,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.00605335, 0.00605334, 0.00466537).  abs diff=0.016772; rel diff=344.061890%
Warning: at pixel (1365,11), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.124266, 0.124266, 0.124966).  abs diff=0.373499; rel diff=346.408936%
Warning: at pixel (1366,11), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.242835, 0.242532, 0.240427).  abs diff=0.725794; rel diff=346.406769%
Warning: at pixel (1376,11), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.047473, 0.0465245, 0.0496473).  abs diff=0.143645; rel diff=346.281128%
Warning: at pixel (1377,11), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.162597, 0.160103, 0.194315).  abs diff=0.517015; rel diff=345.004486%
Warning: at pixel (1365,12), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.13537, 0.13537, 0.130352).  abs diff=0.401092; rel diff=346.355927%
Warning: at pixel (1366,12), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.234519, 0.234519, 0.263961).  abs diff=0.733000; rel diff=345.852631%
Warning: at pixel (1376,12), diffuse (0, 0, 0) + specular (0, 0, 0) = (0, 0, 0) != color (0.0448715, 0.0435358, 0.0483154).  abs diff=0.136723; rel diff=346.072540%
...
Average time to filter 1 image(s): 6.569 Seconds

I then get an image with a black alpha cutout of my object.

**Comment by bsavery** [comment]
Oh that's a fun error. I'd need to look at the exr data or rib file.

On Monday, January 4, 2016, jdent02 <notifications@github.com> wrote:

> So sorry to revive this one but I'm getting some odd behavior when
> exporting a .rib with the denoiser active and then manually rendering it
> with the prman and denoiser command lines. First off the render stops
> pretty quickly. When I run the denoiser and point it to the .exr file I get
> these errors:
>
> denoise
> /media/jon/2296653896650E1B/cg_artwork/Orbital_Gun_Project/Models/Station/station_test/Scene_0001.denoise.exr
> Filtering to produce
> /media/jon/2296653896650E1B/cg_artwork/Orbital_Gun_Project/Models/Station/station_test/Scene_0001.denoise_filtered.exr
> Warning: at pixel (1377,0), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0907931, 0.0898317, 0.057912). abs diff=0.238537; rel
> diff=340.186615%
> Warning: at pixel (1378,0), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0213221, 0.0213221, 0.0137706). abs diff=0.056415; rel
> diff=340.365295%
> Warning: at pixel (1377,1), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.111711, 0.10521, 0.0642172). abs diff=0.281138; rel
> diff=338.008026%
> Warning: at pixel (1378,1), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.017965, 0.0172078, 0.0122588). abs diff=0.047432; rel
> diff=342.057098%
> Warning: at pixel (1376,2), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.000708195, 0.000708195, 0.000397684). abs diff=0.001814;
> rel diff=336.686218%
> Warning: at pixel (1377,2), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.110195, 0.101239, 0.0677182). abs diff=0.279152; rel
> diff=339.911591%
> Warning: at pixel (1378,2), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.01548, 0.0134882, 0.0112705). abs diff=0.040239; rel
> diff=343.598694%
> Warning: at pixel (1376,3), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.00520999, 0.00520999, 0.00247983). abs diff=0.012900; rel
> diff=331.863861%
> Warning: at pixel (1377,3), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.124083, 0.11107, 0.0776738). abs diff=0.312827; rel
> diff=340.480133%
> Warning: at pixel (1378,3), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0137208, 0.00829133, 0.00799326). abs diff=0.030005; rel
> diff=335.000214%
> Warning: at pixel (1376,4), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.012687, 0.0121055, 0.0099082). abs diff=0.034701; rel
> diff=344.571045%
> Warning: at pixel (1377,4), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.138511, 0.120274, 0.108819). abs diff=0.367604; rel
> diff=344.698425%
> Warning: at pixel (1378,4), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0188331, 0.012406, 0.0107602). abs diff=0.041999; rel
> diff=336.162140%
> Warning: at pixel (1376,5), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0109784, 0.0107101, 0.00855162). abs diff=0.030240; rel
> diff=344.415955%
> Warning: at pixel (1377,5), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.145003, 0.13581, 0.145038). abs diff=0.425851; rel
> diff=346.248230%
> Warning: at pixel (1378,5), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0113719, 0.00890184, 0.00755397). abs diff=0.027828; rel
> diff=341.485901%
> Warning: at pixel (1376,6), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0164937, 0.0164937, 0.0160861). abs diff=0.049073; rel
> diff=346.386292%
> Warning: at pixel (1377,6), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.149793, 0.140991, 0.140357). abs diff=0.431141; rel
> diff=346.254761%
> Warning: at pixel (1378,6), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.00899388, 0.00779733, 0.00898336). abs diff=0.025775; rel
> diff=345.672485%
> Warning: at pixel (1365,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0299874, 0.0299874, 0.0279729). abs diff=0.087948; rel
> diff=346.228546%
> Warning: at pixel (1366,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0835604, 0.0835604, 0.0696953). abs diff=0.236816; rel
> diff=345.228790%
> Warning: at pixel (1367,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.00154426, 0.00154426, 0.00113605). abs diff=0.004225; rel
> diff=343.220459%
> Warning: at pixel (1376,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0179814, 0.0179814, 0.010563). abs diff=0.046526; rel
> diff=337.925323%
> Warning: at pixel (1377,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.150422, 0.144509, 0.141138). abs diff=0.436068; rel
> diff=346.289520%
> Warning: at pixel (1378,7), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0092806, 0.00741826, 0.00565097). abs diff=0.022350; rel
> diff=339.753326%
> Warning: at pixel (1365,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.09544, 0.09544, 0.0919048). abs diff=0.282785; rel
> diff=346.356049%
> Warning: at pixel (1366,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.253711, 0.253275, 0.255921). abs diff=0.762907; rel
> diff=346.406555%
> Warning: at pixel (1367,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.00383117, 0.00368878, 0.00732171). abs diff=0.014842; rel
> diff=328.012665%
> Warning: at pixel (1376,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0234216, 0.0234216, 0.0355131). abs diff=0.082356; rel
> diff=339.176056%
> Warning: at pixel (1377,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.164256, 0.158162, 0.17207). abs diff=0.494488; rel
> diff=346.203796%
> Warning: at pixel (1378,8), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.00851284, 0.00851284, 0.00489691). abs diff=0.021923; rel
> diff=337.353821%
> Warning: at pixel (1365,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.107132, 0.107132, 0.103143). abs diff=0.317408; rel
> diff=346.355438%
> Warning: at pixel (1366,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.259914, 0.259749, 0.271894). abs diff=0.791557; rel
> diff=346.329742%
> Warning: at pixel (1367,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.00263505, 0.00263505, 0.00207483). abs diff=0.007345; rel
> diff=344.412354%
> Warning: at pixel (1376,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0255601, 0.0252333, 0.0383218). abs diff=0.089115; rel
> diff=339.341888%
> Warning: at pixel (1377,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.156805, 0.153534, 0.20814). abs diff=0.518480; rel
> diff=342.839996%
> Warning: at pixel (1378,9), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.00902769, 0.00902769, 0.00465251). abs diff=0.022708; rel
> diff=334.225006%
> Warning: at pixel (1365,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.117233, 0.117233, 0.116308). abs diff=0.350775; rel
> diff=346.407776%
> Warning: at pixel (1366,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.250938, 0.250938, 0.27099). abs diff=0.772867; rel
> diff=346.177216%
> Warning: at pixel (1367,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.00109624, 0.00109624, 0.000655966). abs diff=0.002848;
> rel diff=338.419312%
> Warning: at pixel (1376,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0396203, 0.0374552, 0.0552703). abs diff=0.132346; rel
> diff=340.935944%
> Warning: at pixel (1377,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.171048, 0.169803, 0.162587). abs diff=0.503438; rel
> diff=346.324615%
> Warning: at pixel (1378,10), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.00605335, 0.00605334, 0.00466537). abs diff=0.016772; rel
> diff=344.061890%
> Warning: at pixel (1365,11), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.124266, 0.124266, 0.124966). abs diff=0.373499; rel
> diff=346.408936%
> Warning: at pixel (1366,11), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.242835, 0.242532, 0.240427). abs diff=0.725794; rel
> diff=346.406769%
> Warning: at pixel (1376,11), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.047473, 0.0465245, 0.0496473). abs diff=0.143645; rel
> diff=346.281128%
> Warning: at pixel (1377,11), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.162597, 0.160103, 0.194315). abs diff=0.517015; rel
> diff=345.004486%
> Warning: at pixel (1365,12), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.13537, 0.13537, 0.130352). abs diff=0.401092; rel
> diff=346.355927%
> Warning: at pixel (1366,12), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.234519, 0.234519, 0.263961). abs diff=0.733000; rel
> diff=345.852631%
> Warning: at pixel (1376,12), diffuse (0, 0, 0) + specular (0, 0, 0) = (0,
> 0, 0) != color (0.0448715, 0.0435358, 0.0483154). abs diff=0.136723; rel
> diff=346.072540%
> ...
> Average time to filter 1 image(s): 6.569 Seconds
>
> I then get an image with a black alpha cutout of my object.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/110#issuecomment-168883483>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
Hold on a sec.  Might be an ID10T error....

**Comment by jdent02** [comment]
I think I screwed up.  Will let you know in ten minutes or so.

**Comment by jdent02** [comment]
Sorry Brian I messed up.  Somehow the integrator got switched to "BxdfValidate" and I didn't catch it.  I'm living with a seven week old infant and I think the sleep deprivation is getting to me.....  Sorry for the hassle.

**Comment by bsavery** [comment]
No worries.

On Monday, January 4, 2016, jdent02 <notifications@github.com> wrote:

> Sorry Brian I messed up. Somehow the integrator got switched to
> "BxdfValidate" and I didn't catch it. I'm living with a seven week old
> infant and I think the sleep deprivation is getting to me..... Sorry for
> the hassle.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/110#issuecomment-168887898>
> .
>


-- 
brian.savery@gmail.com
508-274-8700
