### ISSUE TITLE
Images are loaded very very long

### ISSUE THREAD

**Issue by mifth** [bsavery/PRMan-for-Blender#112]
Hi.

I tried to add a simple png texture 2048x2048.
IT was opened about 3 minutes. And IT only opened a scene!
I guess this is because Image Convertation for prman. Is it possible to use png/tiff/jpg images directly for prman?

Here is my simple material:
![selection_003](https://cloud.githubusercontent.com/assets/2251298/9343273/9bea232a-4609-11e5-801d-29ccc6ddb507.png)

Most people use png in blender community. Cycles opens png/tiff/jpg images immideately.

The same issue is with jpg and tiff textures.

If you need I can attach a simple scene. But you can open any texture and see loading time issue.
In this way it will be difficult to set materials and make test renders with prman.

Thanks.

**Comment by mifth** [comment]
Also, cycles can open psd files immideately too.

**Comment by bsavery** [comment]
I'm sorry I can't understand the question.  Please attach a scene.  Which part is taking a long time to load exactly?

**Comment by mifth** [comment]
Here is test scene https://dl.dropboxusercontent.com/u/26887202/blender/test_prman.zip
The scene will be loaded about 2 minutes on my machine.
And if i want to render again - it will be loaded 2 minutes again.

**Comment by bsavery** [comment]
Fixed.

If you're curious as to what was going on, we look for all the objects and export textures for them, unfortunately we were export textures for all the objects in the scene, so actually we were converting the same texture over and over again for each monkey.

As a side node there's a checkbox in the scene settings: Always recompile textures.  You can uncheck that to make it even faster.  If you change your texture it will still update the texture.

**Comment by mifth** [comment]
Thank you a lot!
Is it possible to convert images per material? Not per mesh.
Blender has instanced materials. For example 10 objects (monkey, cube, cylinder..) can have one material.

**Comment by mifth** [comment]
Also, it would be cool to add auto-recompile textures feature.
When texture is changed (it can be measured by hash or file size) - there will be auto recompile of the texture.

And an artist does not need to think about compiling things for textures at all. Very desirable feature.

**Comment by bsavery** [comment]
To your first question:
We could do textures per material, but then you might convert a bunch of textures for materials that aren't attached to anything.  I suppose we can figure out if they're attached.

To your second question.  Unchecking the checkbox I mentioned "Always recompile textures" does just what you described.

**Comment by mifth** [comment]
Ok, Thanks a lot for answering. :)

**Comment by MWY3510** [comment]
Sorry but a quick question. Does it make sense to have the default behaviour of the recompile textures ckeck-box set to be false now?

**Comment by bsavery** [comment]
Yes

On Wednesday, August 19, 2015, MWY3510 <notifications@github.com> wrote:

> Sorry but a quick question. Does it make sense to have the default
> behaviour of the recompile textures ckeck-box set to be false now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/112#issuecomment-132749422>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
Ok, I'll submit that with my next changes.
