### ISSUE TITLE
Textures losing the filename

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#113]
MWY do you want to take a look at this?  I believe it may be related to the texture changes or maybe because of the backwards slashes?

https://renderman.pixar.com/forum/showthread.php?s=&threadid=28793

**Comment by MWY3510** [comment]
Sure I'll take a look.

**Comment by MWY3510** [comment]
Ok, sorry for the absence. I now have some time to look at this.

**Comment by MWY3510** [comment]
I just tested it. I don't think there is a problem any more. I was able to use many textures in the same folder and the exporter will use the right names.

**Comment by bsavery** [comment]
Can you reply in the thread?  Thanks for looking!

On Thursday, August 20, 2015, MWY3510 <notifications@github.com> wrote:

> Closed #113 <https://github.com/bsavery/PRMan-for-Blender/issues/113>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/113#event-388352395>.
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
I just did. Thanks for bringing this to my attention.
