### ISSUE TITLE
Shutter shape options

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#115]
On the 1.0 wishlist - shutter shape options:
aka shutter opening:
http://renderman.pixar.com/resources/current/RenderMan/cameramodel.html#the-shutter-model

There are already settings for it in the Renderman scene settings.  Possibly just needs to be exposed and put in rib.

**Comment by jdent02** [comment]
I'm in favor.

**Comment by bsavery** [comment]
FIxed.
