### ISSUE TITLE
Rib Archiving workflow

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#117]
1.0 Wishlist item:
Basically here's how I see this workflow going, (And believe this is basically how it worked in 3delight addon).

1.  User clicks "Export Archive" on object.
2.  Rib archive is exported for object and bounding box saved.
3.  Object in Blender UI is drawn as box? 
4.  In rib gen, the archive export is skipped for that object, and just read in from the previous file.

Pretty straightforward really the only part needed I think is the button and mechanism to launch the archive export.  We'd probably want some mechanism to switch an object to use an already baked archive.  The other issue is exporting shaders with it.

**Comment by jdent02** [comment]
With this system would you still be able to manually assign an archive to replace an object in the RIB at render time?  When I get the camera close to a model it wouldn't work well to just have a bounding box visible.

**Comment by MWY3510** [comment]
Here is a progress picture.
![example archiving](https://cloud.githubusercontent.com/assets/9410101/13592279/a1e7d39a-e4be-11e5-94d9-2ec473c81984.jpg)

**Comment by bsavery** [comment]
Fixed.
