### ISSUE TITLE
Deep compositing 

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#118]
Feature request for deep output.

**Comment by bsavery** [comment]
This will hold off until deep compositing is in blender...

**Comment by jdent02** [comment]
I wouldn't necessarily hold off until that point.  With Nuke being available in a non-commercial version there's still an avenue for Blender people to use deep comp data.

**Comment by jdent02** [comment]
FYI this one looks like it's taken care of......

**Comment by MWY3510** [comment]
True.
