### ISSUE TITLE
Values question

### ISSUE THREAD

**Issue by mifth** [bsavery/PRMan-for-Blender#119]
Hi.

I found that materials values have limitation from 0 to 1.0. Is it ok?
![_001](https://cloud.githubusercontent.com/assets/2251298/9438706/0cc0d388-4a69-11e5-8eae-1d71d3c13ef4.png)

As far as i know many engines can make values more than 1.0.
And cycles too.

**Comment by MWY3510** [comment]
Hello mifth,

These values are being set by the args files that are provided for each
shader. While I think it is possible for these values to be over-driven I'm
not sure how each shader would handle it. If you want, the color values can
still be set to values higher than 1.0. Let me know if you have any other
questions.

MWY3510

**Comment by mollenborg** [comment]
0.0 to 1.0 is correct - see it as 0 - 100%

Kind regards
Kristian Mollenborg

2015-08-24 13:05 GMT+02:00 mifth <notifications@github.com>:

**Comment by mifth** [comment]
I found that SubSurface shader has some values more than 1.0.
![_003](https://cloud.githubusercontent.com/assets/2251298/9440020/a03f71ea-4a74-11e5-8b9b-0f20192d4944.png)

**Comment by bsavery** [comment]
Yes.  The design of the Disney principled bxdf is specifically to have all values limited from 0-1. 

https://disney-animation.s3.amazonaws.com/library/s2012_pbs_disney_brdf_notes_v2.pdf

**Comment by mifth** [comment]
Ok, thanks.
