### ISSUE TITLE
Open subdiv creases don't seem to be exported

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#122]
See thread:
https://renderman.pixar.com/forum/showthread.php?s=&threadid=28865

**Comment by jdent02** [comment]
Looks like it works now after your last commit.  Must be sure to exit out of edit mode for the crease to 'take'.

**Comment by bsavery** [comment]
Yes. I would expect that

On Tuesday, August 25, 2015, jdent02 <notifications@github.com> wrote:

> Looks like it works now after your last commit. Must be sure to exit out
> of edit mode for the crease to 'take'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/122#issuecomment-134784641>
> .
>


-- 
brian.savery@gmail.com
508-274-8700
