### ISSUE TITLE
Pattern nodes should be categorized further. 

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#123]
Pattern nodes are all in one "bin" now.  They could be broken down to Color, texture, noise, utility, etc.  

The one question is how you keep track of the list.  The addon could have it hard coded, because there is no info in the args files currently for subtype of pattern...

Or of course on the RenderMan side that might be able to be added to args files, but you might always encounter and args file without the category.

**Comment by MWY3510** [comment]
Seems that this is resolved in 21. Thoughts Brian?

**Comment by bsavery** [comment]
Done.
