### ISSUE TITLE
PRMan hair color based on texture

### ISSUE THREAD

**Issue by JeannotLandry** [bsavery/PRMan-for-Blender#126]
First of all, thank you very much for your hard work implementing PRman for Blender :)

I just have a quick question about hair.

How can I use a texture as primary fur colour?

Cycles Render & Nodes
![furtexturecycles](https://cloud.githubusercontent.com/assets/14031486/9562905/826afec6-4e4f-11e5-9e9d-d8719ce4189e.jpg)

PRMan render & nodes Seems to map the texture along the strands, which is cool but how can I use the texture as main colour with the mesh UVs?
![furtextureprman](https://cloud.githubusercontent.com/assets/14031486/9562906/9017ff92-4e4f-11e5-9a64-35bf87255194.jpg)

bsavery : We'd need to output the mesh uv into the rib, which would be possible. Just don't do it yet. Can you log an issue here for that?

Done!

**Comment by MWY3510** [comment]
I am sorry but this is kind of funny. When I wrote the original hair export I forgot all about texturing. When Dylan put out his tutorial on renderman 20, I remembered and then promptly forgot after one hectic night of trying to get it to work. Anyway this would be a good feature to have. If anyone has a question about the hair export let me know.

MWY3510

**Comment by JeannotLandry** [comment]
MWY3510,

Well, having the ability to use textures on strands is awesome for things like ferns and grass and should remain there as an option. In certain case having the texture affect all the strands would be beneficial for things like animal fur like a tiger or anything that require complex colours in textures.

**Comment by bsavery** [comment]
Why did you close this?

**Comment by JeannotLandry** [comment]
I didn't close it? Did I press on the wrong button?

**Comment by JeannotLandry** [comment]
Sorry about that, I just noticed the close and comment button lol. My bad
I re opened the ticket.

**Comment by MWY3510** [comment]
I think I will have some time to look at this today along with UI fixes.
MWY3510

**Comment by JeannotLandry** [comment]
No Rush ;)

**Comment by bsavery** [comment]
Think I have a solution for this.  Need to test a bit more.  Also I was thinking of adding a check box in the hair options rather than always outputting them by default as it does incur some overhead...

**Comment by bsavery** [comment]
Committed.  In the hair settings enable "Export Emitter UV" and then in your manifold in the shading network us "scalpS" and "scalpT" in the s,t names

**Comment by lyonelDahu** [comment]
Hi there,

I'm doing some heavy fur in blender, and I'm having a lot of trouble with it. The first thing I'm experiencing is about using a texture to color my fur. I did exactly what you said, and it's working for simple uvs. But when I'm trying to do the same thing with udims, it's unfortunately not working anymore... I feel like the export Emitter UV is only exporting the uvs between 0 and 1, or something like that :).

Do you have any suggestion ? I feel that I tried everything, with no luck. Thank you very much for your help !

Lyonel
