### ISSUE TITLE
Direct specular pass not exported

### ISSUE THREAD

**Issue by Lightye** [bsavery/PRMan-for-Blender#129]
http://sawe.asuscomm.com/published/renderman/blender/issues/20150903_specular_direct_pass_not_exported

**Comment by MWY3510** [comment]
The video does not work for me. Just in case can you write out the problem also.

MWY3510

**Comment by bsavery** [comment]
Can you attach the scene.rib file?  In particular the Lines with Display "..." in them

**Comment by Lightye** [comment]
Option "bucket" "string order" ["horizontal"]
DisplayChannel "color diffuse" "string source" ["color lpe:diffuse"]
DisplayChannel "color indirectdiffuse" "string source" ["color lpe:indirectdiffuse"]
DisplayChannel "color indirectspecular" "string source" ["color lpe:indirectspecular"]
Display "images/Scene_0001.exr" "openexr" "rgba" "quantize" [0 0 0 0]
Display "+images/Scene_0001.z.exr" "openexr" "z" "quantize" [0 0 0 0] "int asrgba" [1]
Display "+images/Scene_0001.diffuse.exr" "openexr" "diffuse" "quantize" [0 0 0 0] "int asrgba" [1]
Display "+images/Scene_0001.indirectdiffuse.exr" "openexr" "indirectdiffuse" "quantize" [0 0 0 0] "int asrgba" [1]
Display "+images/Scene_0001.indirectspecular.exr" "openexr" "indirectspecular" "quantize" [0 0 0 0] "int asrgba" [1]
DisplayChannel "color Ci" 
DisplayChannel "float a" 
DisplayChannel "color mse" "string source" ["color Ci"] "string statistics" ["mse"]
DisplayChannel "color albedo" "string source" ["lpe:nothruput;noinfinitecheck;noclamp;unoccluded;overwrite;C(U2L)|O"]
DisplayChannel "color diffuse" "string source" ["color lpe:C(D[DS]*[LO])|O"]
DisplayChannel "color diffuse_mse" "string source" ["color lpe:C(D[DS]*[LO])|O"] "string statistics" ["mse"]
DisplayChannel "color specular" "string source" ["color lpe:CS[DS]*[LO]"]
DisplayChannel "color specular_mse" "string source" ["color lpe:CS[DS]*[LO]"] "string statistics" ["mse"]
DisplayChannel "float z" "string source" ["float z"] "string filter" ["gaussian"]
DisplayChannel "float z_var" "string source" ["float z"] "string filter" ["gaussian"] "string statistics" ["variance"]
DisplayChannel "normal normal" "string source" ["normal Nn"]
DisplayChannel "normal normal_var" "string source" ["normal Nn"] "string statistics" ["variance"]
DisplayChannel "vector forward" "string source" ["vector motionFore"]
DisplayChannel "vector backward" "string source" ["vector motionBack"]
Display "+images/Scene_0001.denoise.exr" "openexr" "Ci,a,mse,albedo,diffuse,diffuse_mse,specular,specular_mse,z,z_var,normal,normal_var,forward,backward" "int asrgba" [1]
PixelVariance 0.005

**Comment by Lightye** [comment]
![specular_direct_missing](https://cloud.githubusercontent.com/assets/14073317/9648294/6f08d664-51e7-11e5-883f-4e9ba3b5f0a2.png)

**Comment by bsavery** [comment]
Fixed.
