### ISSUE TITLE
what is the problem

### ISSUE THREAD

**Issue by LynXcode** [bsavery/PRMan-for-Blender#13]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.74\scripts\modules\addon_utils.py", line 306, in enable
    mod = __import__(module_name)
  File "C:\Users\C. Jack Sparrow\AppData\Roaming\Blender Foundation\Blender\2.74\scripts\addons\PRMan-for-Blender-master\__init__.py", line 40, in <module>
    from . import engine
  File "C:\Users\C. Jack Sparrow\AppData\Roaming\Blender Foundation\Blender\2.74\scripts\addons\PRMan-for-Blender-master\engine.py", line 35, in <module>
    import prman
ImportError: No module named 'prman'

**Comment by bsavery** [comment]
Did you install renderman?  
https://github.com/bsavery/PRMan-for-Blender/blob/master/installation.txt

**Comment by JSKjaer** [comment]
check your RMANTREE env variable in the DOS command terminal. It may still point to RM19. I had this problem as well. The Win7 env variable pointed to RM20 but DOS did not. I rebooted Windows and then the DOS env was in sync with Windows. I hope this helps

**Comment by Perrishnikov** [comment]
@LynXcode I had a similar (same?) issue because I didnt have RenderMan installed, just the addon. No error after install.

**Comment by LynXcode** [comment]
:( I have version 19. I try addons,when they opened rm20 free install for customers I wish I knew python for blender.  I like pixar renderman, and all compliant.  I try to run all addons and all addons have got bug because blender developers are constant change blender api. I have to do three version, 2.49 (for mosaic, bge), 2.63(3delight and pixie plugin run correctly), and new release for wonder whats new change. (sorry my english)..

**Comment by MWY3510** [comment]
LynXcode,

   You need to have prman version 20 for the addon to work. Also it would be a good idea to use blender version 2.75a as this is the version that the addon is tested against before update.

Hope this helps,
MWY3510

**Comment by LynXcode** [comment]
thank you
