### ISSUE TITLE
Crash probably material related

### ISSUE THREAD

**Issue by Lightye** [bsavery/PRMan-for-Blender#130]
http://sawe.asuscomm.com/published/renderman/blender/issues/20150904_crash_probably_material_related.zip

All info in the zip.

**Comment by Lightye** [comment]
Sorry wrong date, it is the 3rd.

**Comment by Lightye** [comment]
No rush please, this ticket is just put here so it's not forgotten. What you do is fantastic and impressive. Please hang in there! In the end you will be the people who made this possible.

**Comment by bsavery** [comment]
Hmmm.  So when I click on the materials editor I don't get a crash, however when I open the preview pane I do, can you confirm keeping that closed works?  And that it crashes when the preview pane is open.

**Comment by Lightye** [comment]
Crash probably material related #130
More testing

Hmmm. So when I click on the materials editor I don't get a crash, 
however when I open the preview pane I do, can you confirm keeping that closed works? 
And that it crashes when the preview pane is open.

Action: Attempt to open file: 1st try ok.
Action: Attempt to open file: 2nd try crash prior to opening file. 
Action: Using Node Editor. Open Preview Panel, no crash first or second time.
Action: File is open, attempt to open via File Editor => Crash
Action: Repeat the above line => No crash (approximately 10+... times)
Action: Close Blender.
Action: Open file. Use Node Editor. Click on material button (think it was) => Crash! (preview pane closed all the time)
...

**Comment by Lightye** [comment]
Opened via terminal. Look ok a few seconds. Click on material button. Crash. (repeated exactly the same)

Terminal sais:

Last login: Thu Sep  3 13:52:56 on ttys001
ws102:~ s3rvic3$ /Applications/Blender/2.75/blender.app/Contents/MacOS/blender 
ndof: 3Dx driver not found
Read new prefs: /Users/s3rvic3/Library/Application Support/Blender/2.75/config/userpref.blend
found bundled python: /Applications/Blender/2.75/blender.app/Contents/MacOS/../Resources/2.75/python
read blend: /Users/s3rvic3/Downloads/20150904_crash_probably_material_related-2/scificity_remake_v05.blend
read blend: /Users/s3rvic3/Downloads/20150904_crash_probably_material_related-2/scificity_remake_v05.blend
txmake Error: Could not load input image [/Users/s3rvic3/Downloads/scificity_matte_v046.tif]
     file: /Users/s3rvic3/Documents/prman_for_blender/scificity_remake_v05/textures/scificity_matte_v046.tex
Writing: /tmp/scificity_remake_v05.crash.txt
Segmentation fault: 11
ws102:~ s3rvic3$ /Applications/Blender/2.75/blender.app/Contents/MacOS/blender 
ndof: 3Dx driver not found
Read new prefs: /Users/s3rvic3/Library/Application Support/Blender/2.75/config/userpref.blend
found bundled python: /Applications/Blender/2.75/blender.app/Contents/MacOS/../Resources/2.75/python
read blend: /Users/s3rvic3/Downloads/20150904_crash_probably_material_related-2/scificity_remake_v05.blend
txmake Error: Could not load input image [/Users/s3rvic3/Downloads/scificity_matte_v046.tif]
     file: /Users/s3rvic3/Documents/prman_for_blender/scificity_remake_v05/textures/scificity_matte_v046.tex
Writing: /tmp/scificity_remake_v05.crash.txt
Segmentation fault: 11
ws102:~ s3rvic3$

**Comment by Lightye** [comment]
Think I see something a few lines up. Probably that's it. Had a similar issue with Jano's file when not setting textures. However, the environment light, in his file, is more tolerant to missing files. It creates an "exception", but will crash if attempted to render. Think the texture node goes crazy without the file, or maybe something related to that.

**Comment by bsavery** [comment]
This MAY have been fixed with the texture fixed.  

Long story short... rib generation can cause segfault.  I will investigate if we can do a try/catch around that like you mentioned.

**Comment by bsavery** [comment]
Just to confirm, did this fix the issues for you?  Seems like it work on my end.

**Comment by Lightye** [comment]
Sounds great. At a countryside ATM, will check this when back.

**Comment by Lightye** [comment]
Today 7 Sept the latest plug-in was installed. This case have been tested with two separate instances of the same problematic file (i.e. copies). Somehow it was possible, using a step by step approach, to restore the stability of the file. The references to textures was first removed in the pxrTexture nodes and later they were set to other existing textures. After that it was possible to click on all material icons and there was no crash. If there is a reference to a missing texture there will still be a crash (as expected for now).

**Comment by Lightye** [comment]
Here is the error report from /tmp/scificity_remake_v05.crash.txt, which you probably already know well: 

# Blender 2.75 (sub 0), Commit date: 2015-07-07 14:56, Hash c27589e
bpy.context.space_data.context = 'MATERIAL'  # Property
bpy.ops.node.view_all()  # Operator
bpy.ops.object.select_all(action='TOGGLE')  # Operator
bpy.ops.object.select_all(action='TOGGLE')  # Operator
bpy.ops.object.select_all(action='TOGGLE')  # Operator
bpy.ops.node.select(mouse_x=173, mouse_y=325, extend=False)  # Operator
bpy.ops.node.translate_attach(TRANSFORM_OT_translate={"value":(29.2912, 37.3061, 0), "constraint_axis":(False, False, False), "constraint_orientation":'GLOBAL', "mirror":False, "proportional":'DISABLED', "proportional_edit_falloff":'SMOOTH', "proportional_size":1, "snap":False, "snap_target":'CLOSEST', "snap_point":(0, 0, 0), "snap_align":False, "snap_normal":(0, 0, 0), "gpencil_strokes":False, "texture_space":False, "remove_on_cancel":False, "release_confirm":True}, NODE_OT_attach={})  # Operator
bpy.ops.node.select(mouse_x=402, mouse_y=324, extend=False)  # Operator
bpy.ops.node.translate_attach(TRANSFORM_OT_translate={"value":(-33.2854, 29.312, 0), "constraint_axis":(False, False, False), "constraint_orientation":'GLOBAL', "mirror":False, "proportional":'DISABLED', "proportional_edit_falloff":'SMOOTH', "proportional_size":1, "snap":False, "snap_target":'CLOSEST', "snap_point":(0, 0, 0), "snap_align":False, "snap_normal":(0, 0, 0), "gpencil_strokes":False, "texture_space":False, "remove_on_cancel":False, "release_confirm":True}, NODE_OT_attach={})  # Operator
Traceback (most recent call last):
  File "/Applications/Blender/2.75/blender.app/Contents/Resources/2.75/scripts/addons/PRMan-for-Blender-master/__init__.py", line 68, in update
    engine.update(self, data, scene)
  File "/Applications/Blender/2.75/blender.app/Contents/Resources/2.75/scripts/addons/PRMan-for-Blender-master/engine.py", line 104, in update
    engine.render_pass.gen_preview_rib()
  File "/Applications/Blender/2.75/blender.app/Contents/Resources/2.75/scripts/addons/PRMan-for-Blender-master/engine.py", line 531, in gen_preview_rib
    self.convert_textures(get_texture_list_preview(self.scene))
  File "/Applications/Blender/2.75/blender.app/Contents/Resources/2.75/scripts/addons/PRMan-for-Blender-master/engine.py", line 550, in convert_textures
    os.path.getmtime(in_file) <= \
  File "/Applications/Blender/2.75/blender.app/Contents/MacOS/../Resources/2.75/python/lib/python3.4/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Users/s3rvic3/Downloads/20150904_crash_probably_material_related/bg_skyline.psd'

location: <unknown location>:-1
  # Error

# backtrace
0   blender                             0x0000000100c7f5ca BLI_system_backtrace + 58
1   blender                             0x000000010017aabb blender_crash_handler_backtrace + 43
2   blender                             0x000000010017a5b3 blender_crash_handler + 659
3   libsystem_platform.dylib            0x00007fff99080f1a _sigtramp + 26
4   libsystem_c.dylib                   0x00007fff7ccbf6b8 __global_locale + 0

**Comment by Lightye** [comment]
I understand the limitation at the moment, and that this vulnerability will be solved/worked around somehow. Cheers!

**Comment by bsavery** [comment]
So I can't recreate this with MWY's latest fixes...

**Comment by Lightye** [comment]
This case was tested today 14 Sept 2015 three times, and it is perfectly clear that this part is well solved. Well done!
