### ISSUE TITLE
Projector Manifold requires extra information

### ISSUE THREAD

**Issue by davemj** [bsavery/PRMan-for-Blender#133]
This might be me not understanding the Renderman environment, but I have found the following:

When Assigning the PxrProjector  I have found that unless you put something in the Coord field (a space will do), PRman will not render out the image. PRMan itself reports and error messages stating that a coordination system must be named.  This does not match the renderman documentation which states that "" will do. 

So I am not sure that this is a bug in PRMan-for-Blender, PRMan or the PRMan documentation.  (Or me)

**Comment by bsavery** [comment]
Sounds like a documentation bug.  You definitely need something there.

**Comment by davemj** [comment]
Documentation stats the following. 

Coordinate System

Name of coordinate system transform (e.g. place3dTexture node in Maya).
RIB: string coordsys
Default: ""

Which does seem to indicate that it could be blank.   Happy to accept it as a documentation error and that something needs to be put in the slot. (And I will go and learn what a coordinate system transform is, and try and work out how it might link in with blender ;-))

**Comment by bsavery** [comment]
Cool.  I'll log that doc bug back at work on monday.  The default coordinate systems are "shader, object, camera, world,.." Normally if you export a coordinate space (there's a button to do this that might not work at the moment but is an easy fix).  You could say export the coordinate space of an object "Cube" and use that coordinate space in other objects.
