### ISSUE TITLE
Output PNG is empty

### ISSUE THREAD

**Issue by mollenborg** [bsavery/PRMan-for-Blender#134]
Hi

I have problems with generate frames as PNG files - they seems to be empty.

Kind Regards
Kristian

**Comment by MWY3510** [comment]
OK, I took a quick look and the error that is produced is this        Reached EOF while decoding PNG
IMB_ibImageFromMemory: unknown fileformat (/path/to/Documents/Test34/images/Scene_0001.png)

**Comment by bsavery** [comment]
I'll have to take a look at the png display driver.  I know it's fairly trivial as most people use the tiff or openexr for RenderMan

**Comment by MWY3510** [comment]
PNG display driver is disabled for the immediate future. Closing issue.
