### ISSUE TITLE
PRMan addon errors 

### ISSUE THREAD

**Issue by SnyderMark** [bsavery/PRMan-for-Blender#135]
Has anyone else encountered this? TIA, Mark
Blender 2.75, OSX 10.10.4 

![screen shot 2015-09-12 at 5 28 03 pm](https://cloud.githubusercontent.com/assets/14253745/9833916/cbf98032-5974-11e5-8e8b-8e50395d4d85.png)

**Comment by Lightye** [comment]
No, but I'm wondering if you installed the plug-in under "/Applications/Blender...". You seem to have some path errors. On my OS X I put the plug-in under a folder in the actual "Blender" app (right-click and show contents, then navigate to "Contents > Resources > 2.75 > scripts > add ons", did you place the plugin there?

**Comment by SnyderMark** [comment]
Hi Lightye,

Thanks for the reply. I have placed the entire PRMan folder into Blender's
add ons folder. I used the same path as you showed in your example. Did you
place the directory there or the contents?

**Comment by Lightye** [comment]
As you did, It should be the entire folder with the default name "PRMan-for-Blender-master". 

In "/Users/[username]/Library/Application Support/Blender/2.75/scripts/addons I don't have anything prman related. Why are some of your paths pointing there? I'm on OS X 10.10.5 (should probably not matter here). Please make sure you put the plugin in Root => /Applications... (as above). Also, as you did I dropped the entire folder in addons, and did not use Blender's internal "install script" thing.

**Comment by bsavery** [comment]
Actually, It looks like you moved a file prman.py to the addon folder from the RenderMan Pro Server directory?  From the error it mentions prman.py is in the addon folder.  

That won't work.  That file needs to be in RMANTREE/bin.  The reason is that it trys to load libprman.dll from there.

**Comment by SnyderMark** [comment]
After looking around I discovered PRMan stuff in my Library directory. No
idea how it got there. Deleted it all and PRMan is now running. Thanks for
the tips. Looking forward to havu=ing some fun with this! Cheers!
