### ISSUE TITLE
Object motion missing from parented objects when parent is animated.

### ISSUE THREAD

**Issue by fjuhec** [bsavery/PRMan-for-Blender#136]
Hi,

First, thank you for a great exporter. It has been a great help for me to continue work and add new features to the exporter I am coding for Mitsuba Renderer. Learned a lot from reading through your code.

I have reused the code for getting animation data for motion blur and found out that objects with no animation but an animated parent where not having its motion exported.

The code on line 1504 of export.py
```python
    if ob.animation_data is not None or ob.constraints:
        if ob.name not in motion['transformation'].keys():
            motion['transformation'][ob.name] = []

        if ob.parent:
            mat = ob.parent.matrix_world * ob.matrix_local
        else:
            mat = ob.matrix_world

        motion['transformation'][ob.name].append(mat.copy())
```

Is correctly using the parent matrix on parented objects but is missing a check to see if the parent is animated in case the parented object is not.

This modification fixes the issue for me:
```python
    if ob.animation_data is not None or ob.constraints or \
            (ob.parent and (ob.parent.animation_data is not None or ob.parent.constraints)):
```

Tested also with Renderman exporter and fixed the issue.
To test the issue I am using the BMW benchmark scene in case you want to test.
https://www.dropbox.com/s/ip1t0gqiu1bk5vr/BMW1M-MikePan.blend?dl=0
You can animate the car with the carController object and notice some objects stay behind because they have no animation but are parented to an animated object.
There is also an issue on this scene with rib files not being written for some dupli objects but have not investigated it.

Thanks,
Francesc

**Comment by bsavery** [comment]
Hi Franscesc.  I'm actually about to check in a rewrite to that bit of code.  You might find it interesting.  Basically I wanted to merge the finding of all data blocks with the motion caching bit.  So that fix might not be directly translatable but I'll make sure the equivalent gets in.

And thanks for the scene.

**Comment by bsavery** [comment]
And for the record when writing a few things I looked at the Mitsuba code for inspiration ;)

**Comment by fjuhec** [comment]
Nice, I will sure check the rewritten code.
Thanks, I am glad Mitsuba exporter code may have helped you, I consider a lot of the code I write an example on how not to do things ;)

**Comment by bsavery** [comment]
Just another thought on this.  We don't really need to cache the child motion in the above case if the child motion is static relative to the parent.  If the rib is written correctly it should be.. :

(Parent instance)
     Motion Begin (parent)
          Transform
          Transform
    Motion End

    Parent Geometry...

    (Child Instance)
        Transform
        Child Geometry
   (end Child)
(End Parent)

If the rib is written this way the motion should be hierarchical.  Of course if the child is moving relative to the parent, that should have its motion cached.

**Comment by bsavery** [comment]
Either way take a look at the latest checkins.  If you need any explanations let me know.

**Comment by fjuhec** [comment]
I am testing the most recent commit. Never thought of nesting children to parent on export because I believe Mitsuba does not support it.
There is a missing pair of () missing, nothing serious:
Line 1590 of export.py should be:
```python
for name, instance in _instances.items():
```
After fixing this I made a test of one issue I thought might arise from the new method of gathering data and output children nested in parents.
What if the parent is an empty or not renderable?
With current code, objects that are parented to an empty or an object hidden from render are not exported.
Also, I tried an object parented to another object and while the parent has motion blur, the child does not.
![mblur](https://cloud.githubusercontent.com/assets/4067896/9845658/e7510176-5acc-11e5-8a10-bdcf6dc949f7.jpg)
In this image:
- Green: Animated cube and child sphere. Cube is set as hidden from render. Sphere is not rendered.
- Blue: Animated cone and child torus. Torus does not show motion blur.
- Red: Animated empty and child cube. Cube is not rendered.

I have not investigated more. Will read through the code later.

**Comment by bsavery** [comment]
Hmmm.... yes.  That should be an easy fix.


On Mon, Sep 14, 2015 at 1:48 AM, fjuhec <notifications@github.com> wrote:

> I am testing the most recent commit. Never thought of nesting children to
> parent on export because I believe Mitsuba does not support it.
> There is a missing pair of () missing, nothing serious:
> Line 1590 of export.py should be:
>
> for name, instance in _instances.items():
>
> After fixing this I made a test of one issue I thought might arise from
> the new method of gathering data and output children nested in parents.
> What if the parent is an empty or not renderable?
> With current code, objects that are parented to an empty or an object
> hidden from render are not exported.
> Also, I tried an object parented to another object and while the parent
> has motion blur, the child does not.
> [image: mblur]
> <https://cloud.githubusercontent.com/assets/4067896/9845658/e7510176-5acc-11e5-8a10-bdcf6dc949f7.jpg>
> In this image:
>
>    - Green: Animated cube and child sphere. Cube is set as hidden from
>    render. Sphere is not rendered.
>    - Blue: Animated cone and child torus. Torus does not show motion blur.
>    - Red: Animated empty and child cube. Cube is not rendered.
>
> I have not investigated more. Will read through the code later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/136#issuecomment-140003949>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
Been working on a few things here.  Any chance you can attach the above scene?

**Comment by fjuhec** [comment]
Sure, https://app.box.com/s/l2gveggjyb49vjgpz8xq85rh7k6g7ngl
All spheres and the blue cube should appear in render with motion blur.

This is the current render result using Renderman:
![prman](https://cloud.githubusercontent.com/assets/4067896/9957673/40a9d62a-5e02-11e5-823c-72ea06190e1a.jpg)

This is with cycles:
![cycles](https://cloud.githubusercontent.com/assets/4067896/9957668/3b8f80f4-5e02-11e5-930e-1478da24c043.jpg)

**Comment by bsavery** [comment]
Ok great.  Wanted to check it with the latest fixes.  Looks good now.

Brian

**Comment by fjuhec** [comment]
Nice!
There is still some issue.
With the BMW scene, the wheels don't have motion blur.
![bmw-blur](https://cloud.githubusercontent.com/assets/4067896/9966559/d4d05064-5e3d-11e5-89d5-b952e58e8839.jpg)

**Comment by bsavery** [comment]
How do I make the tires rotate with the rig?

**Comment by fjuhec** [comment]
I believe the tires rotate with a driver, when the car controller moves along X the tires rotate automatically.

The scene is not mine, I use it just for testing. I uploaded it here:
https://app.box.com/s/9e58cn1ybrkgslh06h6tgbxzrcgchzbm

**Comment by bsavery** [comment]
With my various testing scenes, the latest changes fixes all the issues.  I'll keep testing though.

**Comment by fjuhec** [comment]
I have run a few tests and there are still some issues with dupli objects. In the BMW scene, a Cube mesh used on the brakes appears bigger than it should because it's original scale seems to be lost on the export process. Also, in a simple scene with a cube and child spheres as face duplis, the parent cube is visible rendering when it shouldn't.
In the Mitsuba exporter I ended taking a slightly different approach to gathering all data using code from you and also adapting code from Cycles synchronization code because I cannot nest children inside parents. If you want to check the code let me know if you have any questions about it, I think it handles all possible dupli objects, duplis of duplis, duplis with hair and dupli lamps.

**Comment by tobbew79** [comment]
I tested this and it seems to work with parenting, but not when constraints are used (child of constaints and copy location constraints are those I tested).

**Comment by bsavery** [comment]
In retrospect it might be easier to do what @fjuhec mentions but in a deeply nested and animating parent tree less efficient.  Anyway i have a fix for the brake issue, also will update with a nice test scene.
