### ISSUE TITLE
No render output with armature

### ISSUE THREAD

**Issue by sloppyjava** [bsavery/PRMan-for-Blender#137]
After parenting an object to an armature, the object no longer renders. un-parenting allows the object to be rendered again. the same seems to be true for any object that is parented to a non-rendering object.  It seems like the "Restrict rendering" setting is propagated to the children when they should be independent settings.  Sorry if this is already a known issue, but i couldn't find anything about it.

There is also an issue with hair not using the bxdf that is assigned to it.  after watching user "Blender Nitidus" hair video, i see that my settings are the same, but unlike in the video, hair is always gray. emitter is using the shader, hair is not.

Also, I would like to say this project is amazing, and once issues like this are hammered out I will be buying a PRman license (and more processors!!) for sure.

Thanks for your amazing work!

**Comment by bsavery** [comment]
Sorry was redoing the parent/child rib gen so that we only do motion blur on the parent if it's moving.  Should work now.
