### ISSUE TITLE
I can't render with the blender render window, nor with "it".

### ISSUE THREAD

**Issue by SALZKARTOFFEEEL** [bsavery/PRMan-for-Blender#139]
Hi.
I really like this plugin for blender. Well, at least the things that are working.
One HUGE problem I have is the fact, that I can't even render. I tried much, but I can't get it to work.
If I click on "render", or press F12, it says: "PRMan: R50009 {SEVERE} License location is not set in rendermn.ini - aborting." (behind the dot is a weired rectangle in blender) and also another window appears with the title "it" that says: "Failed to get license for 'it'. code 2: No such file or directory license source: pixar.license"
I think, that something went wrong during the installation of Renderman. I also tried to uninstal Renderman, but it just crashed every time.

Please help me! I would love to have this working, but now I just have a render engine, that can't render.

Thanks.

**Comment by jdent02** [comment]
What OS are you using?

**Comment by bsavery** [comment]
Yes, something went wrong with your renderman installation.  Pixar has a forum for license issues: https://renderman.pixar.com/forum/forumdisplay.php?s=&forumid=161

But generally you probably need to run the license app that is the renderman installation directory /bin and then put in your username/password you used when rendering for renderman.

**Comment by SALZKARTOFFEEEL** [comment]
@jdent02 I am using a Windows 10 x64 operating system.

@bsavery Thanks, I just want to notice, that the license app is not in the installation directory, it creates an own path at the programs folder called "\Pixar\RenderManProServer-20.2\bin".
But the license tool is just for buying a commercial license. I am using a non-commercial license for Renderman.
Maybe something else to fix it?

**Comment by davemj** [comment]
When you installed Renderman, did it ask you for your forum username and password. Following that it should have connected back and retrieved a license file for you. Did that appear to work correctly?

**Comment by bsavery** [comment]
Did you figure out your issues?
