### ISSUE TITLE
Some nodes not working correctly

### ISSUE THREAD

**Issue by est77** [bsavery/PRMan-for-Blender#14]
I'm using the latest blender release on linux, with an up to date PRMan-for-Blender.
I can use the addon and render using prman without problems or warnings.
But some prman nodes are not working correctly for me.

![prman_b](https://cloud.githubusercontent.com/assets/409013/8633566/b8b45902-27ce-11e5-9c70-95e8de656919.png)

and I have warnings on the terminal like these:

/usr/local/blender-2.75/addons/PRMan-for-Blender/nodes.py:98
rna_uiItemR: property not found: PxrLMPlasticBxdfNode.Clear Coat
/usr/local/blender-2.75/addons/PRMan-for-Blender/nodes.py:98
rna_uiItemR: property not found: PxrLMSubsurfaceBxdfNode.Subsurface
/usr/local/blender-2.75/addons/PRMan-for-Blender/nodes.py:98
rna_uiItemR: property not found: PxrLMSubsurfaceBxdfNode.Specular
/usr/local/blender-2.75/addons/PRMan-for-Blender/nodes.py:98
rna_uiItemR: property not found: PxrLMSubsurfaceBxdfNode.Clear Coat
/usr/local/blender-2.75/addons/PRMan-for-Blender/nodes.py:98
rna_uiItemR: property not found: PxrLMSubsurfaceBxdfNode.Misc

**Comment by bsavery** [comment]
Fixed: https://github.com/bsavery/PRMan-for-Blender/commit/78832e3fba5809dbe754ad264cd39828580c615a

Although I haven't tested connecting an LMLayer to the overlay socket.  Not sure if that works correctly.

**Comment by est77** [comment]
It works now. Thanks!
