### ISSUE TITLE
Possible lighting bug (lights do not respect visibility settings)

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#140]
Testing out the latest downloads and it seems the lights no longer respect the 'restrict viewport visibility' and 'restrict rendering' checkboxes.  If a light is in the scene, it will always render no matter what these two options are set to.

**Comment by bsavery** [comment]
Restrict Rendering should work now.  Restrict viewport vis is a blender side thing...

**Comment by jdent02** [comment]
Yep, works fine now.  Thanks!
