### ISSUE TITLE
Copying materials

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#143]
It looks like when copying a material the renderman nodetree is not moved. 
Two options here:

1.  When copying a material set the node_tree attribute.
2.  Move nodetrees to the native nodetree rather than under renderman settings.

I'm leaning towards the latter.  But its more work.  Maybe a day's worth and would fix another few minor issues.

**Comment by tobbew79** [comment]
There are other problems with the current material tree. If you create a material, then a texture, then copy the texture (shift+d) it does not create any inputs or outputs from the new texture node.

**Comment by bsavery** [comment]
An update on the above idea of using the native nodetrees... I did some experimenting with this, but one issue is that there does not seem to be a way to only show PRMan nodes.   So say we started using the native shader node tree, the cycles node would show as well as the prman ones.  So I think this might not work...

**Comment by blendtsukai** [comment]
bsavery, isn't this a feature of blender? This way you can create the same type of material for each renderer. I believe this is useful when you want to publish the material on some site.
