### ISSUE TITLE
Python Issues with Windows 10

### ISSUE THREAD

**Issue by frmsaul** [bsavery/PRMan-for-Blender#145]
Hi, im trying to get this to work on my Windows 10 machine.
But when trying to activate it, I get the following error:

http://imgur.com/sJmCz4u

Is it solvable?
How do I deal with it?

**Comment by bsavery** [comment]
Hmmm.... It seems like the addon directory isn't all there.  What do you have in the directory?

Brian

**Comment by frmsaul** [comment]
Which directory?

**Comment by bsavery** [comment]
What you have in your addon directory.


On Tue, Oct 6, 2015 at 9:34 AM, Saul <notifications@github.com> wrote:

> Which directory?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/145#issuecomment-145921185>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by frmsaul** [comment]
Here is the content of the directory:

`
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        10/3/2015  11:31 PM                add_curve_extra_objects
d-----        10/3/2015  11:31 PM                add_curve_sapling
d-----        10/3/2015  11:30 PM                add_mesh_BoltFactory
d-----        10/3/2015  11:31 PM                add_mesh_extra_objects
d-----        10/3/2015  11:31 PM                cycles
d-----        10/3/2015  11:31 PM                io_anim_acclaim
d-----        10/3/2015  11:31 PM                io_anim_bvh
d-----        10/3/2015  11:31 PM                io_anim_c3d
d-----        10/3/2015  11:30 PM                io_anim_nuke_chan
d-----        10/3/2015  11:31 PM                io_coat3D
d-----        10/3/2015  11:30 PM                io_convert_image_to_mesh_img
d-----        10/3/2015  11:31 PM                io_curve_svg
d-----        10/3/2015  11:31 PM                io_export_dxf
d-----        10/3/2015  11:31 PM                io_import_dxf
d-----        10/3/2015  11:31 PM                io_mesh_pdb
d-----        10/3/2015  11:31 PM                io_mesh_ply
d-----        10/3/2015  11:31 PM                io_mesh_raw
d-----        10/3/2015  11:31 PM                io_mesh_stl
d-----        10/3/2015  11:30 PM                io_mesh_uv_layout
d-----        10/3/2015  11:31 PM                io_online_sketchfab
d-----        10/3/2015  11:31 PM                io_scene_3ds
d-----        10/3/2015  11:31 PM                io_scene_fbx
d-----        10/3/2015  11:31 PM                io_scene_ms3d
d-----        10/3/2015  11:31 PM                io_scene_obj
d-----        10/3/2015  11:31 PM                io_scene_vrml2
d-----        10/3/2015  11:31 PM                io_scene_x
d-----        10/3/2015  11:31 PM                io_scene_x3d
d-----        10/3/2015  11:31 PM                io_sequencer_edl
d-----        10/3/2015  11:31 PM                io_shape_mdd
d-----        10/3/2015  11:31 PM                light_field_tools
d-----        10/3/2015  11:31 PM                mesh_inset
d-----        10/3/2015  11:31 PM                mocap
d-----        10/3/2015  11:31 PM                modules
d-----        10/4/2015  12:04 AM                mosaic
d-----        10/3/2015  11:31 PM                netrender
d-----        10/3/2015  11:31 PM                object_fracture
d-----        10/3/2015  11:31 PM                object_fracture_cell
d-----        10/3/2015  11:31 PM                object_print3d_utils
d-----        10/3/2015  11:30 PM                presets
d-----        10/3/2015  11:31 PM                render_copy_settings
d-----        10/3/2015  11:31 PM                render_povray
d-----        10/4/2015  12:10 AM                render_ribmosaic
d-----        10/3/2015  11:31 PM                rigify
d-----        10/3/2015  11:31 PM                space_view3d_math_vis
d-----        10/3/2015  11:31 PM                system_demo_mode
d-----        10/3/2015  11:31 PM                ui_translate
-a----        7/31/2014   4:41 PM            183 .arcconfig
-a----        7/31/2014   4:41 PM            236 .gitignore
-a----        7/31/2014   4:41 PM          26598 add_curve_ivygen.py
-a----       11/14/2014   8:20 AM          28682 add_mesh_ant_landscape.py
-a----        7/31/2014   4:41 PM          13521 animation_add_corrective_shape_key.py
-a----        4/30/2015   4:33 PM          17561 animation_animall.py
-a----         9/1/2015   7:14 PM           7364 bone_selection_groups.py
-a----        10/1/2015   1:34 PM          21859 curve_simplify.py
-a----        7/31/2014   4:41 PM          24063 development_api_navigator.py
-a----        7/31/2014   4:41 PM           8440 development_icon_get.py
-a----         9/1/2015   7:14 PM          21387 game_engine_publishing.py
-a----        7/31/2014   4:41 PM           8923 game_engine_save_as_runtime.py
-a----        7/31/2014   4:41 PM           5604 io_anim_camera.py
-a----        7/31/2014   4:41 PM          38169 io_export_after_effects.py
-a----        8/29/2014   3:55 PM           7041 io_export_pc2.py
-a----        1/28/2015   8:09 AM         108538 io_export_unreal_psk_psa.py
-a----        5/20/2015   8:40 PM          27116 io_import_gimp_image_to_scene.py
-a----         9/1/2015   7:14 PM          23579 io_import_images_as_planes.py
-a----        7/31/2014   4:41 PM          46030 io_import_scene_lwo.py
-a----        7/31/2014   4:41 PM         144453 io_import_scene_mhx.py
-a----        7/31/2014   4:41 PM          51073 io_import_scene_unreal_psa_psk.py
-a----         9/1/2015   7:14 PM         173142 mesh_bsurfaces.py
-a----        9/17/2015   5:11 PM           3016 mesh_custom_normals_tools.py
-a----        11/7/2014   3:00 PM          14588 mesh_f2.py
-a----        6/29/2015   4:54 PM         188150 mesh_looptools.py
-a----        7/31/2014   4:41 PM           3932 mesh_relax.py
-a----       11/16/2009   1:53 AM         845046 mosaic.py
-a----         9/1/2015   7:14 PM         179205 node_wrangler.py
-a----        8/29/2014   3:55 PM           5628 object_add_chain.py
-a----         9/1/2015   7:14 PM           7810 object_animrenderbake.py
-a----        9/10/2015   8:53 PM          26856 object_cloud_gen.py
-a----        4/30/2015   4:33 PM          11073 object_edit_linked.py
-a----        11/7/2014   3:00 PM          13369 object_grease_scatter.py
-a----       12/10/2014   9:00 PM          29039 paint_palette.py
-a----         9/1/2015   7:14 PM          15623 render_auto_tile_size.py
-a----         9/1/2015   7:14 PM          25708 render_freestyle_svg.py
-a----        8/29/2014   3:55 PM           3397 space_view3d_3d_navigation.py
-a----         9/1/2015   7:14 PM          30805 space_view3d_copy_attributes.py
-a----        4/30/2015   4:33 PM          28445 space_view3d_materials_utils.py
-a----        3/31/2015   3:37 PM          51181 space_view3d_spacebar_menu.py
-a----        7/31/2014   4:41 PM           6658 system_blend_info.py
-a----        11/7/2014   3:00 PM           9124 system_property_chart.py
-a----        11/7/2014   3:00 PM          21598 ui_layer_manager.py
-a----        3/11/2015   6:01 PM          15868 ui_pie_menus_official.py
-a----        11/7/2014   3:00 PM          14970 uv_bake_texture_to_vcols.py
-a----        4/30/2015   4:33 PM          28561 uv_texture_atlas.py
`

**Comment by bsavery** [comment]
Sorry if I wasn't clear.. What's inside the prman_for_blender directory?  And where is that located?

**Comment by bsavery** [comment]
Bump.  Did you figure out your issues?

**Comment by bsavery** [comment]
No response...
