### ISSUE TITLE
Materials using slim/ptex

### ISSUE THREAD

**Issue by farnoy** [bsavery/PRMan-for-Blender#146]
Hi, I'm trying out RenderMan and this plugin for the first time with great results. I'm wondering if PTex is possible with blender? I also couldn't find any documentation on how to use this plugin with slim, is it possible?

**Comment by bsavery** [comment]
You want to use the PxrPTexture node to read Ptex files in your shading network.  The blender node editor takes the place of Slim, Slim does not support RIS mode anyway.

**Comment by farnoy** [comment]
Oh I see, they define custom nodes for layering & mixing - awesome. Thank you!
