### ISSUE TITLE
PxrLMLayer specular and clearcoat bump inputs are missing

### ISSUE THREAD

**Issue by BEARLIKEOTHERS** [bsavery/PRMan-for-Blender#147]
There is a field for the Specular Bump in the PxrLMLayer node, but it can't be connected to anything. Same problem with the ClearCoat Bump.
![schermata da 2015-10-07 13-49-53](https://cloud.githubusercontent.com/assets/2939295/10336657/a099a766-6cfa-11e5-883d-6673bb623627.png)
The python exporter still consider those fields, overriding the diffuse bump, making impossible to add a bump other than on diffuse.

**Comment by jdent02** [comment]
For some reason the node editor doesn't display all the parameters correctly compared to the material tab.  The material tab gives you access to the clear coat bump pattern input but the input for specular bump is missing there too.

**Comment by bsavery** [comment]
Hmmm...  it seems the sockets inside the advanced panels are not getting made.

**Comment by bsavery** [comment]
Fixed.
