### ISSUE TITLE
Depth Of Field

### ISSUE THREAD

**Issue by SnyderMark** [bsavery/PRMan-for-Blender#148]
I cannot seem to enable the DOF in my scene. Is there a procedure that I am  not following?

Thanks,
Mark

**Comment by jdent02** [comment]
It's there but it's subtle.  You are enabling the Depth of Field checkbox in the RenderMan Camera section of the camera tab, right?  You might have to lower the f-stop down pretty low to see it.

**Comment by SnyderMark** [comment]
jdent02, Got it! Lowered to 1 and see the effect.The default aperture of f/4 is low for most cameras. 
Thanks!

**Comment by jdent02** [comment]
Yeah, I usually have to go under 1 to see anything.  Personally I don't think RenderMan's F-Stop scale matches up at all to a real camera, but it works.

**Comment by bsavery** [comment]
I think it has something to do with the way we're translating focal
distances.  Might be a bug
Focal lengths, sorry


On Thu, Oct 8, 2015 at 5:57 PM, jdent02 <notifications@github.com> wrote:

> Yeah, I usually have to go under 1 to see anything. Personally I don't
> think RenderMan's F-Stop scale matches up at all to a real camera, but it
> works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/148#issuecomment-146728301>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
If I get some time I'll run a comparison of how cycles Fstops compare to RenderMan

**Comment by SnyderMark** [comment]
After running a full size render I've noticed the centre of interest is not
sharp. I'd like to move the focus to the middle of the subject. Is there
any way to define a spot to focus on other than just guessing or is the
"distance" (which doesn't seem to do anything) and re-rendering?

**Comment by jdent02** [comment]
There are two ways to set it: You can enter the name of an object in the 'focus' box, or you can manually set the distance using the numbered slider.  If you do this you should enable the 'limits' checkbox in the camera 'display' tab.  That will make the focal distance visible as a big yellow cross.

**Comment by jdent02** [comment]
Did some comparing and the F-Stop scaling seems to be pretty much identical between Cycles and PRMan so I don't think there's a bug here:

Cycles:
![cycles](https://cloud.githubusercontent.com/assets/13521172/10553683/7e92909a-7422-11e5-9974-ef688847c3c9.png)

PRMan:
![scene_0001](https://cloud.githubusercontent.com/assets/13521172/10553684/7e92d9e2-7422-11e5-9bf0-099854a30cdb.png)
