### ISSUE TITLE
Color Temperature cannot be set to -1

### ISSUE THREAD

**Issue by jpaav** [bsavery/PRMan-for-Blender#150]
I'm using Blender 2.74 and the latest PRMan for Blender (0.5.0). My problem is in the "Color Temperature" setting for the PxrAreaLight node. The tooltip provided says, "When -1, no color correction is applied" but when you attempt to set the value to -1 blender sets it to 0 leading me to believe this is a signing issue. I can attach a file if you need it.
Thanks for the time,
jpaav

![tooltip](https://cloud.githubusercontent.com/assets/11381848/10804594/42426fd0-7e03-11e5-9168-891e1925fc1b.png)
![prmancolortemprender](https://cloud.githubusercontent.com/assets/11381848/10804595/42432880-7e03-11e5-8835-1cb2e44f1d1e.PNG)

**Comment by bsavery** [comment]
Hmmm I'll look at the issue, but for the record, PxrStdAreaLight is the correct one to use in RIS, PxrAreaLight is there for backwards compatibility.

**Comment by bsavery** [comment]
fixed.

**Comment by jpaav** [comment]
Thanks
