### ISSUE TITLE
Image Darkened When Saved

### ISSUE THREAD

**Issue by SnyderMark** [bsavery/PRMan-for-Blender#151]
Hello,

After rendering an image and exporting the output file, it opens in Photoshop very dark.
I've tried Tiff and JPEG. Both seem to have the same behaviour.

**Comment by bsavery** [comment]
You're using 'it'?  Right click on the image -> Catalog -> Burn in mapping on save.

**Comment by bsavery** [comment]
Did that work?

On Thursday, October 29, 2015, SnyderMark <notifications@github.com> wrote:

> Hello,
>
> After rendering an image and exporting the output file, it opens in
> Photoshop very dark.
> I've tried Tiff and JPEG. Both seem to have the same behaviour.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/151>.
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by SnyderMark** [comment]
Yes, it worked Perfectly! Thanks you!
