### ISSUE TITLE
Render from simulation does not work.

### ISSUE THREAD

**Issue by mollenborg** [bsavery/PRMan-for-Blender#153]
The test was made with the simuator for fluid.
After the simulation baked, prman only render the first frame over and over.
If an other frame is selected in the timeline, only this frame will be rendered (only if the frame 1 already have been rendered)- and it is not possible to change frames in the timeline.

Link to forum thread: https://renderman.pixar.com/forum/showthread.php?s=&threadid=29631

Kind regards
Kristian

**Comment by bsavery** [comment]
Thanks!  I took a quick look yesterday but will get to it more today!


On Tue, Nov 24, 2015 at 1:50 AM, Kristian Mollenborg <
notifications@github.com> wrote:

> The test was made with the simuator for fluid.
> After the simulation baked, prman only render the first frame over and
> over.
> If an other frame is selected in the timeline, only this frame will be
> rendered (only if the frame 1 already have been rendered)- and it is not
> possible to change frames in the timeline.
>
> Link to forum thread:
> https://renderman.pixar.com/forum/showthread.php?s=&threadid=29631
>
> Kind regards
> Kristian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/153>.
>



-- 
brian.savery@gmail.com
508-274-8700
