### ISSUE TITLE
Scene_0001.exr Does Not Exist

### ISSUE THREAD

**Issue by grafxlab** [bsavery/PRMan-for-Blender#154]
While attempting to render using PRMan for Blender I receive an error that scene_0001.exr does not exist. I am using Windows 10 and Blender 2.76.  The installation folder for Pixar Renderman is C:\Program Files\Pixar\RenderManProServer-20.5 and Blender is installed at: D:\Program Files\Blender Foundation\Blender\2.76.

The error message is: <'Export path [D:\\Projects\\3D Files\\Test/images/Scene_0001.exr] does not exist.',>

The output path under PRMan Render Engine is set to: //{blend}

Does this have anything to do with the slashes '/images/Scene_0001.exr' being different from what Windows is expecting (i.e.: \\)?

Also can you explain the Preferences settings Use PRMan default paths and Use built in paths?

**Comment by bsavery** [comment]
So the short answer to your problem is that probably yes it has something to do with the backwards slashes.  

Most of those settings are vestigial to the old 3delight plugin which was supposed to be renderer agnostic, i.e you could provide a RMANTREE there, or if the renderer wasn't prman.exe you could provide that info there.  But those settings wouldn't effect the above error.

**Comment by grafxlab** [comment]
Is there a fix for the incorrect slashes in the output path?

**Comment by jdent02** [comment]
I've noticed this error also, but it doesn't seem to prevent the renderer from running, at least for me....

**Comment by MattAinscough** [comment]
I had a similar issue but for me it was a problem with the RenderMan installer not the addon.

I chose to install RenderMan to my E: drive but it only installed the RenderManNC-Installer to E: and actually installed RenderManProServer to C:\Program Files\Pixar instead. The licence file was installed under E: and RenderMan couldn't find it.

The solution for me was to copy the pixar.licence file from "E:\Program Files\Pixar\pixar.license" to "C:\Program Files\Pixar\pixar.license" and then everything worked.

**Comment by grafxlab** [comment]
Matt, copying the Pixar.license file as you described fixed the issue. Thanks for your suggestion.

**Comment by bsavery** [comment]
Hmmm.   And there was no error in the blender error bar about not being able to launch prman? Well that would explain it...

**Comment by jdent02** [comment]
I'm having this issue trying to run PRMan from the command line.  In this case the files it's claiming don't exist actually do, so I'm not sure what the deal is.

**Comment by MWY3510** [comment]
jdent02, what commands are you trying?

**Comment by jdent02** [comment]
In windows I opened the command line from the bin folder and typed "prman.exe +file name".

I went back into the file in Blender and reentered all the file paths and made sure 'relative path' was turned off.  That seemed to fix it.  So once again it might be the dreaded 'slash-backslash' issue.

**Comment by MWY3510** [comment]
That keeps cropping up everywhere. Thanks for the information jdent02. I'll look into this.

**Comment by yzaroui** [comment]
I reinstalled Renderman and selected to install Renderman for Maya (even if I don't have Maya). This solved the problem without any other tweakings

**Comment by vertexgamer** [comment]
hey, what version of renderman for maya have you installed? this doesn't work for me
