### ISSUE TITLE
UVs... 

### ISSUE THREAD

**Issue by bloodboy** [bsavery/PRMan-for-Blender#155]
hello fellow blendheads i am working on a simple leaf... i did the uvs the texture... a add the texture node with the manifold 2d, 3d with out, tried the pxrProjection layer... still cannot get my texture map to sit right in the render... but in the 3d view with textures on... it sits perfectly...  i played with scale, offset, every setting on the nodes was changed... form little to extrem and still....  i am sure i will work it out some how... just wanted to know if anyone had this problem...

**Comment by MWY3510** [comment]
bloodboy,

This is strange. Could you post a picture of your node set-up and result?

**Comment by bloodboy** [comment]
sorry for the delay...  time difference and all.. 
![renderman](https://cloud.githubusercontent.com/assets/16053679/11541434/8384077a-9932-11e5-8860-dd25ff60676c.png)

**Comment by bsavery** [comment]
It kinda looks like the scaling (s or t) is off.  Try setting one of those
in the pxrManifold2d to 2.

On Wed, Dec 2, 2015 at 11:23 AM, bloodboy <notifications@github.com> wrote:

> sorry for the delay... time difference and all..
> [image: renderman]
> <https://cloud.githubusercontent.com/assets/16053679/11541434/8384077a-9932-11e5-8860-dd25ff60676c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/155#issuecomment-161405025>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by bloodboy** [comment]
on another topic... you are the dude thats doing all this good work with renderman.... thank you for your work... i found the docs for renderman and blender on git hub... and i edited the part on sampling little... hope that was ok... i am no coder, but i would like to help... with test scenes or the docs. i dont know but if there is anything i can do... i am happy to help....

**Comment by bsavery** [comment]
Docs are great help!  Thanks

On Wed, Dec 2, 2015 at 11:38 AM, bloodboy <notifications@github.com> wrote:

> on another topic... you are the dude thats doing all this good work with
> renderman.... thank you for your work... i found the docs for renderman and
> blender on git hub... and i edited the part on sampling little... hope that
> was ok... i am no coder, but i would like to help... with test scenes or
> the docs. i dont know but if there is anything i can do... i am happy to
> help....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/155#issuecomment-161409950>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by bloodboy** [comment]
playing with the scale and offset does show changes... it moves the texture around on the leaf... but its hard to get it right... still have not done it... 
my scene file i...  https://renderman.pixar.com/forum/showthread.php?s=&threadid=29717

**Comment by MWY3510** [comment]
Ok, I played with your scene for a bit and got some good results with a bit of math. To get this result simply line up the leaf how you want it then take the decimal equivalent of the aspect ratio of the image and scale the UV map by that in the axis that is smaller. For example a 16:9 image ratio would be scaled by 0.5625 in the y-axis to produce the correct result.
![pearleaf](https://cloud.githubusercontent.com/assets/9410101/11548129/46b84532-9927-11e5-911e-db5b2e06e2bf.jpg)

**Comment by bsavery** [comment]
Can you run txinfo on the resulting tex file and what's the resolution on
the original image?


On Wed, Dec 2, 2015 at 4:22 PM, MWY3510 <notifications@github.com> wrote:

> Ok, I played with your scene for a bit and got some good results with a
> bit of math. To get this result simply line up the leaf how you want it
> then take the decimal equivalent of the aspect ratio of the image and scale
> the UV map by that in the axis that is smaller. For example a 16:9 image
> ratio would be scaled by 0.5625 in the y-axis to produce the correct result.
> [image: pearleaf]
> <https://cloud.githubusercontent.com/assets/9410101/11548129/46b84532-9927-11e5-911e-db5b2e06e2bf.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/155#issuecomment-161474925>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
Brian if your talking about the image he was using, I did not use it. If you mean in general then yes we can get the resolution from that.

**Comment by MWY3510** [comment]
Brian,

A correction to my previous statement. Txinfo does not give you the resolution of the original image. I think that it could be done either through information from txmake or by having a python function read the resolution. Either way this information could then be used to adjust the UV for non-square images.

**Comment by bloodboy** [comment]
MWY3510
                       thanks for your help.... i have somewhat of an understanding of what you did... 
but can you show me the math... behind what you did to get the answer...  
   somewhere in the middle here get me... 
" To get this result simply line up the leaf how you want it then take the decimal equivalent of the aspect ratio of the image and scale the UV map by that in the axis that is smaller."

"line up the leaf how you want" = is that the texture on the the leaf.. 


For example a 16:9 image ratio would be scaled by "0.5625" in the y-axis to produce the correct result.  how did you get 0.5628  
                  x ? y = 0.5628.... 
sorry for the complex requiremants for a simple answer....  just would like to know how to solve this problem in the future.... 
lastly.... 
 and is it simpler to use square textures..  thamks a million..

**Comment by MWY3510** [comment]
bloodboy,

Because of how the plug-in converts textures it is in fact easier (at the moment) to use square textures.

To answer the question though. First, "line up the leaf how you want" this does simply mean line the texture up how you want it to look in the UV editor. It should look just right in textured view. Second, the math portion. You should find the aspect ratio of the image you are working with. In my case I used an image that measured 1862 (x) by 915 (y). By simplifying you get the ratio 16/9. In the UV image editor (or in the manifold node it doesn't matter) you should scale the smaller side by that ratio. In my example you would scale the UV on the y axis by 0.5628. This will through your texture off in the viewer but it will look correct in renderman.

I know this is not the best solution and optimally we should convert the UV map as it is processed.

Hope this helps,
MWY3510

**Comment by MWY3510** [comment]
OK, sorry about that I fixed my previous post.

**Comment by bloodboy** [comment]
MWY3510.. Yeah that will help.. Now I know and understand the work flow.. It's all good....thanks a million and one..

**Comment by bloodboy** [comment]
thanks again... i got it working but i think that i have to re-think how i do UVs and textures.. makes it simpler...

**Comment by MWY3510** [comment]
bloodboy,

No problem. Just a note, we might change this behaver down the road to be
more in line with how Blender visualizes the texture.

MWY3510

**Comment by bloodboy** [comment]
that is not something i will be sad about when its changes... haha...  but until then i understand the work flow somewhat...

**Comment by bloodboy** [comment]
this is it so far... working on my textures... but i think it's looking ok...
![test_01](https://cloud.githubusercontent.com/assets/16053679/11578144/14c097d0-9a23-11e5-8f50-203bfd709316.png)

**Comment by bloodboy** [comment]
this is it so far... working on my textures... but i think it's looking ok
![test_01](https://cloud.githubusercontent.com/assets/16053679/11578437/d671e7f6-9a25-11e5-8aec-77782da9be8d.png)

**Comment by MWY3510** [comment]
This issue is closed because a fix has been pushed.
