### ISSUE TITLE
Feature suggestion: additonal DoF controls

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#161]
The Cycles engine camera has options for DoF bokeh shape, rotation, and aspect ratio.  So far PRMan for Blender isn't exposing the RenderMan equivalents to these and in my opinion it kind of gimps the plugin by comparison.  Could the 'nsides', 'angle', 'roundness', 'density' and 'dofaspect' controls be exposed for the camera tab (hidden behind an 'advanced' tab if desired)?

**Comment by bsavery** [comment]
Haha Gimps?  Well that's an easy one to do anyway.

**Comment by jdent02** [comment]
Yeah, might have been a bit clickbait'ish but it did get your attention, didn't it :)

**Comment by bsavery** [comment]
Merry Christmas.  Fixed.

**Comment by jdent02** [comment]
Thanks Santa
