### ISSUE TITLE
Feature request:  Open last rib file button

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#162]
Mainly for debugging.

**Comment by MWY3510** [comment]
So then we would need to save a copy of the previous rib right?

**Comment by bsavery** [comment]
No I mean a button that just "opens the last rib we created".  Could save just the filename of the last rib, or figure out what the rib file name is on the fly, open it in a text editor.

**Comment by MWY3510** [comment]
Ok, That make more sense.

**Comment by MWY3510** [comment]
Button made. You can also use your favorite text editor if you want.

**Comment by bsavery** [comment]
Hooray!

On Tuesday, December 22, 2015, MWY3510 <notifications@github.com> wrote:

> Button made. You can also use your favorite text editor if you want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/162#issuecomment-166792343>
> .
>


-- 
brian.savery@gmail.com
508-274-8700
