### ISSUE TITLE
Blender lockup and endless IPR refreshing

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#163]
Ran into a possible bug.  Started up an IPR session and tried to change a material from LMDiffuse to PxrDisney while it was running.  Blender locked up and the 'it' window started a loop where every 2nd pass it would perform a full refresh, and it never stopped.  Even after three minutes it was still going.  This happened when I tried switching to regular PxrDiffuse as well so it' not isolated to the Disney BXDF.  File size is 50MB so it's not too realistic to post it here.

using the latest PRMan for Blender download, RenderMan 20.6 and Blender 2.76b.

**Comment by bsavery** [comment]
Ok we'll see if we can reproduce in a simple scene.

**Comment by MWY3510** [comment]
This is not reproducible on my end with a simple scene (or even with a 200MB scene.) I did get Blender to freeze until IT finished rendering but after that the material did change. jdent02 could you provide some more information on the object that you used (what properties type etc.)?

**Comment by bsavery** [comment]
Also if you could give a basic setup... like if there's parented objects, or materials shared or multi -material objects....

**Comment by jdent02** [comment]
It's the ISS mesh from BlendSwap.  It is comprised of numerous modules that are parented together and by default they all use the same material datablock.  Also there are several objects that use the same mesh datablock (the main solar foils being a prime example).  Now that I dig into it more, the hierarchy of this file is more complex than a typical .blend so maybe I will post it, as it seems to be generating some unique behavior from the plugin.

**Comment by jdent02** [comment]
[ISS_Mesh_Only.zip](https://github.com/bsavery/PRMan-for-Blender/files/70264/ISS_Mesh_Only.zip)

Here you go.  Forgot I could ZIP it.  I just tried it again and it still generates the error.

**Comment by MWY3510** [comment]
I've tracked down where the IT multi-refresh is coming from. Turns out the fact that most of the station geometry is multi-user is causing the re-render to try and update the scene over and over. This behavior can be replicated by Alt-D (link copying) copying a cube about five times.

**Comment by MWY3510** [comment]
Actually after letting this effect propagate for about 40 times (or so) the entire space station is updated. Not the idea behavior I know, but Blender does eventually become unfrozen after refreshing for each link of data.

**Comment by jdent02** [comment]
So it might be something that we're stuck with?

**Comment by MWY3510** [comment]
Not necessarily. I need to look into some things. This might not get fixed until after Christmas depending on how much trouble it is to correct.

**Comment by bsavery** [comment]
With prman, There are two basic edits to materials.

One where you edit the material network (which is what you do when you change from Disney to Diffuse) and the network must be rebound to all gprims that it is attached to.  So you're not really endlessly looping just a bunch of edits

Another where you just change a parameter.  That can happen globally once.  

Anyway I think the issue is that we could batch the rebind edits all to one and then flush the edits.

**Comment by bsavery** [comment]
Going to call this closed for now.
