### ISSUE TITLE
start plugin from a uninstalled blender (ie, only unzipped to filefolder) on windows

### ISSUE THREAD

**Issue by tobbew79** [bsavery/PRMan-for-Blender#165]
Fails to load DLL:
import prman_for_python_3 as prman_for_python
(prman.py, line 77). 

It works when I installed using a blender installer instead. I tried setting path to include %RMANTREE%bin\ and pythonpath to include both the bin and lib folder, but that did not help. Simply installing blender using the installer however, and it works immediately. It does still not work from the buildbot (nightly builds). I'm unsure of the reason. Could it have to do with os protection of program files folders? Or does the blender installer setup path variables of importance? Where? In settings the path and pythonpath at least are unchanged.

(The path and pythonpath does look correct and include the correct folders, and I can run the prman.exe from the commandline without being in the folder.)

Running windows 10, downloaded prman (20.6) and prman for blender today (latest).

Best wishes,
Torbjörn

**Comment by bsavery** [comment]
Hey Torbjorn!  Happy new year.  
Usually you don't have to set the pythonpath and other env variables unless you're installing PRMan to a non-standard location (not C:\Program Files).  That said.  If you ARE installing PRMan to a non-standard location, you should just need to set RMANTREE to where you install it, and everything else should be taken care of.

**Comment by MWY3510** [comment]
Brian,
I think that the problem is on the Blender side of things. I just tested an experimental version of Blender and it has problems that a normal release does not. I don't see this as a problem that we could correct.

**Comment by bsavery** [comment]
Ohhhh.... possibly the newest version is built on python 3.5?

On Sat, Jan 2, 2016 at 6:05 PM, MWY3510 <notifications@github.com> wrote:

> Brian,
> I think that the problem is on the Blender side of things. I just tested
> an experimental version of Blender and it has problems that a normal
> release does not. I don't see this as a problem that we could correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/165#issuecomment-168449952>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by tobbew79** [comment]
Now that's a quick response! However, you misunderstand me. I did make sure to set those variables only because I got that error and did not understand why I did not get it to work. It really seemed like a path error to me. I installed PRMAN to default location. But I usually use buildbot builds of blender (builder.blender.org, ie unstable nightly builds) and have several builds installed at the same time. Usually you do not need to install blender, it is enough to just unzip it. Interestingly I was unable to install the addon (copying it to the addon folder or selecting the zip and installing from file makes it appear in the addon list, but when I try to click to activate it I get the error that it does not find a dll and points to line 77 as written above. I have been able to install other addons. I do not know why this does not work. I do not have any concurrent experience of windows application development, and I do not know if the os protects the program file folder or if I would have needed to run blender as an administrator if run from a different location. However, the official install works. I do not know what's different in their environments.

**Comment by tobbew79** [comment]
Yes, the newest builds have python 3.5 Is that a problem?

**Comment by tobbew79** [comment]
The official build has 3.4.2.

**Comment by bsavery** [comment]
So the addon is all just python code and version agnostic.  However it
loads a dll from RMANTREE that is compiled to python 3.4.  I thought python
plugins compiled to 3.4 should be forward compatable... but it's possible
they're not

On Sat, Jan 2, 2016 at 6:11 PM, tobbew79 <notifications@github.com> wrote:

> The official build has 3.4.2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/165#issuecomment-168450100>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by tobbew79** [comment]
My experience in python is just for scripting purposes, so I would not know. It took me a couple of hours before I tried installing an older official build using an installer. 

I tested installing the addon in a blender 2.75 (python 3.4.2) which is not installed using an installer, and it works fine there. It could be the python version then. It that'd be confimed, perhaps the rendermanproserver-20.6/bin/prman.py should have more controls for it's supported python versions before line 77 and give a more informative message. If this would not be changed there perhaps the __init__.py of the blender addon could check to give a message, or at lest this could perhaps be written somewhere close to the download link and in the documentation somewhere. I'm currently downloading the official build in zip form to see if it works there.

**Comment by bsavery** [comment]
Fair enough.  I had it on my list to test the dll with python 3.5...

On Sat, Jan 2, 2016 at 6:43 PM, tobbew79 <notifications@github.com> wrote:

> My experience in python is just for scripting purposes, so I would not
> know. It took me a couple of hours before I tried installing an older
> official build using an installer.
>
> I tested installing the addon in a blender 2.75 (python 3.4.2) which is
> not installed using an installer, and it works fine there. It could be the
> python version then. It that'd be confimed, perhaps the
> rendermanproserver-20.6/bin/prman.py should have more controls for it's
> supported python versions before line 77 and give a more informative
> message. If this would not be changed there perhaps the *init*.py of the
> blender addon could check to give a message, or at lest this could perhaps
> be written somewhere close to the download link and in the documentation
> somewhere. I'm currently downloading the official build in zip form to see
> if it works there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/165#issuecomment-168450852>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by tobbew79** [comment]
Confirms it works with 2.76b just unzipped without installation, so it might very well be the python version then.

**Comment by bsavery** [comment]
Just to be clear, I've confirmed that the prman python dll loads in python 3.5

**Comment by tobbew79** [comment]
That's really comforting to know. Thank you for sharing that information. Then it should not be a problem to solve this in the future, and it should not have to involve you.
