### ISSUE TITLE
Question: How do I get hair to render? Bug: Hair system without any materials at all in scene.

### ISSUE THREAD

**Issue by tobbew79** [bsavery/PRMan-for-Blender#167]
I have tried repeatedly creating a camera, a light and a plane with hair. I cannot see the hair in the render. I have seen renders others have done with hair, I do not understand why it's not working for me. I see no errors in the console.

If I instead try to just create a camera, a plane and add a particle system, switch to hair and press render I get error messages (no materials, no lights created) in a bug wise manner. If I after that press esc to close the render view, select the plane and add a material blender crashes. I have repeated the procedure, and it's reproduced.

**Comment by tobbew79** [comment]
Very weird. I found the example files, and the simple hair system there works fine to render on my computer as well. In spite of this I still get the same error when I try with a new scene. I'll try to delete my preferences and restart to see that it's not something in my default scene which causes issues.

**Comment by bsavery** [comment]
Can you attach the scene?

On Sat, Jan 2, 2016 at 6:00 PM, tobbew79 <notifications@github.com> wrote:

> Very weird. I found the example files, and the simple hair system there
> works fine to render on my computer as well. In spite of this I still get
> the same error when I try with a new scene. I'll try to delete my
> preferences and restart to see that it's not something in my default scene
> which causes issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/167#issuecomment-168449820>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by tobbew79** [comment]
Hopefully. My render gives a cube but no hair. (I'm not using a hair material, but I've tried that before too.)
[renderman_hair_test.zip](https://github.com/bsavery/PRMan-for-Blender/files/76468/renderman_hair_test.zip)

**Comment by MWY3510** [comment]
Ok, I remember this bug. Currently the hair export is only tracking Hair children not the parent strands. It was something that was overlooked by me in an early version. All of my test scenes had child particles. Ops... I think this ones on me.

**Comment by MWY3510** [comment]
Sorry I take that back the plugin should be working correctly but only child strands are being read in. ????

**Comment by tobbew79** [comment]
You are right in that adding children will give rendered hair.

**Comment by MWY3510** [comment]
I'll be doing some debugging on this, but Blenders strand system has been notoriously difficult.

**Comment by MWY3510** [comment]
Ok, now this might sound stupid but someone thought it was a great idea to prevent regular hairs from being exported unless the "Guide Hairs" button is checked (probably my fault somehow ;-) ). This problem has now been addressed. Until the next wave of updates arrives all you need to do is check the Guide Hairs button under the display tap

**Comment by bsavery** [comment]
I think that was me.

**Comment by tobbew79** [comment]
Thank you very much for the workaround!
