### ISSUE TITLE
High resolution smoke not supported?

### ISSUE THREAD

**Issue by tobbew79** [bsavery/PRMan-for-Blender#168]
Testing the fire_monkey_matte from the testfiles from siggraph (?), changing high resolution to on, 1 division. Render. 

line 1330 in export_smoke: TypeError: problem parsing parameterlist entry: varying float density.

**Comment by MarcoCheng** [comment]
when I just render High resolution smoke in renderman. My computer blue screen hhahah. anyway how to use openVDB in blender renderman？

**Comment by bsavery** [comment]
Hi res smoke is not supported.  It seems with cycles this simply takes the same resolution sim and renders it with a higher res voxels but the same data (perhaps with noise to make it less blocky).  Anyway I'm not sure it would make a huge difference with the way renderman works with volumes.  

Does Blender support exporting openvdb yet?  It will be simple to use them if it does.

**Comment by jdent02** [comment]
Nope.  Openvdb is planned to be used only for internal caching operations at first.  Export is supposed to be available *someday*.

**Comment by MWY3510** [comment]
It is getting some attention though. See here https://developer.blender.org/D1308 and here http://wiki.blender.org/index.php/User:Kevindietrich/OpenVDBSmokeExport

**Comment by MWY3510** [comment]
Since this is on the Blender team to finish I think closing this and leaving the issue on the TODO eventually list would be appropriate.

**Comment by bsavery** [comment]
I'm not sure what that means by internal caching. If there's a catch file
somewhere we can use it

On Sunday, January 3, 2016, jdent02 <notifications@github.com> wrote:

> Nope. Openvdb is planned to be used only for internal caching operations
> at first. Export is supposed to be available *someday*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/168#issuecomment-168505395>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by pleprince** [comment]
Blender is using these techniques to add more detail to a low res sim : https://graphics.ethz.ch/research/physics_animation_fabrication/simulation/turb.php
This is quite standard in VFX...

--
Philippe

**Comment by bsavery** [comment]
Philippe so they say the data of the density and color,temperature grid.
Are you saying for the high resolution rendering they use that data then
apply some turbulence function on it?

On Sunday, January 3, 2016, pleprince <notifications@github.com> wrote:

> Blender is using these techniques to add more detail to a low res sim :
> https://graphics.ethz.ch/research/physics_animation_fabrication/simulation/turb.php
> This is quite standard in VFX...
>
> --
> Philippe
>
> > On 3 Jan 2016, at 15:46, bsavery <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > I'm not sure what that means by internal caching. If there's a catch file
> > somewhere we can use it
> >
> > On Sunday, January 3, 2016, jdent02 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Nope. Openvdb is planned to be used only for internal caching
> operations
> > > at first. Export is supposed to be available *someday*.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/bsavery/PRMan-for-Blender/issues/168#issuecomment-168505395
> >
> > > .
> > >
> >
> >
> > --
> > brian.savery@gmail.com
> <javascript:_e(%7B%7D,'cvml','brian.savery@gmail.com');>
> > 508-274-8700
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/168#issuecomment-168508217>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by pleprince** [comment]
Exactly.

--
Philippe

**Comment by bsavery** [comment]
K. That's what's I suspected. Will take a look at applying it

On Sunday, January 3, 2016, pleprince <notifications@github.com> wrote:

> Exactly.
>
> --
> Philippe
>
> > On 3 Jan 2016, at 15:58, bsavery <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Philippe so they say the data of the density and color,temperature grid.
> > Are you saying for the high resolution rendering they use that data then
> > apply some turbulence function on it?
> >
> > On Sunday, January 3, 2016, pleprince <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Blender is using these techniques to add more detail to a low res sim :
> > >
> https://graphics.ethz.ch/research/physics_animation_fabrication/simulation/turb.php
> > > This is quite standard in VFX...
> > >
> > > --
> > > Philippe
> > >
> > > > On 3 Jan 2016, at 15:46, bsavery <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > I'm not sure what that means by internal caching. If there's a catch
> file
> > > > somewhere we can use it
> > > >
> > > > On Sunday, January 3, 2016, jdent02 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > > Nope. Openvdb is planned to be used only for internal caching
> > > operations
> > > > > at first. Export is supposed to be available *someday*.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/bsavery/PRMan-for-Blender/issues/168#issuecomment-168505395
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > > --
> > > > brian.savery@gmail.com
> <javascript:_e(%7B%7D,'cvml','brian.savery@gmail.com');>
> > > <javascript:_e(%7B%7D,'cvml','brian.savery@gmail.com
> <javascript:_e(%7B%7D,'cvml','brian.savery@gmail.com');>');>
> > > > 508-274-8700
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/bsavery/PRMan-for-Blender/issues/168#issuecomment-168508217
> >
> > > .
> > >
> >
> >
> > --
> > brian.savery@gmail.com
> <javascript:_e(%7B%7D,'cvml','brian.savery@gmail.com');>
> > 508-274-8700
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/168#issuecomment-168510497>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
Fixed with .9
