### ISSUE TITLE
Possible to use blender “Group Object" hair particle feature in Renderman？

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#169]
Is it possible to use blender “Group Object" as hair particle in blender RenderMan? Seems renderman has a individual hair particle system...

**Comment by bsavery** [comment]
I believe this works correctly.  The blender cosmos laundromat bechmark scene uses this for the grass.

**Comment by MarcoCheng** [comment]
It seems need to convert particle to object before i use renderman ( Group Object Render pannel disappear when i switch to renderman

**Comment by bsavery** [comment]
Yes, That should be simple to have the group object render panel stick around.
