### ISSUE TITLE
Path problem on Windows 8.1

### ISSUE THREAD

**Issue by handsomedave** [bsavery/PRMan-for-Blender#17]
Blender 2.75a
Try to render a simple scene and get the following in the console:

ERROR: ('Export path [E:\\\RenderManTest\\\Scene_0001.exr] does not exist.',)
Error: PRMan: Exited

It looks to me like whatever is building the paths is adding extra backslashes.

**Comment by bsavery** [comment]
Can you give me some more info?  What are you setting the output directory to?  E:\RenderManTest\?

**Comment by handsomedave** [comment]
In Renderman Output property dialog
RIB Output:  E:\RenderManTest\{scene}.rib
Display Image: E:\RenderManTest\{scene}_####.{file_type}

In settings under Add-ons OUT(Output Root)    E:\RenderManTest\

RIB is created when I try to render.
In the error message all backslashes are double ex. E:\\RenderManTest\\Scen.......

If I change output property dialog settings to:
RIB Output:  $OUT\{scene}.rib
Display Image: $OUT\{scene}_####.{file_type}

I still get the same error.

**Comment by bsavery** [comment]
Sorry Are you on windows, linux etc?  I'm guessing Windows from the above but what version?  I ask because other's on windows don't seem to have that problem.  Maybe a permissions issue?

**Comment by handsomedave** [comment]
Sorry put Windows 8.1 in the title, should have also included in post. Tried running blender as administrator and it made no difference. I don't have anything running other than basic antivirus and have tried disabling it. Which python file does file writing take place? My pythons far from great but I could try and hunt it down myself.

The RIB file is written successfully in the same folder that image output should be written to.

**Comment by bsavery** [comment]
Oh ok.  Hmmm.  So you get a E:\\RendermanTest\\whatever.rib file?  What is in the rib file if you open it in a text editor for the "Display" line?  Maybe if you can attach your scene somehow that might help.

**Comment by handsomedave** [comment]
Below is the contents of the RIB file. I noticed that if I create Test.exr before rendering that the file is deleted when it fails. My scene file is just the default cube with PRMan selected for renderer and the file locations for the RIB and EXR changed.

##RenderMan RIB
#Generated by PRMan for Blender, v0.1.1 
#From File: testblend.blend on Monday 07/13/15 16:49:55
version 3.04
Option "searchpath" "string shader" ["@://C/Program Files/Pixar/RenderManProServer-20.0/lib/RIS/pattern://C/Program Files/Pixar/RenderManProServer-20.0/lib/RIS/bxdf://C/Program Files/Pixar/RenderManProServer-20.0/lib/rsl/shaders://C/Users/dave/AppData/Roaming/Blender Foundation/Blender/2.75/scripts/addons/PRMan-for-Blender-master/shaders"]
Option "searchpath" "string texture" ["//E/RenderManTest//textures"]
Option "bucket" "string order" ["horizontal"]
Display "E:/RenderManTest/Test.exr" "openexr" "rgba" "quantize" [0 0 0 0]
Display "+E:/RenderManTest/Test.z.exr" "openexr" "z" "quantize" [0 0 0 0]
PixelVariance 0.005
Hider "raytrace" "string integrationmode" ["path"] "int maxsamples" [512] "int minsamples" [32] "int incremental" [1]
Integrator "PxrPathTracer" "integrator" 
FrameBegin 1
	Clipping 0.1 100
	Projection "perspective" "fov" [28.8415]
	ScreenWindow -1.77778 1.77778 -1 1
	Transform [ 0.68588 -0.31737 -0.654862 0  0.727634 0.312469 0.610666 0  -0.0108168 0.895343 -0.445245 0  -0.338182 -0.376693 11.2523 1 ]
	Format 960 540 1
	PixelFilter "sinc" 2 2
	ShadingRate 1
	Attribute "trace" "int displacements" [1] "int maxspeculardepth" [2] "int maxdiffusedepth" [2]
	WorldBegin 
		### LIGHTS
		AttributeBegin 
			TransformBegin 
				Transform [ -0.290865 0.955171 -0.0551891 0  -0.771101 -0.199883 0.604525 0  0.566393 0.218391 0.794672 0  4.07625 1.00545 5.90386 1 ]
				ShadingRate 100
				AreaLightSource "PxrAreaLight" "Lamp" "string shape" ["sphere"] "float exposure" [1] "color lightcolor" [1 1 1]
				Sphere 0.1 -0.1 0.1 360 
			TransformEnd 
		AttributeEnd 
		Illuminate "Lamp" 1
		Bxdf "PxrDisney" "default" "color baseColor" [0.18 0.18 0.18]
		### INLINE ARCHIVES
		ArchiveBegin "Cube" 
			#surface
			Bxdf "PxrDisney" "Material" "color baseColor" [0.8 0.8 0.8] "float specular" [0.5]
			#displacement
			#interior
			PointsPolygons [4 4 4 4 4 4] [0 1 2 3 4 7 6 5 0 4 5 1 1 5 6 2 2 6 7 3 4 0 3 7] "P" [1 1 -1 1 -1 -1 -1 -1 -1 -1 1 -1 1 0.999999 1 0.999999 -1 1 -1 -1 1 -1 1 1]
		ArchiveEnd 
		### OBJECTS
		AttributeBegin 
			Attribute "identifier" "name" ["Cube"]
			TransformBegin 
				Transform [ 1 0 0 0  0 1 0 0  0 0 1 0  0 0 0 1 ]
				#surface
				Bxdf "PxrDisney" "Material" "color baseColor" [0.8 0.8 0.8] "float specular" [0.5]
				#displacement
				#interior
				ReadArchive "Cube" 
			TransformEnd 
		AttributeEnd 
		### INSTANCE MASTERS
		### INSTANCES
		### MULTI-MATERIAL OBJECTS
	WorldEnd 
FrameEnd

**Comment by handsomedave** [comment]
Figured out what the issue was. If RenderMan is installed to a non-default location PRMan-for-Blender does not work correctly.

Reinstalled RenderMan to default location and corrected issue.

**Comment by bsavery** [comment]
Interesting.  I think that should work, you just have to set up the environment variables manually.

**Comment by JerryCao1985** [comment]
I am encountering the same issue even if renderman is installed at default location which is:
C:\Program Files\Pixar\RenderManProServer-20.1\

**Comment by MWY3510** [comment]
JerryCao1985,

Can you show me what your RMANTREE environment variable looks like?

**Comment by JerryCao1985** [comment]
Sorry for the delay.
Following is my detailed setup in blender:

RMANTREE Path: C:\Program Files\Pixar\RenderManProServer-20.1\
Render Path: prman
ShaderCompiler Path: shader
Shader Info Path: sloinfo
Texture Optimiser Path: txmake
OUT(Output Root):  D:\prman_for_blender\{blende}   # I changed it to drive d so that I can avoid permission issue
SHD (Shadow Maps):  $OUT/shadowmaps
PTC (Point Clouds):  $OUT/pointclouds
ARC (Archives): $OUT/archives

I've also tried the 'Use PRMan default paths', no luck on this option too.

I would be really appreciated for any tip that helps.

**Comment by bsavery** [comment]
So the problem here I think is that your rendering on a different drive
than where the add on and prman are. When creating the rib file we try to
construct the relative path from where you are rendering to the add on and
Prman. And windows of course because drive letters doesn't know how to do
this.

As a work around I bet if you doing everything in c: it would work fine.



On Sunday, December 13, 2015, Jiayin Cao (Jerry) <notifications@github.com>
wrote:

> Sorry for the delay.
> Following is my detailed setup in blender:
>
> RMANTREE Path: C:\Program Files\Pixar\RenderManProServer-20.1\
> Render Path: prman
> ShaderCompiler Path: shader
> Shader Info Path: sloinfo
> Texture Optimiser Path: txmake
> OUT(Output Root): D:\prman_for_blender{blende} # I changed it to drive d
> so that I can avoid permission issue
> SHD (Shadow Maps): $OUT/shadowmaps
> PTC (Point Clouds): $OUT/pointclouds
> ARC (Archives): $OUT/archives
>
> I've also tried the 'Use PRMan default paths', no luck on this option too.
>
> I would be really appreciated for any tip that helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/17#issuecomment-164255954>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by JerryCao1985** [comment]
I'm afraid that it doesn't...
Actually I tried to export those intermediate files to drive C first, I changed it to drive D in case there is a permission issue.
However I do can see some files generated, such as c:\prman_for_blender\untitled\Scene.rib and folders called 'archives', 'images', 'textures'.

Here is the error log output by PRMan:

ERROR:  ('Export path [c:\\prman_for_blender\\untitled/images/Scene_0000.exr] does not exist.',)
Info: Texture generation took 00:00:00
Info: RIB generation took 00:00:00
Error: PRMan: Exited

And the Scene_0000.exr image is not there as it complains.

**Comment by bsavery** [comment]
Ok I'm not sure why the revers slashes don't work for you because they seem
ok for everyone else on Windows. Should be an easy fix though

On Sunday, December 13, 2015, Jiayin Cao (Jerry) <notifications@github.com>
wrote:

> I'm afraid that it doesn't...
> Actually I tried to export those intermediate files to drive C first, I
> changed it to drive D in case there is a permission issue.
> However I do can see some files generated, such as
> c:\prman_for_blender\untitled\Scene.rib and folders called 'archives',
> 'images', 'textures'.
>
> Here is the error log output by PRMan:
>
> ERROR: ('Export path [c:\prman_for_blender\untitled/images/Scene_0000.exr]
> does not exist.',)
> Info: Texture generation took 00:00:00
> Info: RIB generation took 00:00:00
> Error: PRMan: Exited
>
> And the Scene_0000.exr image is not there as it complains.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/17#issuecomment-164267496>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
Brian,

Are you already working on this issue, or would you like me to put it on my list for tonight?

MWY3510

**Comment by MWY3510** [comment]
I think I have most of the reverse slash issues tracked down.
