### ISSUE TITLE
Suggestion for improvement: deformation motion blur

### ISSUE THREAD

**Issue by tobbew79** [bsavery/PRMan-for-Blender#170]
Currently it seems it does not support deformation motion blur. I have tried only using a shapekey animation and using simple deform modifiers. I have not tried any character animation yet.

Test scene using a shapekey key animation and with a simple transform for reference:
[renderman_no_deformation_motion_blur.zip](https://github.com/bsavery/PRMan-for-Blender/files/76714/renderman_no_deformation_motion_blur.zip)

**Comment by jdent02** [comment]
Shapekeys currently don't work with deformation blur.  A workaround I found was to add in an armature modifier.  You don't need to link it to anything (and it won't affect your animation) but that will trigger the exporter to create the right files for def blur.

**Comment by tobbew79** [comment]
Great. Thank you for the workaround, I misstook it for deformation motion blur not to have been implemented at all. Interesting though that if you uncheck the armature from preview and rendering it still gives motion blur on the shape keys, however deleting the armature removes the deformation motion blur. I'll add a short comment about it in the wiki for other newcomers.

**Comment by jdent02** [comment]
From the code snippets I saw (and understood, which wasn't much), the exporter looks for particular modifiers on an object in order to decide if it needs to export the extra meshes to make deformation blur work.  As of now it doesn't appear to pay any attention to shape keys, but the armature modifier is on the list so it fools the exporter when you put it in there.

**Comment by bsavery** [comment]
I think I have this fixed.  Any object with shape keys now should be marked as deforming when exporting.

Please test with your scene after updating from github

**Comment by tobbew79** [comment]
It works. However, shape keys have lot's of uses except animation and I think it would make sense to only set object as deforming if the shape keys have keyframes (possibly also if the current frame is within or in close proximity to them).

Having taken a look at the code something to consider would be 
1) which modifiers are possibly deforming, but only if they have keyframes placed on them (most)
2) which modifiers can be deforming without having keyframes (ie simulations), for them check if we are within simulation time (possibly with a small margin to allow the end of motion blur).

**Comment by tobbew79** [comment]
(On updating to latest in branch there a lot's of problems regarding particles and motion blur, but perhaps that's something you are currently working on - tuplet errors, probably parameter types that are wrong.)

You might have to rewind the file (shift+left arrow) and start playing it so you have a history cache (alt+a twice to start and stop), then F12 to render.

Test scene:
[renderman_particle_test2.zip](https://github.com/bsavery/PRMan-for-Blender/files/79919/renderman_particle_test2.zip)

**Comment by bsavery** [comment]
Thanks for all the good feedback.  Really good testing.

1.  Considered being "smarter" about looking at modifiers when exporting as you described... took the easy route.  An object set as deforming basically means it's exporting rib per frame, so it might be ok to take the "stupid" route here.

2.  I'll fix that particle problem.

**Comment by bsavery** [comment]
Particles fixed.

**Comment by tobbew79** [comment]
I have a past as a C++/java programmer (professionally, then, but working in an entirely different field now). I have used python for scripting before. I'm new to the renderman renderer. 

If it makes a difference and is low priority (more than weeks away, because that might be what it takes for me to find the spare time to do it) I could try to look into improving that as a contribution to the project.

Personally I'm not currently that worried about the time for the export (if I would become in the future I could do it then). What I'm unaware of is whether there's a cost in the current implementation on the ris renderer side that's affected by if objects are exported as deforming or not. If that overhead is small (it seems to me it's fast with motionblur, but testing deformation motion blur with a heavier character with motionblur and displacement is still on my to do list) it might not be worth the time and then perhaps it would be better if I did something else.

**Comment by bsavery** [comment]
So let me give a little background on what's going on.  This part of the
exporter has been rewritten a few times, as translating the blender to
renderman scene is tough to get right in all the edge cases.

1.  We go to export the frame at frame X.  Under the archives directory
you'll see there is a "static" and 0000, 0001, 0002 directory etc.
Geometry that is deforming (emphasis on deforming not translating/rotating)
goes in the frame numbered directories while everything else goes in the
static directory.  Note that this is irrespective of motion blur.  In
general we are exporting just the geometry to the archives, not the object
transforms.

2.  For motion blur, deforming geometry or particles gets motion blur in
the 0001/ etc archive, while transforming motion blur gets motion blur in
the object transform.  In general transform motion blur in rib looks like:

MotionBegin [0 1] #for more samples it could be [0 .25 .5 .75 1] etc
    Transform at frame begin
    Transform at frame end
MotionEnd
Geometry calls here


for deformation:
Transform ....
MotionBegin [0 1] #for more samples it could be [0 .25 .5 .75 1] etc
    Geometry at frame 0
    Geometry at frame 1
MotionEnd

So if you look at the rib files it should be clear that with motion blur on
deformation has to be in the geometry archive while transforms can be in
the main rib.

3.  Furthermore the "slow" part of exporting a scene with motion blur is
that you have to export once for each motion sample.  (at least the
beginning and end) Which means blender re-evaluates things.  Furthermore in
renderman, and using the exporter you can specify certain objects to say
have 10 motion samples whereas the scene has just the beginning and end
motion.  This is very useful with rotating or fast moving objects.  So we
try to be smart when re-evaluating the scene and caching all the motion
needed before exporting any rib.

4.  Finally there is the bit where we try to "lazy rib gen".  That is, lets
say you have a scene and you render it then change one geometry.  We don't
need to export all the geometry anew, just the one changed.  So the system
tracks that.  Or if you move an object (the geometry doesn't change) it
should not re-emit the geometry archive.

It's all pretty complex.  I wanted to explain it all to kinda get it all
written down.  And also if you do want to test this maybe testing all the
edge cases of everything would be a great help.

Other things that would be great to help out with would be testing
interactive rendering.

Thanks
Brian

On Fri, Jan 8, 2016 at 2:16 PM, tobbew79 <notifications@github.com> wrote:

> I have a past as a C++/java programmer (professionally, then, but working
> in an entirely different field now). I have used python for scripting
> before. I'm new to the renderman renderer.
>
> If it makes a difference and is low priority (more than weeks away,
> because that might be what it takes for me to find the spare time to do it)
> I could try to look into improving that as a contribution to the project.
>
> Personally I'm not currently that worried about the time for the export
> (if I would become in the future I could do it then). What I'm unaware of
> is whether there's a cost in the current implementation on the ris renderer
> side that's affected by if objects are exported as deforming or not. If
> that overhead is small (it seems to me it's fast with motionblur, but
> testing deformation motion blur with a heavier character with motionblur
> and displacement is still on my to do list) it might not be worth the time
> and then perhaps it would be better if I did something else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/170#issuecomment-170142949>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by tobbew79** [comment]
I wonder if you misunderstood both the offer and the question. I'm offering to improve one method, is_deforming, if you think that would make a difference. It could be used both for when rib_caching is on to decide whether to regenerate ribs and and for exporting deforming objects for motion blur. Currently it checks for existence of some modifiers or shape keys. If you say that the reason for accepting false positives on deforming is the combination of keeping it simple and very small impact on export and rendering times [for example if the renderer itself is programmed to compare the different frames before setting an object as deforming, I would not expect that design to be in the renderer though, I'd expect it to be in the exporter] then it's not meaningful. The specific offer was due to limit rib involvement and mostly blender python involvement (which I have more use for a wider knowledge in in the future, and where I have a better base).

is_deforming could take an object and a frame number range, and the rib_cache could check is_deforming between last_exported_frame and current frame while for motion blur you could check for between previous and current frame 

Just from a quick look I think for example the shape keys should only be considered deforming if
(is mesh and) bpy.data.meshes[ ob.name ].shape_keys.animation_data is not None and shape_keys.animation_data.action (is not none and either has ...action.driver is not None [evaluating a driver over the course of the frame range might be possible but risks an unknown cost and is probably not worth the risk], or fcurves is not None and for each fcurve frame is within curve.range (then it's deforming), I took a look at where the NLA-strips are stored last night, I have forgotten now, but refinding it can't be difficult. That's the last case I can think of there. Just as particles are only deforming from emission_start to emission_end+max_particle_life. A potential risk faced with this however is that I do not where animation data on the nodetrees will be stored once the node generators are available. I might have to take a look at the node branch. 

I personally do not agree that writing an exporter in itself is difficult. It's just a lot of work, especially if you are not familiar with the formats in the beginning, now reading up on that is not itself hard but I do not have time for that (I was working for a company which distributed systems for realtime online stock trading, however now I work as a GP and I'm also a family father). Writing a good and optimized renderer however is very difficult.

I had already read enough of the code to know points 2-4 in what you are writing. I actually have not yet bothered to check the output from the exporter. I do not have any benchmarks or experience of the renderer to know the time cost of unneccessarily setting objects as deforming. Of course you could always apply modifiers to avoid objects set as deforming but keeping things nondestructive always feels better.

**Comment by bsavery** [comment]
Oh totally would be great to do that.  I was just giving some background on how things work.  And wanted to type it all out somewhere.  

Writing an exporter is not insanely difficult as you say, but the devil is in the details with various edge cases (for example, parent object is deforming and child is not or parent is not and child is etc) and also there are a few concept from Renderman (for example multiple motion samples that can be specified per object) that we wanted to adapt to Blender that made it more "interesting".

Anyway yes improving is_deforming would be a great help and what I was trying to get as in doing so you might run into some interesting edge cases.  Thanks!
