### ISSUE TITLE
Any news from render box noise （cause from direct specular）

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#171]
https://renderman.pixar.com/forum/showthread.php?s=&threadid=29949 

I have been post already in forum ( sorry to post here again. But this problem stop my work. )

I notice that those box artifact will only appear in direct specular pass （ other passes works fine）
I won't use Denoiser so the problem may not be related to denoiser
On the other hand. My PforB is latest version （with RMS 20.5） so albedo pass will not be a problem

So I hope there will be some news on this problem

I am so sorry to make you annoying......

**Comment by MWY3510** [comment]
Sorry for the lack of response MarcoCheng. I have been dealing with many issues lately. After having looked over your problem some more I am not sure that the problem lie's with the plugin. It might be with the PxrDisney shader. I cannot say for sure though. We should be able to more successfully address this problem tomorrow when vacation is over. Again sorry for the lack of activity on this.

I will keep this issue open to remind me and Brian about it.

**Comment by bsavery** [comment]
Think this is a prman issue related to light localized sampling.  Answered on RenderMan forums.
