### ISSUE TITLE
Issue with Linux command line rendering

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#172]
I've used command line rendering successfully in Linux several times, but since updating to 20.6 I'm not able to anymore, and I'm not sure where the issue lies.

Long story short everything renders fine from within Blender.  However, if I try to export an .rib and use the prman utility, it spits back an "RiArchive" read error for every output archive, stating that they don't exist.  I can go into the output folder and see the files so I'm not sure why the paths are getting screwed up (which is what I'm assuming is happening).  I updated the environment variables in my .profile for the 20.6 install but did I miss something, or is it the exporter?

**Comment by jdent02** [comment]
For elaboration here is the terminal printout:

prman /home/jon/Documents/PRmanout/Scene.rib
R12001 {ERROR}   File static/materials.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.runner_light_blue cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.old_metal cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.power_pipes cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.solar_panels cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.metal_gun cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.red_runners cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.yellow_warnings cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.stripe warning cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.gold_foil cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.black_metal cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.Metal cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File material.White_runners cannot be opened by RiReadArchive. (System Error: No such file or directory)
T02001 {ERROR}   Can't open texture "HDRI.tex". (filename or texture path incorrect?) (System Error: No such file or directory)
L61214 {ERROR}   Environment light failed to be created, map HDRI.tex not found.
R12001 {ERROR}   File static/Station.002-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/Station.003-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/Station.001-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/Station.005-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/Station.006-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/blue_runner_lights-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/red_runners-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/power_pipes-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/white_runners-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/Station.004-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/Station.007-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)
R12001 {ERROR}   File static/Station-MESH.rib cannot be opened by RiReadArchive. (System Error: No such file or directory)

**Comment by bsavery** [comment]
The rib file assumes you are running it from the directory it is in. All
the paths are relative to there

On Monday, January 4, 2016, jdent02 <notifications@github.com> wrote:

> For elaboration here is the terminal printout:
>
> prman /home/jon/Documents/PRmanout/Scene.rib
> R12001 {ERROR} File static/materials.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File material.runner_light_blue cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File material.old_metal cannot be opened by RiReadArchive.
> (System Error: No such file or directory)
> R12001 {ERROR} File material.power_pipes cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File material.solar_panels cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File material.metal_gun cannot be opened by RiReadArchive.
> (System Error: No such file or directory)
> R12001 {ERROR} File material.red_runners cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File material.yellow_warnings cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File material.stripe warning cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File material.gold_foil cannot be opened by RiReadArchive.
> (System Error: No such file or directory)
> R12001 {ERROR} File material.black_metal cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File material.Metal cannot be opened by RiReadArchive.
> (System Error: No such file or directory)
> R12001 {ERROR} File material.White_runners cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> T02001 {ERROR} Can't open texture "HDRI.tex". (filename or texture path
> incorrect?) (System Error: No such file or directory)
> L61214 {ERROR} Environment light failed to be created, map HDRI.tex not
> found.
> R12001 {ERROR} File static/Station.002-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/Station.003-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/Station.001-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/Station.005-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/Station.006-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/blue_runner_lights-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/red_runners-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/power_pipes-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/white_runners-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/Station.004-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/Station.007-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
> R12001 {ERROR} File static/Station-MESH.rib cannot be opened by
> RiReadArchive. (System Error: No such file or directory)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/172#issuecomment-168865243>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
The archives are in the same PRmanout folder as the .rib

**Comment by jdent02** [comment]
![screenshot from 2016-01-04 20 40 08](https://cloud.githubusercontent.com/assets/13521172/12106291/66bf1016-b323-11e5-8165-eefaeee42b5b.png)

**Comment by bsavery** [comment]
Try running.

Prman -cwd /users/jon/Documents/PRManout Scene.rib

I might have the PRManout path wrong but you get the idea. Or cd to that
directory and run prman scene.rib

On Monday, January 4, 2016, jdent02 <notifications@github.com> wrote:

> [image: screenshot from 2016-01-04 20 40 08]
> <https://cloud.githubusercontent.com/assets/13521172/12106291/66bf1016-b323-11e5-8165-eefaeee42b5b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/172#issuecomment-168875900>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
Same error.  Even tried CD'ing directly to the PRMan executable's directory and running it from there.

**Comment by jdent02** [comment]
Okay, if I manually enter the full file path of both the texture and archive folder in the .rib file then it works.  So ultimately it is a path issue 
![screenshot from 2016-01-04 20 54 30](https://cloud.githubusercontent.com/assets/13521172/12106463/5f8d6ffc-b325-11e5-89aa-3120d8450ab7.png)

**Comment by MWY3510** [comment]
Ok that's something that can be easily fixed.

**Comment by bsavery** [comment]
Sorry, maybe we're both confusing each other.  Both of these things should
be equivalent and fix your problem:

cd /home/jon/Documents/PRmanout
prman Scene.rib

or

prman -cwd /home/jon/Documents/PRManout

The rib file, as you found above has paths that are relative to the CURRENT
directory from which you are running prman.  So ./archives is relative to
wherever you are running prman from.  If you don't CD to the prmanout
directory before running prman it won't find the ./archives directory.  The
-cwd option to prman does the same thing.

On Mon, Jan 4, 2016 at 6:54 PM, jdent02 <notifications@github.com> wrote:

> Okay, if I manually enter the full file path of both the texture and
> archive folder in the .rib file then it works. So ultimately it is a path
> issue
> [image: screenshot from 2016-01-04 20 54 30]
> <https://cloud.githubusercontent.com/assets/13521172/12106463/5f8d6ffc-b325-11e5-89aa-3120d8450ab7.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/172#issuecomment-168877907>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
I'll check it out

**Comment by jdent02** [comment]
prman -cwd /home/jon/Documents/PRManout Scene.rib seems to work fine.  Wonder why I haven't run into this before.........

Anyway, thanks!  I'll let you guys get back to the important stuff :)

**Comment by MWY3510** [comment]
Great that you have it working.

Have a great week jdent02.
