### ISSUE TITLE
Question/Suggestion: About smooth normals (low priority), ui design choice

### ISSUE THREAD

**Issue by tobbew79** [bsavery/PRMan-for-Blender#173]
In blender every object (edge) already has a "shade smooth"/flat option, and there are several ways to affect this on faces. See https://www.blender.org/manual/modeling/meshes/smoothing.html . It seems to me the only thing the exporter currently respects is the "Export smooth normals" in the primitive variables settings on object data level. Is there a reason for this design choice? (Not overly important to me personally, as I'd probably either use baked normals or subdivision surfaces.)

**Comment by bsavery** [comment]
Actually maybe that button is a bit mislabeled.  It should say "export normals".  Let me explain.  We could always export all normals for polygons to the rib stream however that is unnescessary if they are just the default normal for poly faces.  So we don't (for the sake of speed) put the normal in the rib stream by default.  Turning on that check box will force the export of all normals.  So I think most of the smooth normal options will be rendered correctly by turning on that box.  

I suppose we could be a bit smarter perhaps when choosing to export or not export nomals.

**Comment by tobbew79** [comment]
What you write makes sense, and if that's the case then just renaming it to export normals would do. But in the version I have that is not how it works. This file shows two (in blender flat shaded) spheres, where the right one has export smooth normals checked. In the render the right one also has smooth normals in the render, which I think it should not have if it were like you said.
[shade_smooth.zip](https://github.com/bsavery/PRMan-for-Blender/files/79717/shade_smooth.zip)

**Comment by bsavery** [comment]
You're right.  Sorry for my confusion (what I described was how it worked in my head).  

So I have a fix for this.  However, I wonder if the "correct" answer will be to always put out all normals on all polys.  Unfortunately there's no way on an object level to tell if the object is all smooth or all flat polys or 1/2 each.  And in the rib stream we can't just put normals out for some polys.  I'll test and see if outputting all normals slows down considerably.

**Comment by bsavery** [comment]
And obviously if we always output normals smooth or flat (what you see in the blender viewport) we wouldn't need the button.

**Comment by bsavery** [comment]
Which I just checked in.  Now we just follow the blender normal settings.

**Comment by MWY3510** [comment]
Brian,

Was there any slowdown?

**Comment by bsavery** [comment]
Barely any.  Less than a second on the Cosmos Laundromat benchmark.

On Thu, Jan 7, 2016 at 5:50 PM, MWY3510 <notifications@github.com> wrote:

> Brian,
>
> Was there any slowdown?
>
> On Thu, Jan 7, 2016 at 8:43 PM, bsavery <notifications@github.com> wrote:
>
> > Closed #173 <https://github.com/bsavery/PRMan-for-Blender/issues/173>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bsavery/PRMan-for-Blender/issues/173#event-508947648
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/173#issuecomment-169863792>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
Great! never mind me then.
