### ISSUE TITLE
Deforming objects with changing topology

### ISSUE THREAD

**Issue by tobbew79** [bsavery/PRMan-for-Blender#176]
I found a problem with the current implementation of is_deforming - objects changing topology (for example if you animate an array modifier). It provides a nice error R07006 cannot conform motion samples from the renderer (and the object is completely ignored from output), but no crash. How should this be handled by the exporter? Should it force is_deforming to return false? Or should that be left as an open issue?

**Comment by bsavery** [comment]
RenderMan does not support changing topology in motion blur. Is there a way
to detect changing topology easily other than counting the vertices?  Which
might be enough.


On Saturday, January 9, 2016, tobbew79 <notifications@github.com> wrote:

> I found a problem with the current implementation of is_deforming -
> objects changing topology (for example if you animate an array modifier).
> It provides a nice error R07006 cannot conform motion samples from the
> renderer (and the object is completely ignored from output), but no crash.
> How should this be handled by the exporter? Should it force is_deforming to
> return false? Or should that be left as an open issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/176>.
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by tobbew79** [comment]
Agreed, counting vertices is probably the best way. I was considering the limited amount of datapaths in modifiers which actually change topology, but that would not be compatible with scripts which change topology and probably not with future node systems either. A problem with counting vertices though is that you'll need the count from both frames on all objects, meaning you'll be pretty close to having fetched all meshes, or at least all from the first frame and the ones from the second previous frame one at a time, unless they are deforming. 

A general question might actually be if pure scripts implemented only as frame listeners and deforming objects should be supported for the is_deforming, if so the only way will be to actually store all meshes from the two frames and compare them by brute force.

I've been thinking a lot about difficult cases that are hard to predict. I think the most difficult will be animations in scripts (be it written or nodal ones). If that's to be supported I can't see anything else than bruteforce vertice comparisons, but that will come with serious performance penalties on export.  An option is to have a system that does it best at finding deformations, trying to be smart (ie checking for animations on armatures connected to armature modifiers, for animations on the lattice on a lattice deformer and so on) but it will have to be set to rather have false positives than false negatives (but less than current system). But whenever we try that we risk false negatives (which is worse because it while it won't waste resources, the resulting image will be wrong), and that means you might have to have an override switch on object level to manually set deforming if you plan on using addons which use frame listeners to change things.

What do you think?
