### ISSUE TITLE
Can I append other blend files object？

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#177]
I make some PRman render before. Can i link those object back to my new renderman render? Seems all RenderMan Nodetree lost due to append.

**Comment by MWY3510** [comment]
This seems related to issue #143. You can import materials its just that you must also import the node-tree separately. Sorry about this but it is related to the material copying. At least there is a workaround for the moment.

**Comment by MWY3510** [comment]
Closed because it is possible to link objects and materials seamlessly now.

**Comment by bsavery** [comment]
I should note that I think appending still doesn't work unless you copy
over the node trees manually.

On Fri, May 6, 2016 at 7:29 PM, MWY3510 <notifications@github.com> wrote:

> Closed #177 <https://github.com/bsavery/PRMan-for-Blender/issues/177>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/177#event-653320634>
>



-- 
brian.savery@gmail.com
508-274-8700
