### ISSUE TITLE
Using denoise option, Image Tool stays black for a long time

### ISSUE THREAD

**Issue by maeg** [bsavery/PRMan-for-Blender#178]
When I check the denoise post-process option and use IT as display driver, there seems to happen anything for a long time until the render is processed. Is this the normal an expected behavior?

When unchecked, it takes some time and then I can see the render process in IT: It runs from the top left to the bottom right.

Probably it is not the right place to add another question, but I did not find any information on that.  I read number of samples is reduced when using denoise, Is there a given number of samples used oder is it reduced by a given factor?

**Comment by MWY3510** [comment]
maeg,

Yes this is the expected behaviour. The denoise post-process is really meant for your final image so in most cases this is not an issue. Let us know if you have any other questions.

MWY3510
