### ISSUE TITLE
Bug: Texture file names including . are truncated when converting to .tex (I think)

### ISSUE THREAD

**Issue by tobbew79** [bsavery/PRMan-for-Blender#179]
I think the problem is the files have materials and textures with the same beginning of the name but the second has a .001 before the file ending (.png) in the name. 
ie texture.png
texture.001.png

get_tex_file_name (nodes.py, line 1112 in my files)

the return (second rsplit attempt is using maxsplit 2 [why?], throwing parts of my filename away. It should be maxsplit 1, I think. ) See http://python-reference.readthedocs.org/en/latest/docs/str/rsplit.html

**Comment by bsavery** [comment]
Ah yes.  I fixed this as part of the UDIM fix.
