### ISSUE TITLE
error if the scene does not have camera

### ISSUE THREAD

**Issue by pitiwazou** [bsavery/PRMan-for-Blender#182]
If you don"t have camera in the scene, you have this error.

It should add a text, no camera, please add one to render.

http://pitiwazou.com/screenshots/blender-app_2016-01-31_18-20-42.png

**Comment by bsavery** [comment]
So you're saying there should be an error message?  Can't really render if we don't know where to render from!

**Comment by pitiwazou** [comment]
There should be a message in the info or a popup indicating you need a cam instead of this error message.

**Comment by bsavery** [comment]
Fixed.
