### ISSUE TITLE
If duplicate area = NodeTree connected

### ISSUE THREAD

**Issue by pitiwazou** [bsavery/PRMan-for-Blender#183]
If you duplicate and area light, the nodetree is connected, you change one, that change the other.

It's not good, they need to be different.

Example.
http://pitiwazou.com/screenshots/2016-02-01_11-57-01.gif

**Comment by bsavery** [comment]
Can you attach the scene for that?

**Comment by pitiwazou** [comment]
Here it is, in fact when duplicating the area, the node tree use the previous area data, not the new one.

http://pitiwazou.com/screenshots/2016-02-01_19-05-17.mp4

https://www.dropbox.com/s/mjbzqzilji7ex99/area_duplication_issue.blend?dl=0

**Comment by bsavery** [comment]
Well when Duplicating a light (or object) the data nodes are actually shared.  And the node tree is on the data node.  Actually if you duplicate any light in blender you should see the same thing no?

**Comment by bsavery** [comment]
I mean you should see the same behavior with cycles or the blender render.

**Comment by pitiwazou** [comment]
Nope, when you duplicate a light or an object, you can change the settings.
that duplicate the node tree but it's a new one.

http://pitiwazou.com/screenshots/2016-02-01_20-32-19.gif

If you want to share the data you can yes.

**Comment by bsavery** [comment]
Oh ok.  I was doing Alt+D vs Shift + D.

**Comment by bsavery** [comment]
So the issue here is the nodetree setting is saved on the lamp.renderman as a string property.  When you copy the lamp, the string property is copied, but the corresponding nodetree is not.  Really what we should be doing is using the existing (cycles) nodetree, but that hasn't worked for various reasons.  I'd put this on the todo list. .

**Comment by bsavery** [comment]
I'm going to mark this as a 21 todo as the light node are all changing there...

**Comment by bsavery** [comment]
Furthermore there will not be a whole nodetree for the lights in 21.  Just the shader itself.
