### ISSUE TITLE
Some are are not updated in the ipr

### ISSUE THREAD

**Issue by pitiwazou** [bsavery/PRMan-for-Blender#184]
As you can see on this gif, I can update 2 areas, but not the third.

http://pitiwazou.com/screenshots/2016-02-01_12-03-08.gif

I have to restart the ipr to see the difference.

**Comment by bsavery** [comment]
Bit hard to tell from the gif.  Can you attach the scene again?  Sorry.  Seems to work for me here though with a simple scene.

**Comment by pitiwazou** [comment]
Depend on the blender, I tested and I had the same issue and after a crash of blender it works.
Weird.

**Comment by bsavery** [comment]
Ok I have some pending updates to ipr that might help a bit with stability

On Monday, February 1, 2016, Cédric Lepiller <notifications@github.com>
wrote:

> Depend on the blender, I tested and I had the same issue and after a crash
> of blender it works.
> Weird.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/184#issuecomment-178161154>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
I'm going to close this issue for now.  If you can reproduce the crash send a scene.
