### ISSUE TITLE
Feature suggestion for Blender driven rendering with denoiser on

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#185]
So it's been established that running a render from within Blender with the denoiser on and an image format that feeds back into the image editor (like EXR or TIFF) drops the rendering speed off a cliff, mainly because PRMan has to spend so much time frequently writing huge checkpoint EXR's with all the extra AOV's.  Would it make sense to either disable image feedback or force the 'IT' driver as an output when the denoiser is active and a render is started from within Blender?  I think a lot of people might shy away from using the (awesome) denoiser because they notice that it really slows down rendering but they don't understand or figure out why.

**Comment by MWY3510** [comment]
jdent02,

This will be covered by a new item in 21. So yea stay tuned.

**Comment by bsavery** [comment]
Yes.  I would say denoiser should be disabled in preview renders and there
should be a "batch render" button would allow you to use it.

On Wed, Feb 3, 2016 at 2:22 PM, MWY3510 <notifications@github.com> wrote:

> jdent02,
>
> This will be covered by a new item in 21. So yea stay tuned.
>
> On Wed, Feb 3, 2016 at 5:06 PM, jdent02 <notifications@github.com> wrote:
>
> > So it's been established that running a render from within Blender with
> > the denoiser on and an image format that feeds back into the image editor
> > (like EXR or TIFF) drops the rendering speed off a cliff, mainly because
> > PRMan has to spend so much time frequently writing huge checkpoint EXR's
> > with all the extra AOV's Would it make sense to either disable image
> > feedback or force the 'IT' driver as an output when the denoiser is
> active
> > and a render is started from within Blender? I think a lot of people
> might
> > shy away from using the (awesome) denoiser because they notice that it
> > really slows down rendering but they don't understand or figure out why
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bsavery/PRMan-for-Blender/issues/185>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/185#issuecomment-179503240>
> .
>



-- 
brian.savery@gmail.com
508-274-8700
