### ISSUE TITLE
Hair children settings export

### ISSUE THREAD

**Issue by shemkel** [bsavery/PRMan-for-Blender#187]
I'm unable to export advanced hair styles, like waves or length value correctly. While in viewport I have this:
![vieport](https://cloud.githubusercontent.com/assets/15322760/12815888/80a3b912-cb49-11e5-9120-3c84ec8b0a93.jpg)
with this settings:
![settings](https://cloud.githubusercontent.com/assets/15322760/12815932/d414622c-cb49-11e5-84e1-9594856b1d92.JPG)
final scene renders completely different:
![render](https://cloud.githubusercontent.com/assets/15322760/12815966/fab0f29c-cb49-11e5-9d45-099c855cded7.jpg)

Maybe I'm doing something wrong, but in final render I can't see waves, random value in roughness, and length is a bit different.
I hope someone can tell me what am I doing wrong, or is this bug, or WIP feature :)
(I used newest version of plugin to render this, downloaded yesterday)

**Comment by shemkel** [comment]
And there is another thing: after rendering, when I go back to blender, I can see hair like in render, I need to enter particle edit and exit it, to see my setup. I encounter this issue in my previous tests.

**Comment by bsavery** [comment]
Hmmm I seem to see an issue when using virtual parents.  Does turning that off work for you?

Brian

**Comment by shemkel** [comment]
It doens't really help...

But I think I found the reason that is causing the problem.
When I switch to cycles, in render section of particles, there is option called steps:
![rendercycles](https://cloud.githubusercontent.com/assets/15322760/12841037/9b6f1e54-cbe8-11e5-8faf-aad6ef8f7bfc.JPG)
Steps adds additional sub-points to basic hair spline with ^2.
I think, plugin uses basic spline segments, smooth them and then export to renderer. Even if children settings are exported, I can't see them, because of low hair detail.

**Comment by shemkel** [comment]
okay, I was right. But it's kinda weird...
When I switched to cycles, I increased steps default value of 3 to 7, as you can see on screenshot, and the I switch back to renderman.. and this helped, hair render now correct, with much greater detail, waves and they are shorter, same as in viewport.
But still, this option should be available in renderman :D

**Comment by bsavery** [comment]
Ok yeah we're just getting the curves straight from blender if that
controls the fidelity of them. I'll expose that in the ui

On Friday, February 5, 2016, shemkel <notifications@github.com> wrote:

> okay, I was right. But it's kinda weird...
> When I switched to cycles, I increased steps default value of 3 to 7, as
> you can see on screenshot, and the I switch back to renderman.. and this
> helped, hair render now correct, with much greater detail, waves and they
> are shorter, same as in viewport.
> But still, this option should be available in renderman :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/187#issuecomment-180323019>
> .
>


-- 
brian.savery@gmail.com
508-274-8700
