### ISSUE TITLE
Material RIB not correct. Two outgoing edges in graph generate mutliple instances in RIB

### ISSUE THREAD

**Issue by gabyx** [bsavery/PRMan-for-Blender#188]
Open this blender file:

The material PxrTexture appears several times, due to two connections to PxrBlend 

[gridTexture2.blend.zip](https://github.com/bsavery/PRMan-for-Blender/files/119522/gridTexture2.blend.zip)

**Comment by bsavery** [comment]
Good catch.

**Comment by bsavery** [comment]
Although technically it won't break anything.  But I'll fix that

**Comment by bsavery** [comment]
Fixed this.
