### ISSUE TITLE
Outputting Animation (not yet working) / Additional RIB String

### ISSUE THREAD

**Issue by gabyx** [bsavery/PRMan-for-Blender#189]
I have some sugestion for further improvements :-)

The stuff is so far pretty cool.

However it would be very cool to have some additional features such as:

- Export all Scene Frames of the animation

- Add some additional option to allow a custom rib archive or string be written in the final RIB at various levels:
   -> Object Attribute level (in the object menu)
   -> Scene Attribute level (in the Scene Menu)

maybee introduce some variables (frame idx, time and so one) which are replaced : ${frameIdx}
to output something like

```
AttributeBegin 
                       <ADDITIONAL RIB STRING PRE> for example : ReadArchive MySpecialShit.rib
			Attribute "identifier" "name" ["Plane"]
			Transform [ 3.1831 0 0 0  0 3.1831 0 0  0 0 3.1831 0  0 0 0 1 ]
			AttributeBegin 
				ReadArchive "material.GridTexture" 
				Procedural2 "DelayedReadArchive2" "SimpleBound" "string filename" ["static/Plane-MESH.rib"] "float[6] bound" [-1 1 -1 1 0 0]
			AttributeEnd 
                       <ADDITIONAL RIB STRING POST>
    AttributeEnd 
```

that allows also to have some empty objects in blender which can then account for other external RIB stuff :-)

**Comment by bsavery** [comment]
Gabrirel. You clearly understand this a bit.  There's some code in there for outputting a "rib box" (if you ever used SLIM) which is basically what you're talking about... (bty_inlinerib_texts) in properties.py.  

Ryan is working on the rib archiving to be checked in soon.  However if you knew some python and wanted to take a crack at re-enabling the inline rib stuff that would be a pretty simple project!  All that would have to happen is putting it back in the ui, and then making sure the get put into the rib stream,  the ri call is 
ri.ArchiveRecord(ri.RI_VERBATIM, my_rib_string)   I believe in python that should work.

**Comment by MWY3510** [comment]
Gabrirel,

I'm glad that you are taking an interest in these features. I hope to be able to provide most of these using RIB archives. But as Brian said if you want to take a swing at inline rib then that would be great. If you have any more questions concerning this fell free to ask.

Sincerely,
Ryan

**Comment by jdent02** [comment]
Did this ever get added in?  I can take a swing at it.

**Comment by MWY3510** [comment]
Good day jdent. Yes and no is the answer. First, I did get RIB archiving done (including animations) and it is in devel. Second, I did allow empties to be used as RIB archive objects. The only things that are not implemented are the custom strings in rib and the export all frames (as far I can remember.) Let me know if you have more questions.

**Comment by jdent02** [comment]
I was referring to the custom strings part, knew you were working on archives :)

**Comment by MWY3510** [comment]
Oh sorry I did not know which item you were referring to. In that case feel free to take a loot at it. It should be very straight forward.

**Comment by jdent02** [comment]
If it's just adding an inline custom string at the world, object or light level I should be able to crank that out pretty fast this evening (cross fingers).

**Comment by jdent02** [comment]
Will do.  For custom strings the call is "ri.ArchiveRecord(ri.COMMENT, my_rib_string)" right?

**Comment by MWY3510** [comment]
Well you can just use the string literal like so ri.ArchiveRecord('comment', comment).

**Comment by bsavery** [comment]
Yes.  Super easy.

On Thu, May 5, 2016 at 8:53 AM, MWY3510 <notifications@github.com> wrote:

> Well you can just use the string literal like so
> ri.ArchiveRecord('comment', comment).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/189#issuecomment-217192784>
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
actually you wanted ri.ArchiveRecord(ri.VERBATIM, "some rib").  ANyway done for .9
