### ISSUE TITLE
RenderMan blender in linux (ubuntu)

### ISSUE THREAD

**Issue by Andrewson3D** [bsavery/PRMan-for-Blender#19]
I'm trying to install the plugin in blender does not work in linux

**Comment by bsavery** [comment]
Please be more specific. You need to install RenderMan first which can be somewhat tricky on ubuntu since it is an RPM file.  But you can search around for ways to install an RPM on ubuntu.

**Comment by Andrewson3D** [comment]
I'm talking about the plugin in the blender does not work

**Comment by Andrewson3D** [comment]
![screenshot from 2015-07-13 00 15 35](https://cloud.githubusercontent.com/assets/12683511/8641060/5a996a16-28f4-11e5-863f-2eede94333ac.png)

**Comment by Andrewson3D** [comment]
like that

**Comment by Andrewson3D** [comment]
I use ubuntu 15 64 bit

**Comment by bsavery** [comment]
Please see Installation.txt:

https://github.com/bsavery/PRMan-for-Blender/blob/master/installation.txt

You have to install renderman first.  If you didn't let it install in the normal location, you will have to set the RMANTREE environment variable, as described in installation.txt.

**Comment by zeffii** [comment]
I also found the installation to be somewhat quirky and the guide was perhaps too terse for buffoons like me.

If I was writing the instructions for my past self, it would be something like:

- follow [the pr renderman instructions](http://rendermansite.pixar.com/view/get-renderman )
    - means downloading the installer, registering for forum access (gives you a username and password   you can use for the renderman server installation.  
   - the installer is packaged as an rpm, a .deb file for ubuntu users would have been great, but it's not a big deal to do this manually, or use `alien` to convert rpm to deb (i've read this works too)
 - with the 20+ mb `rpm` on your disk you can extract it to a temp location, it contains an `/opt/pixar/..` structure, and inside the `RenderManNC-Installer` folder is a `bin` folder.  The bin folder contains the executable installer. This installer must be run using `sudo`. If you simply click the installer executable it will show a message to this effect, copy that command into a terminal to start the installation process
-  when running the installer as sudo it will  ask for username and password and at some point also show a notice that it didn't find Maya (see the more info in that error box to confirm..) ,  
-  Then once the installation is complete, you will have a new 

    ````
    /opt/pixar/RenderManProServer-20.0
    /opt/pixar/pixar.license
    ````
    you can then install the Blender prman add-on like any normal add-on.
