### ISSUE TITLE
Volume Render Seems still buggy. Render Stop Case

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#191]
I just add multiple lamp render will stop after few second(1~2sec). Not Error message. Just displays as Render Finish and render time 00：00：00
Notes：
My RM version:20.5
https://www.dropbox.com/s/n9oqm3i615dzmbj/buggie.blend?dl=0

**Comment by bsavery** [comment]
There was a ton of volume improvements put in to 20.7.  Can you try installing that?

**Comment by MarcoCheng** [comment]
Cool I will install tomorrow Thanks ！

**Comment by Mouldfish** [comment]
I've also had problems with volume. I'm using 20.7 and the latest build of the Blender addon. All seems fine during the render then it sticks when denoising. It doesn't finish.

**Comment by bsavery** [comment]
So there is a volume specific denoise setting that we don't currently use.
Can you attach the scene.

On Fri, Feb 19, 2016 at 4:14 AM, Mouldfish <notifications@github.com> wrote:

> I've also had problems with volume. I'm using 20.7 and the latest build of
> the Blender addon. All seems fine during the render then it sticks when
> denoising. It doesn't finish.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/191#issuecomment-186192897>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by Mouldfish** [comment]
Sure, here it is: https://db.tt/Y3BDNod5
It takes a long time to render, then doesn't complete.
