### ISSUE TITLE
Will Blockers, Gobos, and Portals into todo list of Blender RM?

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#192]
Blockers, Gobos, and Portals seems a powerful feature in RenderMan. It will be great if those feature got into blender PRMan.

BTW what is gobos do?

**Comment by bsavery** [comment]
21.0

On Wed, Feb 10, 2016 at 5:38 AM, MarcoCheng <notifications@github.com>
wrote:

> Blockers, Gobos, and Portals seems a powerful feature in RenderMan. It
> will be great if those feature got into blender PRMan.
>
> BTW what is gobos do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/192>.
>



-- 
brian.savery@gmail.com
508-274-8700
