### ISSUE TITLE
RM20.7 + Latest commit 0d37750 Install fail

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#193]
Today I updated to renderman 20.7 and new version of addon for blender (Latest commit 0d37750）this morning and renderman no longer useable.

The error report has been shown as follow
//----
Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender\Blender2.76b\2.76\scripts\modules\addon_utils.py", line 324, in enable
    mod = __import__(module_name)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\PRMan-for-Blender-master\__init__.py", line 38, in <module>
    from . import engine
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\PRMan-for-Blender-master\engine.py", line 70, in <module>
    import prman
ImportError: No module named 'prman'
//----

**Comment by bsavery** [comment]
Check what you have your rmantree env variable set to and that it is where
the latest RenderMan 20.7 is installed

On Wednesday, February 10, 2016, MarcoCheng <notifications@github.com>
wrote:

> Today I update my renderman 20.7 and new version of addon for blender
> (Latest commit 0d37750
> <https://github.com/bsavery/PRMan-for-Blender/commit/0d377502b18af89c4a367750c942abe8a4e5999b>）this
> morning and renderman no longer useable.
>
> The error report has been shown as follow
> //----
> Traceback (most recent call last):
> File "D:\Program Files\Blender
> Foundation\Blender\Blender2.76b\2.76\scripts\modules\addon_utils.py", line
> 324, in enable
> mod = *import*(module_name)
> File "C:\Users\user\AppData\Roaming\Blender
> Foundation\Blender\2.76\scripts\addons\PRMan-for-Blender-master__init__.py",
> line 38, in
> from . import engine
> File "C:\Users\user\AppData\Roaming\Blender
> Foundation\Blender\2.76\scripts\addons\PRMan-for-Blender-master\engine.py",
> line 70, in
> import prman
> ImportError: No module named 'prman'
> //----
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/193>.
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MarcoCheng** [comment]
Hi Brain. I can't set RenderMan path ( There has no way to set the path unlike older version of RM for BL addon)

**Comment by MarcoCheng** [comment]
![p zzlkb pdk_ll p 4qf 4c](https://cloud.githubusercontent.com/assets/15306113/12975900/a9dd3a18-d0fa-11e5-97a1-c7bc9cd9d412.png)
As image

**Comment by MarcoCheng** [comment]
@bsavery  can you help me？

**Comment by bsavery** [comment]
It sounds like you have the environment variables are wrong after installing.  

Follow this page:
https://renderman.pixar.com/resources/current/RenderMan/installNT.html#setting-up-the-user-s-environment

And make sure that your rmantree is set to the latest installed RenderMan Pro Server dir, and do you have the PYTHONPATH variable set?  You shouldn't.

**Comment by manuelalbertcom** [comment]
Hello bsavery,

I would like to evaluate RenderMan for my business but do seem to have the same problem as MarcoCheng - trying to activate the addon I get the same output in the blender user preferences window. 

Traceback (most recent call last):
  File "C:\Users\Manuel\Blender\Trunk\blender-2.77.0-git.298aac3-AMD64\2.77\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\Manuel\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender-master\__init__.py", line 38, in <module>
    from . import engine
  File "C:\Users\Manuel\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender-master\engine.py", line 70, in <module>
    import prman
  File "C:\Program Files\Pixar\RenderManProServer-20.7\bin\prman.py", line 77, in <module>
    import prman_for_python_3 as prman_for_python
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden. (the module wasn't found)

I am also using the latest renderman 20.7 in combination with the latest blender addon. I read through here https://renderman.pixar.com/resources/current/RenderMan/installNT.html#setting-up-the-user-s-environment but have no idea, how I set those paths. Help would be much appreciated. Thanks.

**Comment by bsavery** [comment]
Hey Manuel (and any one else reading this). I posted in a thread on the
RenderMan forums. Basically on Windows there is an issue when using cross
Python versions of c modules. Long story short blender switched to Python
3.5 for 2.77 and prman on Windows only didn't work for that.

Solutions at this moment are to use blender 2.76 or wait for prman 20.8
where I've fixed the python module to be compatible with all versions. If
you have a strong reason that you have to use blender 2.77 right now I
might have another work around I haven't tested yet.

Again for others reading this it's only on Windows with blender 2.77 and
RenderMan 20.7

On Monday, February 29, 2016, manuelalbertcom <notifications@github.com>
wrote:

> Hello bsavery,
>
> I would like to evaluate RenderMan for my business but do seem to have the
> same problem as MarcoCheng - trying to activate the addon I get the same
> output in the blender user preferences window.
>
> Traceback (most recent call last):
> File
> "C:\Users\Manuel\Blender\Trunk\blender-2.77.0-git.298aac3-AMD64\2.77\scripts\modules\addon_utils.py",
> line 330, in enable
> mod = *import*(module_name)
> File "C:\Users\Manuel\AppData\Roaming\Blender
> Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender-master__init__.py",
> line 38, in
> from . import engine
> File "C:\Users\Manuel\AppData\Roaming\Blender
> Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender-master\engine.py",
> line 70, in
> import prman
> File "C:\Program Files\Pixar\RenderManProServer-20.7\bin\prman.py", line
> 77, in
> import prman_for_python_3 as prman_for_python
> ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
> (the module wasn't found)
>
> I am also using the latest renderman 20.7 in combination with the latest
> blender addon. I read through here
> https://renderman.pixar.com/resources/current/RenderMan/installNT.html#setting-up-the-user-s-environment
> but have no idea, how I set those paths. Help would be much appreciated.
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/193#issuecomment-190218528>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
I'm going to call this closed for now.  20.8 should work on windows with the newer Python 3.5 builds of Blender (blender 3.77+)
