### ISSUE TITLE
RMANTREE Config issues.

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#195]
Configuration of the addon is unnecessarily difficult.  Setting an env variable for RMANTREE is too hard for most users and where 99% of the config issues come in.  Here's what I'm proposing. 

1. Have an "RMANTREE" preference in the addon preferences.  This is where RMANTREE comes from. 
2.  If that is not set try to pull from env variables or latest found as we already do.  
3.  Users can set the RMANTREE setting the preferences manually.  Maybe put a button in there to "pull from latest installed"...

**Comment by MWY3510** [comment]
Brian,

I think that would be a great idea.

**Comment by bsavery** [comment]
Here's what I came up with:  Basically a two part preference.  The default is still just "Grab the latest installed to default location" 

First the user chooses how to get renderman 
1.  Choose from what's installed (default).  This will give them a dropdown of RenderMan versions that installed to default location (/Applications/Pixar on osx).  Or by default get the newest installed version.
2.  Get from RMANTREE environment variable for power users who use env variables (also gives feedback what that is set to)  In hindsight not many blender users use env variables but still want to include it.
3.  Set install location manually with file browser
<img width="650" alt="screen shot 2016-02-23 at 8 55 19 pm" src="https://cloud.githubusercontent.com/assets/1892220/13276016/e74946ac-da6f-11e5-9cfb-66ff1e174be5.png">
<img width="642" alt="screen shot 2016-02-23 at 8 55 28 pm" src="https://cloud.githubusercontent.com/assets/1892220/13276017/e7589620-da6f-11e5-8eca-d8fbe8968db7.png">
<img width="650" alt="screen shot 2016-02-23 at 8 55 46 pm" src="https://cloud.githubusercontent.com/assets/1892220/13276018/e767d8f6-da6f-11e5-8559-27b543da1f8f.png">
<img width="638" alt="screen shot 2016-02-23 at 8 55 56 pm" src="https://cloud.githubusercontent.com/assets/1892220/13276019/e76c33d8-da6f-11e5-978f-31fa3f71303c.png">

**Comment by bsavery** [comment]
Done in devel branch.

**Comment by ChameleonScales** [comment]
I don't have these preferences. Is it normal ?

**Comment by jdent02** [comment]
You can't run just the preferences module as it's missing all the commands that initialize the plugin. Is here any particular reason you're trying to run it by itself?

**Comment by ChameleonScales** [comment]
Ok. I was trying to run it by itself because I wanted to understand why I don't have the preferences.

**Comment by ChameleonScales** [comment]
Ok I understand better now. The issue is that I get this error when trying to enable the add-on :
```
Traceback (most recent call last):
  File "/home/caetano/Installed_programs/blender/2.78/scripts/modules/addon_utils.py", line 349, in enable
    mod.register()
  File "/home/caetano/.config/blender/2.78/scripts/addons/RenderManForBlender-master/__init__.py", line 121, in register
    load_addon()
  File "/home/caetano/.config/blender/2.78/scripts/addons/RenderManForBlender-master/__init__.py", line 95, in load_addon
    if guess_rmantree():
  File "/home/caetano/.config/blender/2.78/scripts/addons/RenderManForBlender-master/util.py", line 553, in guess_rmantree
    "Error loading addon.  RMANTREE %s is not valid.  Correct RMANTREE setting in addon preferences." % rmantree)
  File "/home/caetano/.config/blender/2.78/scripts/addons/RenderManForBlender-master/util.py", line 59, in throw_error
    raise ImportError(msg)
ImportError: Error loading addon.  RMANTREE  is not valid.  Correct RMANTREE setting in addon preferences.
```
But The preferences don't appear until the add-on is enabled, so how am I supposed to "Correct RMANTREE setting in addon preferences" ?

**Comment by ChameleonScales** [comment]
I tried
```
export PATH="${PATH}:/opt/pixar/RenderMan-Installer-ncr-21.4/bin"
export RMANTREE="${RMANTREE}:/opt/pixar/RenderMan-Installer-ncr-21.4"
```
but it didn't seem to change anything. I still can't enable the add-on. Any idea ?
