### ISSUE TITLE
importance sampling doesn't work?

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#196]
When I add an environment lamp, I set Light Panel >Sampling >Importance into higher value something like 1024, 2048, 4096 to give a Importance Sampling to HDRs. But seems it change nothing with the render. In my experiences, It should become lesser noise and higher contrast to the shadow like One of the RenderMan Doc below（although I know it is for Reyes, but i believe it works same with RIS）.
https://renderman.pixar.com/view/TGT_REYES_Lighting

So in this situation, Importance supported or not or just a bug？

Thanks！
Marco

**Comment by bsavery** [comment]
If you go to the scene advanced settings and turn of the light localized
sampling setting you should see it. The light localization overrides it

On Tuesday, February 16, 2016, MarcoCheng <notifications@github.com> wrote:

> When I add an environment lamp, I set Light Panel >Sampling >Importance
> into higher value something like 1024, 2048, 4096 to give a Importance
> Sampling to HDRs. But seems it change nothing with the render. In my
> experiences, It should become lesser noise and higher contrast to the
> shadow like One of the RenderMan Doc below（although I know it is for Reyes,
> but i believe it works same with RIS）.
> https://renderman.pixar.com/view/TGT_REYES_Lighting
>
> So in this situation, Importance supported or not or just a bug？
>
> Thanks！
> Marco
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/196>.
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
Let me know if that helps.

**Comment by MarcoCheng** [comment]
I tested it yesterday. But seems I get the same shadow contrast level then I use light localization overrides.The only differences is more white noise artifacts on indirect light ray surfaces and become much slower when I turn off light localization overrides. So I think I just keep using light localization overrides. But any ways to dual with IBLs lighting like multiple importance sampling(gives more sampling in highlight area like sun, to make more obvious shadow）in Arnold or Cycles?

**Comment by bsavery** [comment]
Sorry if I was a bit unclear with my last comment. The global light
localization setting turns on a mode in prman where the importance and
balancing of samples between lights is managed automatically.  If however
you want to manage this yourself you can turn this off and use the
importance settings on each light.

The lights do multiple importance sampling themselves by default.

On Wednesday, February 17, 2016, MarcoCheng <notifications@github.com>
wrote:

> I tested it yesterday. But seems I get the same shadow contrast level then
> I use light localization overrides.The only differences is more white noise
> artifacts on indirect light ray surfaces and become much slower when I turn
> off light localization overrides. So I think I just keep using light
> localization overrides. But any ways to dual with IBLs lighting like
> multiple importance sampling(gives more sampling in highlight area like
> sun, to make more obvious shadow）in Arnold or Cycles?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/196#issuecomment-185507739>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
Did that explain it?
