### ISSUE TITLE
Texture parameter errors

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#198]
Minor ignorable error when rendering, but I noticed there was a "int filename" parameter put into the rib stream when using a PxrTexture node.  It doesn't cause a problem, but there's already of course a "string filename" parameter to PxrTexture so it throws an error like this:

PRMan: R10043 {WARNING} filename, unknown or mismatched input parameter of PxrTexture (PxrTexture)".

Not sure where the other parameter is get getting in there?  Maybe from the txmake options?

**Comment by MWY3510** [comment]
Yea, This is coming from txmake options. I'll take care of that tonight.

**Comment by MWY3510** [comment]
Fixed awaiting merge.

**Comment by MWY3510** [comment]
Anyway this is in devel (and works well) and a merge request is active for the master branch. I am calling this fixed since I have not seen this error after implementing the fix.
