### ISSUE TITLE
Animated texture sequences supported yet?

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#200]
I try million ways to import a tiff image sequence texture to rm like adding ####, $f4 to tell renderman sequence number, but none of them work!  So any ways to add a sequences import button into pxr Texture?

**Comment by bsavery** [comment]
Right now we don't support that.  It should be easy though.  have a few changes pending but will add that next.

**Comment by bsavery** [comment]
I uploaded a fix for this.
