### ISSUE TITLE
Meshes in linked blend file don't render

### ISSUE THREAD

**Issue by petertsoi** [bsavery/PRMan-for-Blender#201]
I linked some files together and while resulting scene renders correctly with Cycles, prman shows some errors after the render completes and the linked objects are missing. An test scene is attached. To reproduce, try rendering from Scene.blend.

Config:
OS X 15D21
PRMan 20.7 linked Tue Jan 26 11:42:50 2016 PST @1571626
PRMan-for-Blender: 0d377502

[LinkingError.zip](https://github.com/bsavery/PRMan-for-Blender/files/141963/LinkingError.zip)

**Comment by bsavery** [comment]
Fixed.  FYI this was really an issue of duplis within duplis not working correctly.

Brian

**Comment by petertsoi** [comment]
Verified, working at 3f968ef. Thanks!
