### ISSUE TITLE
PxrFractal with PxrRamp cause Error

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#209]
![wz6xu m a0jrbd q54 v g6](https://cloud.githubusercontent.com/assets/15306113/13547623/051f3616-e315-11e5-83bc-191800642146.png)
Node step 

![l2ar1 pmo r 8i9r jab5](https://cloud.githubusercontent.com/assets/15306113/13547617/e587f202-e314-11e5-847f-ecdf2a00d803.png)
Error
PS.: some time blender quit without error message
RMS Version: RMS20.7
Addon version:latest

**Comment by bsavery** [comment]
Can you attach your scene file?  I tried recreating this and the colors
parameter for me is "color[4] colors" [0 0 0 0 0 0 1 1 1 1 1 1]  not
color[3], shouldn't end up with 3 with the code.



On Sat, Mar 5, 2016 at 4:59 AM, MarcoCheng <notifications@github.com> wrote:

> [image: wz6xu m a0jrbd q54 v g6]
> <https://cloud.githubusercontent.com/assets/15306113/13547623/051f3616-e315-11e5-83bc-191800642146.png>
> Node step
>
> [image: l2ar1 pmo r 8i9r jab5]
> <https://cloud.githubusercontent.com/assets/15306113/13547617/e587f202-e314-11e5-847f-ecdf2a00d803.png>
> Error
> PS.: some time blender quit without error message
> RMS Version: RMS20.7
> Addon version:latest
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/209>.
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by MarcoCheng** [comment]
[Texture_BGs.zip](https://github.com/bsavery/PRMan-for-Blender/files/160126/Texture_BGs.zip)

Here's the file

**Comment by bsavery** [comment]
Very weird.  I get the correct result with your file on OSX.  I'll have to
try it out when I'm back at the office and have a windows machine.  One
thing I can think of as a potential workaround is adding another
color/position knot in the ramp.  Should fix it temporarily.

Brian

On Sat, Mar 5, 2016 at 6:29 PM, MarcoCheng <notifications@github.com> wrote:

> Texture_BGs.zip
> <https://github.com/bsavery/PRMan-for-Blender/files/160126/Texture_BGs.zip>
>
> Here's the file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/209#issuecomment-192783446>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
Fixed it!
