### ISSUE TITLE
Should Motion blur be centered around frame time?

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#217]
Currently the motionblur centers around the middle of the frame (i.e blur from 1->2 for frame 1)

Might it make more sense to center it around the frame time?  In this case would be from .5 -> 1.5 for a motion length of 1.  This would match what RenderMan for Maya does and most plates as well.  Also if you turn on motion blur it would match the static render a bit closer.

**Comment by MWY3510** [comment]
Sounds good.
