### ISSUE TITLE
Spotlights are buggy:

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#218]
See scene:
Might be a PRMan issue.

[spotlight.blend.zip](https://github.com/bsavery/PRMan-for-Blender/files/184584/spotlight.blend.zip)

**Comment by MWY3510** [comment]
Brian, I am almost 100% sure that this is a PRMan error. The same rib files that are generated can be tested against 20.7 and no issues exist.

**Comment by bsavery** [comment]
Agreed. I was just logging it here so I can take a look when I have some
time later

On Thursday, March 24, 2016, MWY3510 <notifications@github.com> wrote:

> Brian, I am almost 100% sure that this is a PRMan error. The same rib
> files that are generated can be tested against 20.7 and no issues exist.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/218#issuecomment-200985301>
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
Great. If you have it logged there can we go ahead and close it here then? Just spending some time cleaning out the issues today.

**Comment by bsavery** [comment]
Closed.  Issue with light localization fyi.
