### ISSUE TITLE
I can't enable Plugin

### ISSUE THREAD

**Issue by betalars** [bsavery/PRMan-for-Blender#221]
Since i already read in another post, that there are issues with 2.77, i installed blender 2.76 and tryed to use the RendermanPlugin ... but for some reasons, this appears, when i try to click on the checkbox in the user preferences...
![renderman_issue](https://cloud.githubusercontent.com/assets/18014034/13963581/30c595ea-f066-11e5-920e-94fe3c1f057c.PNG)
I'd be glad, if anyone couldt help me... ^^
This identical issue showed up, when i tryed to enable the plugin with blender 2.77...

**Comment by jdent02** [comment]
It's a Python issue.  Supposedly the Renderman 20.8 release fixes it.

**Comment by jdent02** [comment]
Just tested and the plugin works with Blender 2.77 and Renderman 20.8

**Comment by MWY3510** [comment]
Let us know if the problem still persists after you have Renderman 20.8 installed and restarted your computer (refreshes env variables.)

**Comment by betalars** [comment]
Sorry, i forgot to close the issue...and it was a PEBKAC issue.... Problem exists between keyboard and chair. ^^
