### ISSUE TITLE
Do trace sets work?

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#225]
Subject says it all.  Was trying to have an object not cast a shadow from a particular lamp while still being lit by it.  Tried to use the trace set section of the object parameters but it didn't seem to work.

When I went to add a trace set the options didn't really make sense.  I added three pictures to show what I'm getting:

![trace 1](https://cloud.githubusercontent.com/assets/13521172/14036337/eaec3e4c-f205-11e5-8ed8-471987bdb8e0.PNG)

![trace 2](https://cloud.githubusercontent.com/assets/13521172/14036340/efe49c1e-f205-11e5-9272-543df343a1b1.PNG)

![trace 3](https://cloud.githubusercontent.com/assets/13521172/14036342/f4782ff2-f205-11e5-8cf5-dd456e5789fe.PNG)

There are never any other options in the 'group' dropdown, even with the object assigned to a Blender object group.  It appears that you're supposed to be able to define a list of trace sets somewhere and then select them with this dropdown but I can't find where that is.

**Comment by bsavery** [comment]
Short answer:  no it's not working.  
Couple things though.  First off, you want to put something in the "Don't trace subset" of the light's shadow parameters.  But what you want to put there is the name of the subset.  
Unfortunately the UI for creating new trace subsets by name isn't exposed.  If you could create a new subset name you found the right place to include or not include it.  

However would there be a better way to do this?  We could turn Blender groups into subsets....

**Comment by jdent02** [comment]
Yeah I did find the trace subset section of the light but still no go, even when I entered "No group selected" into the exclude trace set window of the lamp.

Honestly I think the existing system is fine for assigning trace sets and it appears to be more straightforward than object or light groups.  It seems like it would work a bit like the light linking options now.  Maybe it would work to have the trace set creation tool exposed on either the "world" or "scene" tabs.  Luxrender does something similar for creating it's light groups and material volumes.  These light group/volumes are then selectable by dropdown menu in the material options.

In fact.....I don't know how much work it would be for you but maybe you want to do that for all the various grouping options so there's some consistency to it.  Something along the lines of this:

The "Scene" tab has boxes for creating trace sets, light groups, and object groups and assigning them names.  These names are then available via a dropdown menu in the relevant material/object sections.  This would eliminate the possibility of a user typing 'light' in the light group section of a lamp and then using "Light" when they try to set up an LPE in the AOV section and getting a black render.....

**Comment by bsavery** [comment]
Hmmmm, yes that might make sense. Let me think about it a bit more.

**Comment by bsavery** [comment]
Yes I think this is a good idea. In fact I was looking at doing something somewhat related for lights and similar to the light editor in RenderMan for maya.  It could be extended to the object groups / trace sets

**Comment by bsavery** [comment]
<img width="1920" alt="screen shot 2016-03-25 at 8 07 26 pm" src="https://cloud.githubusercontent.com/assets/1892220/14057683/45b964d4-f2c5-11e5-93c1-a6c1788b8d76.png">

Trace groups UI

**Comment by jdent02** [comment]
Looks promising.  So trace sets and holdout groups are basically just object groups with different names?

**Comment by bsavery** [comment]
That's the idea. We could use object groups for both and then in the trace
set or lpe group (holdout) selector give a selection of the existing groups

Same things for light groups I want to make a similar ui but also allow a
few controls for editing lights on a group as a whole:

Change color on a whole group, mute or turn on a whole group, bump up
exposure on a whole group

Stuff that you might want to do on a set of lights at once when lighting.

On Saturday, March 26, 2016, jdent02 <notifications@github.com> wrote:

> Looks promising. So trace sets and holdout groups are basically just
> object groups with different names?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/225#issuecomment-201824582>
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
Light groups getting there:  This allows you to quickly edit all lights params.  I might put a row to edit all at once in the top similar to:
https://renderman.pixar.com/resources/current/RenderMan/lightingPanel.html

<img width="1920" alt="screen shot 2016-03-26 at 2 31 10 pm" src="https://cloud.githubusercontent.com/assets/1892220/14062531/9278ff56-f35f-11e5-935a-33a02028f4bb.png">

**Comment by jdent02** [comment]
That's looking nice.

**Comment by bsavery** [comment]
Really liking this workflow.  I'm also thinking of moving the light linking to here Similar to 

![image](https://cloud.githubusercontent.com/assets/1892220/14185565/4f15c630-f72f-11e5-8c39-ca33c8c066e9.png)

**Comment by jdent02** [comment]
So basically all linking and object/light group creation functions would be in one area?

**Comment by bsavery** [comment]
Yes and you could link by light/light group  ---> object/object group


On Thu, Mar 31, 2016 at 11:40 AM, jdent02 <notifications@github.com> wrote:

> So basically all linking and object/light group creation functions would
> be in one area?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/225#issuecomment-204071200>
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
![screen shot 2016-03-31 at 12 38 17 pm](https://cloud.githubusercontent.com/assets/1892220/14188472/84516a8a-f73d-11e5-96a9-2d1f739d87d6.png)
![screen shot 2016-03-31 at 12 38 27 pm](https://cloud.githubusercontent.com/assets/1892220/14188473/84640636-f73d-11e5-91a7-a367200e5f2b.png)

**Comment by jdent02** [comment]
I see what you're going for.  That's definitely better than typing names into half a dozen scattered parameter boxes......

Looks like a really powerful feature.  Definitely something Cycles does not have.  Great work!

**Comment by bsavery** [comment]
Moar... Icons are just placeholders to indicate there is an existing light link

![screen shot 2016-03-31 at 12 38 27 pm](https://cloud.githubusercontent.com/assets/1892220/14192313/b5ef7686-f751-11e5-8570-743421ecbaa6.png)

**Comment by jdent02** [comment]
Maybe a box underneath that shows a list of all the links that have been created?  Could get ugly if a user created dozens of light links but what are the odds of that?
