### ISSUE TITLE
displacement not working

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#227]
Hi,
Not sure if this is an ID 10 T error or not but I'm almost positive I've used the following node setup to successfully use displacement in the past.  However, as of the latest version I'm getting nothing, even after bumping the scalar scale slider up to 600 and increasing the displacement bounds to 2.

![displace 1](https://cloud.githubusercontent.com/assets/13521172/14062786/f5b02422-f379-11e5-9af3-abff3fe73280.PNG)

![displace 2](https://cloud.githubusercontent.com/assets/13521172/14062789/fc0bd44c-f379-11e5-95e9-129e46a9cb9f.PNG)

**Comment by bsavery** [comment]
Can you attach the scene?

On Saturday, March 26, 2016, jdent02 <notifications@github.com> wrote:

> Hi,
> Not sure if this is an ID 10 T error or not but I'm almost positive I've
> used the following node setup to successfully use displacement in the past.
> However, as of the latest version I'm getting nothing, even after bumping
> the scalar scale slider up to 600 and increasing the displacement bounds to
> 2.
>
> [image: displace 1]
> <https://cloud.githubusercontent.com/assets/13521172/14062786/f5b02422-f379-11e5-9af3-abff3fe73280.PNG>
>
> [image: displace 2]
> <https://cloud.githubusercontent.com/assets/13521172/14062789/fc0bd44c-f379-11e5-95e9-129e46a9cb9f.PNG>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/227>
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
[test file.zip](https://github.com/bsavery/PRMan-for-Blender/files/190687/test.file.zip)

**Comment by jdent02** [comment]
Update, displacement is only broken in preview rendering.  It works fine during the final render.

**Comment by bsavery** [comment]
One line error, trace displacements were off in previews.

**Comment by bsavery** [comment]
Fixed btw
