### ISSUE TITLE
renderman addon not work in official version 2.77 of Blender

### ISSUE THREAD

**Issue by chcamp** [bsavery/PRMan-for-Blender#228]
a belive is problen of python version u can fix this thanks!!!

**Comment by bsavery** [comment]
https://renderman.pixar.com/forum/showthread.php?s=&threadid=30703

**Comment by MWY3510** [comment]
Closed Issue.

**Comment by bsavery** [comment]
Actually I'd like to leave this open in the hope that we don't get 10 more of this same issue in the next week ;) hopefully others will read this before opening a new one.

**Comment by MWY3510** [comment]
Far enough. That makes sense.
