### ISSUE TITLE
Textures and OSL not working properly together

### ISSUE THREAD

**Issue by VanCantus** [bsavery/PRMan-for-Blender#230]
Every time I try to link a newly created PxrTexture to an input of an OSL script node and render the stuff, I get an error like the following:

`Error: PRMan: X00002 {ERROR}   Plugin error: PxrTexture could not open "<filename>.tex" [<Scatter> Object: Cube Shader: <NodeName>]`

where `<filename>` is the prefix of a file, like "image" in "image.png", and `<NodeName>` is the name of the PxrTexture node.

As soon as I link the same texture output to some other node input like the "baseColor" input of a PxrDisney node and render it, everything works correctly. After I've done this, I can relink it to the OSL script node and now it is working fine.

**Comment by VanCantus** [comment]
By the way: I'm using Blender 2.76.

**Comment by bsavery** [comment]
So the texture has to be converted to a .tex file by txmake.  When you put the texture in a PxrTexture node that happens automatically.  You can do that yourself in the command line with the txmake utility and use the .tex filename instead of image.png.  Or I *think* the conversion happens automatically if you pass the texture name as a string input to the osl shader.

**Comment by bsavery** [comment]
i.e     
shader my_shader(string input_color = "image.png"; output color out = 0) {

out = texture(input_color);

}

**Comment by MWY3510** [comment]
Hmm, I will take a look at this. I may not have teased out all the bugs
with OSL nodes.

**Comment by MWY3510** [comment]
Ok I did finally look into this and found that OSL nodes did not allow connected PxrTexture nodes to "make" their textures. This has now been addressed. If you run into any other problems feel free to reopen this issue. Sorry this took so long to address.

**Comment by VanCantus** [comment]
Seems to work so far! Thanks for your awesome work.
