### ISSUE TITLE
PxrMeshenerHair issue

### ISSUE THREAD

**Issue by JeannotLandry** [bsavery/PRMan-for-Blender#232]
[PRManTest.zip](https://github.com/bsavery/PRMan-for-Blender/files/204754/PRManTest.zip)

Here is the scene I am not able to render with the PxrMeshenerHair and a gound, works fine with any other materials (well, I tried simple diffuse and PxrDisney and they both worked fine)

**Comment by bsavery** [comment]
Great!  Thanks taking a look now

**Comment by bsavery** [comment]
I seem like I'm getting the right result or the texture on the fur color at least.  

Can you zip up the C:\Documents\prman_for_blender\PRManTest directory and attach that here?

**Comment by JeannotLandry** [comment]
Here goes. I had to delete the folder and re-render the issue, the file was over 250 megs (probably due to multiple tries) So I re-did and here goes the smaller file. You think it has to do with my computer? Everything is up to date (graphic drivers, windows updates, etc...)
[PRManTest.zip](https://github.com/bsavery/PRMan-for-Blender/files/205027/PRManTest.zip)

Just in case here is my computer spec:
Windows 10 home 64 bits
AMD FX 9590 Octa Core (8 CPUs) 4.7 GHz
24 Gigs Ram
AMD Radeon R9 380 Series (4 Gigs)
Water Cooling System

**Comment by JeannotLandry** [comment]
I'm glad to know that those are there (in the documents folder) because it ends up taking a lot of space after a while. I didn't know that was there and I use a SSD for my windows and the rest is on my other drives. This could easily bring my SSD full. I think I'll clear those as I go (when not having issues).

**Comment by MWY3510** [comment]
JeannotLandry,

Is this still a problem for you? If so can you provide a more detailed explanation of what is going wrong. As with Brian I am able to render your scene without difficulty so I am at a loss as to what your exact issue is.

**Comment by JeannotLandry** [comment]
I'll give it a try again today and let you know.

**Comment by JeannotLandry** [comment]
I'll install the latest addon first :P

**Comment by JeannotLandry** [comment]
It does now render the marschener hair with proper casting shadow on the ground. The hair also works with the textures. However, it starts rendering and doesn't finish rendering, but it says its done rendering (using IT to render at 24 samples, it crashes blender if I use Preview). Here is an image of the issue. I'll also post the files.
![marchenerhairnotfinishingrendering](https://cloud.githubusercontent.com/assets/14031486/14581228/6a08d884-03bd-11e6-9325-542b5245ec69.jpg)

**Comment by JeannotLandry** [comment]
Here is the files, you may have to re-plug the texture as well as quickly recalculate the hair dynamics (very quick since its only a fur ball). I've included the .blend, the texture and the RIB files (under documents/prman_for_blender.
[HairTest.zip](https://github.com/bsavery/PRMan-for-Blender/files/222204/HairTest.zip)

**Comment by JeannotLandry** [comment]
Latest version of the addon was just installed right before that test. I am using Renderman 20.8, I have Windows 10 home 64bits, AMD FX octa core 4.7 GHz, 24 Gigs DDR5 Ram, AMD Radeaon R9 380 4Gigs, 10 TB of HD and a SSD of 250 Gigs for my window. All this with a water cooling system.

**Comment by JeannotLandry** [comment]
I just want to point out that I don't get that Issue if I use other materials than marschener hair. It works fine with PxrDisney, Diffuse and even Glass. It really is just that material that gives me that issue.

**Comment by MWY3510** [comment]
Ok, I think I found the problem. Unfortunately it looks to be a issue with the MarshenerHair plugin or PxrDiffuse plugin as together they causes problems for PRMan when rendering. Currently this only occurs if you have a MarhenerHair material interacting with a PxrDiffuse material. One workaround you can do is to convert any diffuse material elements to PxrDisney materials. Not the ideal solution but it should work. I will report this issue to the relevant persons.

**Comment by JeannotLandry** [comment]
Well, I usually use the PxrDisney material for most of the stuff I do and tweak the settings. I rarely see a scenario where I would actually need a only diffuse material so that works for me. The Marschener Hair on the other hand renders pretty realistic hair/fur compared to PxrDisney. I'll give that a try to see if it really solves it and let you know.

**Comment by MWY3510** [comment]
Also I did some further tests and the problem does not seem to be directly tied to Diffuse. I was mistaken in saying that it only causes problems with Diffuse as I can get Disney to error out also. The main thing is that using a texture on a large number of hairs seems to cause segmentation faults. Sorry but I don't see an easy way to work around this at the moment without not using textures on the hair.

**Comment by JeannotLandry** [comment]
Well, I do use it for grass with hair and disney pixar and it works fine for that ;) I do have a scene I am currently rendering animation which has a lot of hair particles for grass and it rendered it no problem (River post on the forum).

**Comment by JeannotLandry** [comment]
Here is a thought, have you checked the possibility that the issue might be due to the Hair dynamics? That fur ball has dynamics to calculate the hair falling? Currently I get an issue with my render scene of grass (has no dynamics but it has grass animation using a texture) It renders the few first frames and at the fifth frame it stops rendering and gives me a RIB error.

I am not sure if it is related or not, but that isn't allowing me to render the entire animation. At first I was rendering frame 500 to 740 (so a 10 second animation) and it gave me that error. So I shifted my entire animation rendering to frame 700 to 940 and the same thing happened on the 5th frame again.

![rib error on grass animation](https://cloud.githubusercontent.com/assets/14031486/14583417/9215de0a-03f7-11e6-92a3-7b1625da2f3b.jpg)

**Comment by JeannotLandry** [comment]
I have removed the texture to randomise the grass colour and it does the same thing on the fifth frame, it just stops rendering and gives me that error. The thing is there is nothing in my scene that doesn't have a name, there is no Cube.020 like in the error. I'll retry with no grass animation just to see if it'll work!

**Comment by JeannotLandry** [comment]
O crap, its the fluid! The fluid is named fluid in the object tab, but in the mesh tab (little triangle) it is named Cube.020. There is a entire cached simulation of 1440 frames (baked) and that is my error. So I guess there is an issue rendering fluid properly and this really has nothing to do with the same issue!
I should open a different ticket for this, but first I'll try a simpler test scene!

**Comment by bsavery** [comment]
Turn off the localized sampling option in the advanced scene options I think...

**Comment by JeannotLandry** [comment]
I'll give that a try...

**Comment by JeannotLandry** [comment]
that didn't work with the Marscherner hair issue. And I tried with the river scene and it seemed to work, I was able to render 21 frames that way, but at the 21 frame, it did the same error.

**Comment by MWY3510** [comment]
Ok, I did report this and it was logged as a bug. Hopefully this will be resolved. Until that point I will leave this issue open. Thank you for reporting the issue JeannotLandry.

**Comment by JeannotLandry** [comment]
I really think it is the dynamics the issue. I'm currently working on a furry creature (an otter names Otto) and I've quickly created some fur. When dynamics on it does the same thing. However, if I turn it off and comb the fur instead it works just fine. (https://renderman.pixar.com/forum/showthread.php?s=&postid=181881#post181881)
![otto_fur25 clump_0001](https://cloud.githubusercontent.com/assets/14031486/14697991/fd5d632a-075f-11e6-9c0c-c0a5868f0fa9.jpg)

**Comment by JeannotLandry** [comment]
Btw, using Marschener Hair on this, and a PxrDisney for ground.

**Comment by bsavery** [comment]
So can we close this if it's a PRMan issue?  I'll track it on the Pixar side.

**Comment by JeannotLandry** [comment]
That is up to you, it really is just when dynamics for hair/fur is on that it crash. (This is really useful for hair animation and fur animation). Your call ;)

**Comment by bsavery** [comment]
Alright I'll close it here as its not really an issue with the blender addon I think.  I'll reply on forum when we fix.

**Comment by JeannotLandry** [comment]
Well, it works file if using any other material like the PxrDisney, dynamics work fine with that (doesn't look as good as Marschener hair, but it works). So I do think the issue is with the Marschener, not necessarily with the addon nor blender. So yhea, your call ;)

**Comment by bsavery** [comment]
So the issue was with the marschner hair.  It doesn't play well with negative colors in the diffuse color.  Which there are in the texture

**Comment by JeannotLandry** [comment]
What do you mean by negative colors? Anything dark?

**Comment by bsavery** [comment]
If I inspect the texture in "it" some of the pixels have negative values in
the colors.  I.e   -.01, .3, .4 or something in the rgb

On Thu, Jun 2, 2016 at 6:41 AM, JeannotLandry <notifications@github.com>
wrote:

> What do you mean by negative colors? Anything dark?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/232#issuecomment-223294696>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABzffHBqOGYrwerIMmWkqIiX5VvOoiQKks5qHt15gaJpZM4IAKfH>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by JeannotLandry** [comment]
Ok, so anything with a value lower than 50% would be considered negative?

**Comment by JeannotLandry** [comment]
Is there a work around?

**Comment by bsavery** [comment]
Sorry lower than 50%?  No I mean anything with a r G or b channel under 0.

We're fixing marschner hair to clamp colors to 0-1 but if you throw a
pxrclamp node between your texture and hair bxdf that does the same

On Thursday, June 2, 2016, JeannotLandry <notifications@github.com> wrote:

> Ok, so anything with a value lower than 50% would be considered negative?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/232#issuecomment-223317505>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABzffCwf6akkn3wweFIqfwoXe9hBspbGks5qHu7-gaJpZM4IAKfH>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by JeannotLandry** [comment]
Ok, I see what you mean! Cool! I did no knew jpg images or even png could have negative color values, I though only .exr or anything similar (hdri) had that. Learn something everyday!!!
