### ISSUE TITLE
Particle Object Group Instance Crash

### ISSUE THREAD

**Issue by JeannotLandry** [bsavery/PRMan-for-Blender#233]
I am trying to use particles on a tree converted to polygons for leaf and that I use hair or particles to generate the leafs based on a group of leafs it gives me an error and doesn't render. I also tried the renderman render options to use an object (no options for groups here, that would be a nice addition) and it still gives me an error. Give me that error that there is materials or not assigned to the objects. It is as if it doesn't want to render object instances which are awesome to render out leafs and such. Would really be useful for animated trees (which this tree is, has a tree armature with small wind animation). So my intention is to animate that tree, but I can't get the leafs to work with particles which would allow them to follow the branches.

Any idea as to what the error might be?

I added a zip of the folder containing the .blend of the tree with particles setup and textures associated with it. I also copied and pasted the C:document/prmanforblender/TreeTest2 rib files and such in that zip.
[Tree Tests.zip](https://github.com/bsavery/PRMan-for-Blender/files/208984/Tree.Tests.zip)

**Comment by bsavery** [comment]
I'll take a look.

On Thu, Apr 7, 2016 at 11:31 AM, JeannotLandry <notifications@github.com>
wrote:

> I am trying to use particles on a tree converted to polygons for leaf and
> that I use hair or particles to generate the leafs based on a group of
> leafs it gives me an error and doesn't render. I also tried the renderman
> render options to use an object (no options for groups here, that would be
> a nice addition) and it still gives me an error. Give me that error that
> there is materials or not assigned to the objects. It is as if it doesn't
> want to render object instances which are awesome to render out leafs and
> such. Would really be useful for animated trees (which this tree is, has a
> tree armature with small wind animation). So my intention is to animate
> that tree, but I can't get the leafs to work with particles which would
> allow them to follow the branches.
>
> Any idea as to what the error might be?
>
> I added a zip of the folder containing the .blend of the tree with
> particles setup and textures associated with it. I also copied and pasted
> the C:document/prmanforblender/TreeTest2 rib files and such in that zip.
> Tree Tests.zip
> <https://github.com/bsavery/PRMan-for-Blender/files/208984/Tree.Tests.zip>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/233>
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by JeannotLandry** [comment]
Awesome :) For now I have converted the particles to geometry and merged them together into 1 mesh (that won't follow the armature so I've got rid of that too) and that does render. So right now I've played a lot with materials and nodes to get a pretty realistic tree out of this, will post in the forum thread when the 2K render is done.

**Comment by JeannotLandry** [comment]
Any luck on this issue?

**Comment by bsavery** [comment]
Looking right now.

**Comment by bsavery** [comment]
Fixed.

**Comment by bsavery** [comment]
BTW I think the normal way to work around the no object option is to use a make a new object that dupli groups the group that you want to use in the emitter, then reference that object in the emitter
if that makes sense.

**Comment by JeannotLandry** [comment]
Awesome, works like a charm ;)

**Comment by JeannotLandry** [comment]
Now I can use this to animate trees and grass :)

**Comment by bsavery** [comment]
I'm hoping to look more at optimizing the "it" vs render to blender
interaction this weekend.  Doing it to OpenEXR right now is slow


On Fri, Apr 8, 2016 at 12:54 PM, JeannotLandry <notifications@github.com>
wrote:

> Now I can use this to animate trees and grass :)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/233#issuecomment-207576867>
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by JeannotLandry** [comment]
Yhea It seems to render faster than OpenEXR and also seem to be able to handle larger scene. I tried rendering my Maple Meadow in OpenEXR, it said PRMan: Starting Render......... for about 30 mins and crashed. Right now trying with IT, hopefully it'll work, it is a fairly big scene, now over 2.8 million polygons and a few things like Environment Fog (render huger) as well as DoF and real camera option with vignette. With IT, if blender crashes, it should still continue rendering since the Ribs are already all exported.

**Comment by JeannotLandry** [comment]
Well, it seems to be rendering, however, all I see in IT is a black screen (probably due to the denoiser). As long as it is rendering I am happy :P
