### ISSUE TITLE
Standard AOV's

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#234]
I know there are a few of the standard AOV's available through the exporter (normals, Z), but how do you output the other passes that RIS generates?  Passes like color _Pworld, color _depth, float cpuTime, float sampleCount, etc.......?

**Comment by bsavery** [comment]
Here you go:  
[depth_aov.blend.zip](https://github.com/bsavery/PRMan-for-Blender/files/217959/depth_aov.blend.zip)

**Comment by jdent02** [comment]
Thanks Brian!  I had an inkling that was it but I wasn't sure.  Given that the lpe String box can output things other than lpe AOV's maybe it should be relabeled?  

Same thing with the 'holdout object' box in the object properties, given that this box actually controls object groups, not just holdouts.

Sorry, bit of a tangent....... Thanks again.

**Comment by bsavery** [comment]
The holdout box will change to object group for .9.

On Wednesday, April 13, 2016, jdent02 <notifications@github.com> wrote:

> Thanks Brian! I had an inkling that was it but I wasn't sure. Given that
> the lpe String box can output things other than lpe AOV's maybe it should
> be relabeled?
>
> Same thing with the 'holdout object' box in the object properties, given
> that this box actually controls object groups, not just holdouts.
>
> Sorry, bit of a tangent....... Thanks again.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/234#issuecomment-209728307>
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
Awesome.
