### ISSUE TITLE
feature suggestion: multi layer EXR for aov output

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#237]
Might be a 1.0 feature for all I know but I thought I'd ask anyway.  It would be great to have the option to export a multilayer .exr when aov's are used in order to avoid having to juggle multiple files.  It could be another option in the output driver dropdown.

I'm trying to learn Python but from examining the code I don't know anywhere near enough to figure out how to add it on my own.

**Comment by bsavery** [comment]
Sounds good.  Kinda part of a .9 feature...


On Sat, Apr 16, 2016 at 8:03 AM, jdent02 <notifications@github.com> wrote:

> Might be a 1.0 feature for all I know but I thought I'd ask anyway. It
> would be great to have the option to export a multilayer .exr when aov's
> are used in order to avoid having to juggle multiple files. It could be
> another option in the output driver dropdown.
>
> I'm trying to learn Python but from examining the code I don't know
> anywhere near enough to figure out how to add it on my own.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/237>
>



-- 
brian.savery@gmail.com
508-274-8700
