### ISSUE TITLE
Complex Fluid simulation RIB error

### ISSUE THREAD

**Issue by JeannotLandry** [bsavery/PRMan-for-Blender#238]
The fluid is named fluid in the object tab, but in the mesh tab (little triangle) it is named Cube.020. There is a entire cached simulation of 1440 frames (baked) and that is my error. So I guess there is an issue rendering complex fluid simulation properly. I've tried several sequences of frames (500 to 740, 700 to 940, etc...) it does the exact same thing. Might be a memory issue, but I ain't sure. Attached is the image of the issue. The files are too big for here so I'll post them on my GDrive and post a link here for you to download.
![rib error on grass animation](https://cloud.githubusercontent.com/assets/14031486/14584064/05443ca0-040c-11e6-9a0e-b060f2e1aa87.jpg)

**Comment by JeannotLandry** [comment]
Link to the RIB file 135 megs
https://drive.google.com/open?id=0B57v0HTtegvSWG9XSkhRUmhGTG8

**Comment by JeannotLandry** [comment]
The actual files for the scene are 13 gigs, so it'll take a little white to upload. (Baking yourself the simulation would take roughly 6hrs, so I've included in there)

**Comment by JeannotLandry** [comment]
Actually, I'll let you guys re-simulate if you are welling to test it. This is too big of a file. I'll include everything but the cache simulation...

**Comment by JeannotLandry** [comment]
Here is the link to the .blend with the textures. You can re simulate the fluid (let me know if you don't know how :P ) but you don't have to do a 60 second simulation, I am sure a 30 second sim would work fine to get this issue to pop again. This scene has a lot of elements (some are on the btm layer and you might need them visible to get the simulation to work, perhaps even on the same layer, moved them there after the simulation so it would be in the way in the viewport, but that shouldn't change anything because I did the same thing with a simpler test that worked, video in the forum thread)

https://drive.google.com/open?id=0B57v0HTtegvSZGFJOWxxd3RVcVU

**Comment by JeannotLandry** [comment]
And I tried with Light Localise Sampling off and it seemed to work, I was able to render 21 frames that way, but at the 21 frame, it did the same error. I even re baked the entire thing at lower resolution, but still the same issue.

**Comment by JeannotLandry** [comment]
I've restarted the rendering from the frame it stopped at, and it is rendering, however that single frame has no river but the others that follows have. So I'll still put the animation together with that 1 missing frame (hopefully it will be the only missing river frame). I still consider this as a bug since I've basically recalculated the animation cache and this shouldn't happen (calculated 30 seconds, so frame 1 to 720, took 2 hours to calculate. There is no frames missing in the cache files, I really have no clue what Is causing this.

**Comment by JeannotLandry** [comment]
So I've been trying to render from frame 480 to 720 (so I get a 10 second animation) at a lower cached simulations. It rendered really well frame 480 to 500, 501 the river is blank and it stopped. So I restarted the render from frame 501, it remained blank but went on forward with the rendering. Frames 502 to frame 521 renderer really well, but frame 522 did the same thing, no river and render stops. So now I've restarted the rendering from frame 522 and it is going, frame 522 is still blank as well. SO my guess is that I'll have a few frames to remove off the animation, but it sort of work. Some frames don't and this is where I get those RIB error, even though the geometry is there for some reasons it see those frames as empty.

**Comment by JeannotLandry** [comment]
More and more frames are missing the river fluid sim. I really have no clue as what can actually cause this. I will put this test aside since there is obviously something weird going here (definitely bug).

**Comment by bsavery** [comment]
I'll take a look at the rib gen and see if there's an issue.

**Comment by bsavery** [comment]
How do I redo the sim?

**Comment by JeannotLandry** [comment]
Select the fluid object (big long cube) and go to the Physics tab, then set the end frame to like 30 (that takes seconds) so that would be 720 frames. and click on bake.
![fluidsim](https://cloud.githubusercontent.com/assets/14031486/14769248/89ffe3c0-0a2b-11e6-9454-32b31d6c9d61.jpg)
