### ISSUE TITLE
Links from and to OSL nodes disappear after reopening Blender

### ISSUE THREAD

**Issue by VanCantus** [bsavery/PRMan-for-Blender#241]
Each time, I save a scene with OSL nodes, close Blender and reopen it, all links from and to the OSL nodes disappear.

This bug does only appear at closing and reopening Blender and not if I for example revert the scene or open another scene and then reopen the scene with the OSL nodes.

**Comment by MWY3510** [comment]
Ok, I did fix this for the next release. I will leave this issue active until 0.9 is done.

**Comment by MWY3510** [comment]
Actually this has been tested enough that I am confident in closing the issue. It still won't be in master until 0.9 release though.

**Comment by VanCantus** [comment]
Thanks a lot. Great job!
