### ISSUE TITLE
Image sequence for texture not working

### ISSUE THREAD

**Issue by JeannotLandry** [bsavery/PRMan-for-Blender#242]
To play an image sequence for texture I have to input: //cache_ocean\foam_$f4.exr (I tried with F4 but it didn't work, it worked with f4 but only the first frame)

Here is the error it gives me. It renders the first frame no trouble with the foam, second frame appears with no foam and once the render is done I get this error:

![texfilenotfound](https://cloud.githubusercontent.com/assets/14031486/14641823/6a8d851c-061e-11e6-8f98-8c8bb2589e05.jpg)

**Comment by bsavery** [comment]
Fixed.  Sorry we were converting the F4 in the input file when txmaking, not the output.  Incidently you can use either $f4 or $F4 its just one worked for you because it was cached.

**Comment by JeannotLandry** [comment]
Ok, I'll test that ;)

**Comment by JeannotLandry** [comment]
Seems to be working, I'll let the full 24 frames of animation render and I'll post if there is still issues, but so far, the 3 first frames rendered it ;)

**Comment by JeannotLandry** [comment]
Yup, definitely working ;) Awesome work Brian!

**Comment by JeannotLandry** [comment]
Awesome, worked flawlessly :) Added a video of this working on the forum
https://renderman.pixar.com/forum/showthread.php?s=&postid=182048#post182048
