### ISSUE TITLE
if install python3.5 with add python to path setting. get ImportError: No module named 'prman'

### ISSUE THREAD

**Issue by kokutoukiritsugu** [bsavery/PRMan-for-Blender#243]
Install python3.5 with add python to path setting.
Now has 2 environment:
C:\Users\litel\AppData\Local\Programs\Python\Python35-32\Scripts\
C:\Users\litel\AppData\Local\Programs\Python\Python35-32\

Now install prman-for-blender plugins, Will get ImportError: No module named 'prman' error.

If temporary delete that 2 environment. Install has no broblem. and now add 2 environment back. Plugins still works fine.

This little bad user experience can be fix?

**Comment by bsavery** [comment]
I'm assuming from that path above you have 32 bit version?  RenderMan is only 64 bit compatible.

**Comment by bsavery** [comment]
Was that the issue?

**Comment by kokutoukiritsugu** [comment]
![20160425002729](https://cloud.githubusercontent.com/assets/5471433/14768773/994415ac-0a7d-11e6-963c-12b95d0cf4f5.jpg)
python install setting.
enable add python to path.

now see environment:
![20160425003431](https://cloud.githubusercontent.com/assets/5471433/14768778/b00072f4-0a7d-11e6-99a8-8417f0b9fe90.jpg)

now install plugin will get error message.

=============

if delete the 2 line environment, install plugin ok.
Now add 2 line environment back, plugin work no problem.

this only effect when plugin install step.

is can be fix?

**Comment by kokutoukiritsugu** [comment]
my english not good, soo sorry.

**Comment by bsavery** [comment]
No that's fine.  I understand.

Based on this path used:
C:\Users\litel\AppData\Local\Programs\Python\Python35-*32*\

This seems to imply you're using a 32 bit version of blender or python.
Renderman only works on 64 bit.

On Sun, Apr 24, 2016 at 9:39 AM, kokutoukiritsugu <notifications@github.com>
wrote:

> my english not good, soo sorry.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/243#issuecomment-213997766>
>



-- 
brian.savery@gmail.com
508-274-8700
