### ISSUE TITLE
How to use Blender vertex color channel as Renderman material color / texture?

### ISSUE THREAD

**Issue by MetinSeven** [bsavery/PRMan-for-Blender#247]
Hi,

Thanks for creating and improving your great bridge between Blender and Renderman, much appreciated.

I'm wondering how I can display vertex colors on my rendered meshes. I've connected the resultRGB output of a PxrPrimvar node to the baseColor input of a PxrDisney material, changed the Variable Type dropdown entry to 'color', and entered 'Col' (default Blender vertex color channel name) in the Variable Name field. This is more or less how you would connect an Attribute node to a Cycles material, indicating 'Col' as the attribute name.

But no matter what I've tried to adjust in the PxrPrimvar node so far, the mesh surface remains black in my Renderman IT rendering.

Many thanks in advance for your help.

**Comment by jdent02** [comment]
Looks like the default vertex color is called Cs according to the tooltip in the mesh options panel.  Try entering that in the PxrPrimvar.

**Comment by MetinSeven** [comment]
It works, great! Muchas gracias!
