### ISSUE TITLE
F8  ( Blender's global addon reload shortcut ) : ValueError: register_class(....): already registered as subclass

### ISSUE THREAD

**Issue by zeffii** [bsavery/PRMan-for-Blender#25]
```
Exception in module register(): '(....)/scripts/addons_contrib/PRMan/__init__.py'
Traceback (most recent call last):
  File "(....)/scripts/modules/addon_utils.py", line 328, in enable
    mod.register()
  File "(....)/scripts/addons_contrib/PRMan/__init__.py", line 90, in register
    properties.register()
  File "(....)/scripts/addons_contrib/PRMan/properties.py", line 1458, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass
```

**Comment by zeffii** [comment]
if this has been fixed already, please close it - i'll git pull

**Comment by bsavery** [comment]
This seems to work fine for me on OSX.

**Comment by zeffii** [comment]
I just downloaded and tried Master, and still get that Traceback, if I hit F8 with PRman enabled. Maybe it's ubuntu only.

The unregister() function in `properties.py`,  does suggest that you aren't unregistering the `bpy.types`, and when F8 tries to call unregister, then register, they exist already.

**Comment by bsavery** [comment]
Ok, I'll try it on linux.

**Comment by zeffii** [comment]
hmm, it looks like the problem happens earlier . In properties.py 's register you register each item in `classes`, but in the unregister  you just call `bpy.utils.unregister_module(__name__)` which I don't think does the same thing (or at least not what we expect).

**Comment by bsavery** [comment]
Yeah that would do it.  Hmmm I'll have to fix that correctly because there are some classes that are registered dyamically and will have to be unregistered.  Thanks for the tip!  Unless you want to tackle the code change.

**Comment by zeffii** [comment]
```python
def unregister():
    bpy.utils.unregister_module(__name__)

    for cls in classes:
        bpy.utils.unregister_class(cls)
```
That supressed the traceback, and shows that nodes.py also needs attention for the same thing

**Comment by bsavery** [comment]
Yep.

**Comment by zeffii** [comment]
I think creating properties just overwrites existing ones with the same name,  but _classes_ need to explicitly unregistered first before trying to (re)register them.

**Comment by zeffii** [comment]
I'm surprised you don't get that traceback on OSX.

**Comment by bsavery** [comment]
Ah you know what I do, just f8 wasn't doing the same thing.  If I explicitedly unload then load the addon you get it.  

Sorry still before 8 here.

**Comment by zeffii** [comment]
properties.py

```python
def unregister():
    nodeitems_utils.unregister_node_categories("RENDERMANSHADERNODES")
    #bpy.utils.unregister_module(__name__)

    bpy.utils.unregister_class(RendermanShaderSocket)    
    bpy.utils.unregister_class(RendermanNodeSocketColor)  
    bpy.utils.unregister_class(RendermanNodeSocketFloat)  
    bpy.utils.unregister_class(RendermanNodeSocketInt)   
    bpy.utils.unregister_class(RendermanNodeSocketString)
    bpy.utils.unregister_class(RendermanNodeSocketVector)     
```

**Comment by zeffii** [comment]
that also suppresses the final traceback for duplicated class registration. -- so putting them in a list and iterating over them would also work, (like in properties.py )

**Comment by zeffii** [comment]
OK. can close this then it's a simple fix.

**Comment by bsavery** [comment]
that should be in nodes.py no?

**Comment by zeffii** [comment]
(Yes, i corrected that) refresh :)

**Comment by bsavery** [comment]
Do you want to pull request the change or should I just do it?

**Comment by zeffii** [comment]
I can't PR now : /

**Comment by zeffii** [comment]
well, not using the web interface.. so if you do see a PR ignore it for a bit

**Comment by zeffii** [comment]
: / I didn't manage to merge pull requests done with web interface, will wait till later!
