### ISSUE TITLE
Blender crashes on undo during active interactive rendering

### ISSUE THREAD

**Issue by hilburger** [bsavery/PRMan-for-Blender#254]
Each time I activate the interactive rendering the it windows opens and renders just fine, so far so good. 
But at any time I try an undo (ctrl+z) in the 3d viewer it crashes instantly. 

Blender: 2.77a
RenderMan 20.0 integration: 0.8.0 (downloaded last night from git)
RenderMan NC: 20.9
it: 20.9
Windows 8.1
nVidia GTX 980 with latest drivers

**Comment by bsavery** [comment]
The undo WHILE interactive rendering?


On Thu, May 5, 2016 at 5:05 AM, hilburger <notifications@github.com> wrote:

> Each time I activate the interactive rendering the it windows opens and
> renders just fine, so far so good.
> But at any time I try an undo (ctrl+z) in the 3d viewer it crashes
> instantly.
>
> Blender: 2.77a
> RenderMan 20.0 integration: 0.8.0 (downloaded last night from git)
> RenderMan NC: 20.9
> it: 20.9
> Windows 8.1
> nVidia GTX 980 with latest drivers
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/254>
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by hilburger** [comment]
No, I thought that, too at first sight. But it happens without anything being rendered.

**Comment by bsavery** [comment]
Hmmm so I can't get it to crash when undo-ing. Is there something else
you're doing here?

Can you get a screencast maybe?


On Thu, May 5, 2016 at 11:33 AM, hilburger <notifications@github.com> wrote:

> No, I thought that, too at first sight. But it happens without anything
> being rendered.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/254#issuecomment-217235905>
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by hilburger** [comment]
I'll try to finish one after this project around the week-end :)

**Comment by bsavery** [comment]
Ok great thanks.  Sorry I can't seem to recreate this problem and need a
bit more info.

On Thu, May 5, 2016 at 4:21 PM, hilburger <notifications@github.com> wrote:

> I'll try to finish one after this project around the week-end :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/254#issuecomment-217307832>
>



-- 
brian.savery@gmail.com
508-274-8700
