### ISSUE TITLE
Interactive Rendering crashes Blender

### ISSUE THREAD

**Issue by rendermouse** [bsavery/PRMan-for-Blender#26]
Windows 7, Blender 2.75a, Intel Graphics chipset (laptop, latest drivers)

Steps to reproduce:
1. Load Blender 2.75a, open scene file.
2. Click 'Start/Stop Interactive Rendering' in the 'Interactive and Preview Sampling' menu.

Blender locks up.  Console output shows the following:

![image](https://cloud.githubusercontent.com/assets/1102555/8689601/c41dc6e2-2a77-11e5-9c23-2f49dbfcc62a.png)

The scene renders fine via PRMan, just not with IR.

**Comment by bsavery** [comment]
Fixed windows 'it' path issues.
