### ISSUE TITLE
Can't select node tree from the node editor

### ISSUE THREAD

**Issue by nuzzar** [bsavery/PRMan-for-Blender#266]
Hi I can't seem to select/update the node tree from the node editor's drop down list. Is this a bug?

I can update the node editor to the active node tree by selecting the object directly as expected. However, because of the above issue I can't seem to find a way to update the node editor with the 'world' node tree--since it is not selectable. Is there any workaround to solve this issue temporarily? By manually updating it through python for instance.

OS: Ubuntu
GPU: Intel HD 4000

Thanks

**Comment by MWY3510** [comment]
Good day blendtsukai,

Unfortunately this is a known bug which does not have an easy fix #143 . You can edit other materials if you first pin the node tree. This will allow any material to be accessed and modified. Just note that as soon as you unpin you will return to the original material. Also you can modify world light settings by creating your own light object and setting it to an environment light as an alternative.

Hope that helps some,
Ryan

**Comment by blendtsukai** [comment]
I see. Thanks for the tips.

**Comment by bsavery** [comment]
This is fixed in 21
