### ISSUE TITLE
blender crashes when trying to render

### ISSUE THREAD

**Issue by michal1000w** [bsavery/PRMan-for-Blender#268]
I've got blender 2.77, renderman proserver 20.9 and PRMan plugin. My computer is running on Windows 10 64bit, 16gb ram, intel core i5 and Nvidia GTX 960.
When I'm trying to render, blender crashes. The same thing is when I'm trying to make material preview.

**Comment by bsavery** [comment]
What's the error

On Sunday, May 29, 2016, michal1000w <notifications@github.com> wrote:

> I've got blender 2.77, renderman proserver 20.9 and PRMan plugin. My
> computer is running on Windows 10 64bit, 16gb ram, intel core i5 and Nvidia
> GTX 960.
> When I'm trying to render, blender crashes. The same thing is when I'm
> trying to make material preview.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/268>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABzffCGrqEIiXyYGcR9UAvlpmoEvDwBdks5qGaPsgaJpZM4IpTWc>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by michal1000w** [comment]
There is no error. Just blender is closing, without any message.

**Comment by michal1000w** [comment]
[Desktop 05.29.2016 - 16.46.29.01.zip](https://github.com/bsavery/PRMan-for-Blender/files/288387/Desktop.05.29.2016.-.16.46.29.01.zip)
There is a video.

**Comment by bsavery** [comment]
Hmmm, that's not a lot of info!  Can you start Blender from the command line?  Or try the devel branch:

https://github.com/bsavery/PRMan-for-Blender/tree/devel

**Comment by michal1000w** [comment]
Thanks a lot! Now it's working fine. I used devel branch.
