### ISSUE TITLE
OSL workflow

### ISSUE THREAD

**Issue by bloodboy** [bsavery/PRMan-for-Blender#270]

**Comment by bloodboy** [comment]
anyone in here has given the PxrOsl patter a go... 
i am playing around with it but no luck... the shaders work in cycles... but not in RM... i am using the .oso from blender/cycles compile but still no luck... any tips would be great... 
thanks

**Comment by bsavery** [comment]
Osl patterns should work fine.  As long as they don't have closures in
them, closures are not supported in PRMan as Bxdf's do the same thing.

On Mon, May 30, 2016 at 3:30 AM, bloodboy <notifications@github.com> wrote:

> anyone in here has given the PxrOsl patter a go...
> i am playing around with it but no luck... the shaders work in cycles...
> but not in RM... i am using the .oso from blender/cycles compile but still
> no luck... any tips would be great...
> thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/270#issuecomment-222463368>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABzffEqo6kky7Q3dhdPDhxY8D1A97kyWks5qGrw2gaJpZM4IprlL>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
I'm going to go ahead and close this since there has not been any activity.
