### ISSUE TITLE
Can't activate addon in blender 2.77a and renderman 20.9 

### ISSUE THREAD

**Issue by Johannesfknudsen** [bsavery/PRMan-for-Blender#276]
The tilte says it all but here is a error log:

Traceback (most recent call last):
  File "D:\Program Files\Steam\steamapps\common\Blender\2.77\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\johan\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender\__init__.py", line 38, in <module>
    from . import engine
  File "C:\Users\johan\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender\engine.py", line 70, in <module>
    import prman
ImportError: No module named 'prman'

Can you help me?

Thanks in advance!!

**Comment by bsavery** [comment]
Where do you have RenderMan installed?  And what is the RMANTREE setting in
your environment variables.

On Mon, Jun 6, 2016 at 10:28 AM, Johannes Farmer Knudsen <
notifications@github.com> wrote:

> The tilte says it all but here is a error log:
>
> Traceback (most recent call last):
> File "D:\Program
> Files\Steam\steamapps\common\Blender\2.77\scripts\modules\addon_utils.py",
> line 330, in enable
> mod = *import*(module_name)
> File "C:\Users\johan\AppData\Roaming\Blender
> Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender__init__.py", line
> 38, in
> from . import engine
> File "C:\Users\johan\AppData\Roaming\Blender
> Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender\engine.py", line
> 70, in
> import prman
> ImportError: No module named 'prman'
>
> Can you help me?
>
> Thanks in advance!!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/276>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABzffK6owUyc5llIDZHwXlSUjXDJJ8Vyks5qJFi_gaJpZM4IvIIy>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by Johannesfknudsen** [comment]
Renderman is install on "C:\Program Files\Pixar\RenderManProServer-20.9", and the environment variable is on "C:\Program Files\Pixar\RenderManProServer-20.9"

**Comment by bsavery** [comment]
Hmmmmm... that should work then.  Only other thing I can think of is if you have a 32 bit version of blender?  Or you can try the devel branch we changed the way renderman is found.
