### ISSUE TITLE
Pxr physical camera fov doesn't match Blender's camera settings

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#277]
https://renderman.pixar.com/forum/showthread.php?s=&threadid=30749

This thread is a bit rambling but the basic problem is the Pxr physical camera FOV doesn't match the numbers that Blender shows in it's own camera parameters, even with the Blender camera sensor fit set to 'vertical' and the lens display set to 'field of view'.  The only way to properly match it up is to export a RIB file with the 'normal' camera and then copy that FOV number into the Pxr physical camera setting.  

I tweaked the camera export to make the Pxr physical camera draw it's FOV from the same place the 'normal' Renderman camera does, but due to the methods the exporter uses to populate the Pxr physical camera parameters I can't remove its FOV entry.  Right now it doesn't do anything, but it looks kinda sloppy to have it still visible.

**Comment by bsavery** [comment]
Yeah, I think the way to do it is just not show the FOV value on phsyical camera, and pull it from the camera instead.

**Comment by jdent02** [comment]
I found out how to remove the FOV setting from the pxr physical camera so I'm just doing some testing to make sure it works right.

**Comment by jdent02** [comment]
Just posted a pull for this.  I'll close the issue.
