### ISSUE TITLE
Possible checkpoint/recovery workflow

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#282]
Note: The checkpoint options only appear when 'local render' is selected.  These options add the -checkpoint and -recover command line arguments to the string that launches the background render process.  Nothing is added to the .rib files (which is why the options are not there when 'Generate rib files only' is selected).  This made the most sense to me from a management standpoint.  Let me know what you think......
![checkpoint snippett](https://cloud.githubusercontent.com/assets/13521172/16057693/d771ea26-3240-11e6-90df-b7539a2bb003.PNG)

**Comment by bsavery** [comment]
Only local renders?  have you had any thought on doing them on tractor?

**Comment by bsavery** [comment]
You'd add it to the tractor job command.

**Comment by jdent02** [comment]
I'm not familiar with Tractor so I hadn't looked at that.  I'll check it out!

**Comment by jdent02** [comment]
I'll add it into the command line in the spool module.  I don't have Tractor though so I can't test it.....

**Comment by bsavery** [comment]
Ok.  Main thing is to look at the command that comes out in the spool.alf
file.


On Tue, Jun 14, 2016 at 2:29 PM, Jon D <notifications@github.com> wrote:

> I'll add it into the command line in the spool module. I don't have
> Tractor though so I can't test it.....
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/282#issuecomment-226022140>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABzffOdmB0-9G0bbk7DKylRSxXL2AhlAks5qLx1FgaJpZM4I1tJJ>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
I put some code into the spool module but it looks only partially finished so it's anybody's guess on whether it will work.  It does work for local rendering (Lightyear and myself tested it out).  Recovery has some odd behavior though (you can only have one rib per command string), so I'm removing that checkbox.  If someone wants to use recovery, they'll have to render through the command line.

**Comment by jdent02** [comment]
I looked over the spool module and I added in some code where I thought it was appropriate but the module isn't in a functional state so it doesn't output an .alf file that I can look at.....

**Comment by jdent02** [comment]
I'm gonna close this one.  I'll add in the recovery option to Tractor/Localqueue spooling when I get some time.
