### ISSUE TITLE
Unable to load addon: Blender v 2.68a Win 7 sp1 x64

### ISSUE THREAD

**Issue by rbates27** [bsavery/PRMan-for-Blender#29]
First some background: Originally, PRMan failed to load b/c it couldn't find an RMSTREE.  I did not originally install a PRMan20 Studio client since I don't have Maya.  I re-installed and told it to install the Maya 2016 PRManStudio and that resolved the first error I was getting.

Now I'm stuck; it fails to import the prman_for_python_3 .pyd.  It's unclear to me why..????   Here is the stack I'm seeing:

![image](https://cloud.githubusercontent.com/assets/5639361/8707552/6cd7a88e-2b04-11e5-96ea-e54137164c93.png)

**Comment by bsavery** [comment]
I fixed the bug where it was failing to load for not having RMSTREE.  In fact you shouldn't have to set that.

For the above issue.  Do you have RMANTREE variable set and RenderMan Pro Server installed?

**Comment by bsavery** [comment]
Also do you have your pythonpath variable set to something?

**Comment by rbates27** [comment]
Yeah...I saw your recent change to fix the RMSTREE issue :-)

RMANTREE is set to C:\Program Files\Pixar\RenderManProServer-20.0\  (which is correct install location)

I didn't have an environment variable for pythonpath.  So I created one and set it to %RMANTREE%bin\

**Comment by bsavery** [comment]
Just to be clear you don't HAVE to set either of those variables, It should find them on their own as long as they're installed in the normal place.  Are you still getting the error?  

I think this might be a python version issue.  What python version does 2.68 have? I haven't tested with that, only 2.74+.  You can find that by running the help->system info menu

**Comment by ohsnapitsjoel** [comment]
Blender 2.68 used Python 3.3, if I remember correctly.  It switched to Python 3.4 around 2.72 or so.

**Comment by rbates27** [comment]
Yes.  That's what I'm seeing.  2.68 is using Python 3.3

**Comment by bsavery** [comment]
Well then... I'd guess the prman_for_python module would not load then.  It's compiled against 3.4 python.  The blender version in the bl_info of the addon doesn't limit where you can load the addon?

**Comment by rbates27** [comment]
Just downloading latest 2.75 release and will retry.

**Comment by ohsnapitsjoel** [comment]
Nope unfortunately, it's basically a reference for the user to tell them which Blender version it was developed for and tested against.

**Comment by rbates27** [comment]
Working in 2.75 as expected.
