### ISSUE TITLE
Node keyframes not showing in dope sheet

### ISSUE THREAD

**Issue by Mouldfish** [bsavery/PRMan-for-Blender#292]
I tried to add keyframes to node parameters but they do not appear in the dope sheet or graph editor.

Is this a known issue?

**Comment by jdent02** [comment]
Yes.  RGordon had a workaround that involved adding a driver to the parameter, but I can't remember where it was posted.....

**Comment by jdent02** [comment]
Brian, this one might be fixed with the change to using the Cycles node graph.....

**Comment by MWY3510** [comment]
This issue has indeed been resolved by Brian moving to Cycles nodetrees. This issue will probably still persist for versions <21. Anyway I am going to close this since it works for all current versions.
