### ISSUE TITLE
Error when installing devel branch

### ISSUE THREAD

**Issue by afecelis** [bsavery/PRMan-for-Blender#293]
Master installs and can be checked fine. Devel installs but when checking the tick box to enable it the following error is displayed:
![devel_branch_err](https://cloud.githubusercontent.com/assets/3821786/16357015/33a59b72-3ab0-11e6-94f2-a932c5e0318d.jpg)

**Comment by bsavery** [comment]
So we changed the way that the RMANTREE setting is set in the addon preferences for the devel branch.  What do you have set there?

**Comment by bsavery** [comment]
I think we should be using the new "PrintToInfo" operator to report setup issues btw here.

**Comment by afecelis** [comment]
Hi Brian,

I'm attaching 2 pictures of the 2 branches in blender. 01_master shows it
installs everything by default according to the installation folder, and I
guess using the environment variables it sets in windows. 02_devel is as
far as I can get with this version, I can select the zip file but as soon
as I check the tick box to enable it I get the long error I posted, so no
way to set RMANTREE  :(

I'm using the master version for now, but I was loving the things/menus
implemented in the devel version and I truly hope it becomes master soon.

Thanks a lot for supporting blender and for the time and effort you're
putting into it.

regards,

Alvaro

**Comment by bsavery** [comment]
Didn't get the attachments.

**Comment by afecelis** [comment]
That's weird, they show up ok in sent mail. Do you mean they must be
attached at github's bug report thread?

I'm attaching them again.

Please let me know if you receive them OK this time.  :D

regards,
Alvaro

**Comment by bsavery** [comment]
Yeah I think they have to be attached on github

**Comment by afecelis** [comment]
ughhhh sorryyyy  I was attaching them here.

**Comment by afecelis** [comment]
![01_master](https://cloud.githubusercontent.com/assets/3821786/16431404/0a164f8e-3d46-11e6-806c-ef74674dcf38.jpg)

![02_devel](https://cloud.githubusercontent.com/assets/3821786/16431413/116ebf78-3d46-11e6-98dd-94e069d3e7ba.jpg)

**Comment by bsavery** [comment]
I'm working to make the error reporting better.  In the meantime what do you get in the console window?  Which you can access through Help » Toggle System Console on windows

https://wiki.blender.org/index.php/User:Fade/Doc:2.6/Manual/Interface/Window_system/Console_window

**Comment by bsavery** [comment]
Also I updated the devel branch to at least get you to the preferences to fix the errror!
