### ISSUE TITLE
20.10?

### ISSUE THREAD

**Issue by lumpynose** [bsavery/PRMan-for-Blender#299]
I just downloaded renderman from pixar and it's version 20.10.  I created a simple scene with an icosphere, gave it a subsurf modifier, view and render at 2 subdivisions, gave it a color using the default material, then rendered it.  Then I added a torus, clicked on the material tab's button to change its color, but when I click on the New button blender's window disappears (I'm assuming something crashed).

Windows 10, 64 bit, blender 2.77.

**Comment by bsavery** [comment]
Was there any error in the blender info window?

**Comment by lumpynose** [comment]
I'm not sure what you mean by info window.  I toggled the blender console
window but it disappears at the same time blender does.  Something in all
caps did show up just before everything disappeared.  The subdivision surf
modifier isn't needed to make it do this; apparently doing a render and
then adding a new object and then clicking on New in the material tab is
what does it.  I can add 2 objects and add materials without a problem, but
if I render (F12) then do F11, then add an object and try to add a material
then blender exits.

**Comment by bsavery** [comment]
Hmmm I can't recreate this.  If you drag down from the top bar you get the info window.  If you can print any errors from there as you go along that could help

http://annex2nothing.com/wp-content/uploads/2012/12/03_infowindow.jpg

**Comment by lumpynose** [comment]
The whole blender window disappears a fraction of a second after I click on
the New button so I don't get the opportunity to see what message is
showing.

**Comment by bsavery** [comment]
Sorry if I'm not being clear.  If you open that at the beginning of your session and look for an errors that come by BEFORE hitting the new button that would be useful.

**Comment by lumpynose** [comment]
Nope; the last message is that I added the torus.  There are some green
lines but they're not errors.

**Comment by lumpynose** [comment]
If I upload my .blend file somewhere will that also have my user preferences?  Maybe I have something set that's causing it.

**Comment by bsavery** [comment]
Hmmmm. And the first render happens fine?  Sorry for the problem. I can't
seem to recreate this here. What is the plugin settings in user
preferences?  Is there anyway you could get me more info like a crash
report?

On Wednesday, July 13, 2016, Rusty Wright <notifications@github.com> wrote:

> Nope; the last message is that I added the torus. There are some green
> lines but they're not errors.
>
> On Wed, Jul 13, 2016 at 5:54 PM, bsavery <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Sorry if I'm not being clear. If you open that at the beginning of your
> > session and look for an errors that come by BEFORE hitting the new button
> > that would be useful.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/bsavery/PRMan-for-Blender/issues/299#issuecomment-232528378
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAA4igwjiOVYaLNBSCC2NfMaDl8FBjhkks5qVYjKgaJpZM4JL-UJ
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/299#issuecomment-232529156>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABzffP7l5hg3-G7mQuofK8vNQgzalW7Qks5qVYohgaJpZM4JL-UJ>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by lumpynose** [comment]
In case they might help here are the 2 files startup.blend and userpref.blend from the blender config folder (C:\Users\lumpy\AppData\Roaming\Blender Foundation\Blender\2.77\config)

[lumpy.zip](https://github.com/bsavery/PRMan-for-Blender/files/362840/lumpy.zip)

**Comment by lumpynose** [comment]
How do I generate a crash report?  Is there some way I can toggle logging the blender console output?

**Comment by lumpynose** [comment]
Yes, first render is fine.  I don't even need to add a material, but after
I render and add the 2nd object adding a material to it causes the silent
exit.

**Comment by jdent02** [comment]
Hi lumpynose.  Can you launch Blender from a cmd window?  That way any errors that are generated will still be visible after the crash.

Go to the folder where you keep your Blender application.  Make sure no files are selected.  Shift-right click on a blank area of the window and select 'open command window here'.  In the cmd screen type 'blender.exe' and hit enter.  That will launch Blender.  When it crashes you should be able to see any errors in the command screen.

**Comment by lumpynose** [comment]
Yes, that fixes it.  Thanks!

Now to recreate my startup file...

**Comment by jdent02** [comment]
Good luck!  I've had similar things happen before where my files all of a sudden caused errors when rendering with plugins (Luxrender in particular).  I think it has something to do with Blender's render API.  Unfortunately, that's not something Brian can easily fix :+1:

**Comment by lumpynose** [comment]
Ok, thanks.  It's unfortunate that there isn't some better logging
mechanism in blender that can be turned on and off, with different levels
(debug, warning, error, etc.)

**Comment by bsavery** [comment]
There is, you just have to launch it from the command line with --debug I believe.

**Comment by lumpynose** [comment]
Ah; thanks.  That's good to know.  Except that I'll probably forget by the
time I need it next. ;-)

**Comment by lumpynose** [comment]
It happened again; I uninstalled renderman, not the plugin, believing the announcement for the new version applied to the free version.  When I tried it it did the same thing; silent exit when I tried to add a new material.  No idea what's causing it.

**Comment by bsavery** [comment]
So here's what's going on... the "RenderEngine" basically the bit that Blender intantiates when it start a render never gets deleted with your file.  Why?  I'm not sure yet.  But it's mostly why this is happening.

**Comment by bsavery** [comment]
It might actually be a blender bug

**Comment by bsavery** [comment]
Alright.  Well I fixed it either way on our end.  Try the latest code

**Comment by lumpynose** [comment]
Ok, looks good.  No silent exit on material selection.
