### ISSUE TITLE
Option to hide "PRMan Interactive Mode Running, do not..."

### ISSUE THREAD

**Issue by Lightye** [bsavery/PRMan-for-Blender#302]
...because it is not needed here and grabs much attention. 

![skarmavbild 2016-07-14 kl 23 02 56](https://cloud.githubusercontent.com/assets/14073317/16855840/eb0b1b10-4a1f-11e6-8d1e-d3b26aeba4e6.png)

Thanks!

**Comment by bsavery** [comment]
That should be an easy fix.

**Comment by MWY3510** [comment]
Feature is now in master and devel-21. Just change the option in the user preferences and save so it will carry over between Blender restarts.

**Comment by Lightye** [comment]
Thanks!
