### ISSUE TITLE
Several Issues with version 21

### ISSUE THREAD

**Issue by afecelis** [bsavery/PRMan-for-Blender#308]
Dear Brian,

Scenes created with previous versions (20) won't render in version 21. Mesh emitter material node has changed:
http://www.telardigital.com/afecelis/renderman/v21/emitter_v21.jpg
How do you create an emitter material in v21?

IPR renders a black Image:
http://www.telardigital.com/afecelis/renderman/v21/IPR_21_black.jpg

Only if you render using the render button do you get something to display on IT (but I had to create a new v21 scene).

With previously created files, if you start IPR you get the following error:
http://www.telardigital.com/afecelis/renderman/v21/devel_21_err.jpg

So... I haven't been able to render anything in version 21  :(

Help Brian, help!  ;)

**Comment by afecelis** [comment]
Also, material preview only shows up white. It doesn't display any bitmap/shader/color info.

**Comment by bsavery** [comment]
Living on the bleeding edge!  So couple things:

1.  Make sure you get the latest devel-21 branch https://github.com/bsavery/PRMan-for-Blender/tree/devel-21   it's updating daily (hourly)

2.  Make sure you have RenderMan 21 installed as well.  

3.  In the blender preferences, make sure it's using RenderMan 21 for the addon.

Then you'll need to remake your light nodes as the shaders that were in 20 are no longer there.

**Comment by afecelis** [comment]
Thanks Brian.

Thanks Brian,

I'm using v21 because I purchased the commercial version and got an email notifying me about the new release, not that I'm running betas or early versions or invoking the ancient dark powers of the render god since I know it's not out yet as NC, but I know that with every major new version comes a lot of changes and broken things  ;)

1. I'm using that same devel-21 version since the other 2 don't work with V21. In fact, I had just downloaded the latest commit prior to posting my issues.
2. Renderman 21 is installed. As a matter of fact, the new installer is much more streamlined and easier to follow.  :D Check the following screenshot please:
http://www.telardigital.com/afecelis/renderman/v21/prman21_env_vbles.jpg
3.Here are the options used in blender (default):
http://www.telardigital.com/afecelis/renderman/v21/prman21_prefs.jpg

Where can I find the blender-equivalent changes for the shaders? Does every new version break stuff like this so drastically? Is there an option to auto-update materials from previous versions to current? Doing it by hand may be a little time-consuming.

As usual, thanks a lot for taking care of us blenderheads  :D 

regards,
Alvaro

**Comment by bsavery** [comment]
All your materials should still work.  It's the light shaders that we dramatically changed.  

For what it's worth you can just change the light type in the properties and it should update the shader correctly.  Also I added a check to not error on old lights.  As far as a transition script.  That would be pretty easy actually.  Just a bit swamped at the moment with SIGGRAPH next week

**Comment by pafurijaz** [comment]
Hi bsavery, I have several bugs when I use your plugin, this is the first I've found, in debug mode.

`C:\Users\pafurijaz\Desktop\blender-2.77.0-git.f2fa737-AMD64\2.77\scripts\startup\bl_ui\space_node.py:427
bpy.ops.shading.add_renderman_nodetree(idtype="material")
WM_operator_last_properties_store: storing properties for 'SHADING_OT_add_renderman_nodetree'
A00003 {WARNING} Invalid initialization state.
Error: EXCEPTION_ACCESS_VIOLATION`

**Comment by bsavery** [comment]
Are you using RenderMan 21?

**Comment by MWY3510** [comment]
It seems that this issue is resolved with additions made over the months. I will close this but if there are still problems the issue can be reopened.
