### ISSUE TITLE
Issue about local Queue problems

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#321]
https://renderman.pixar.com/forum/showthread.php?s=&threadid=32015
I've post to forum already. Here just for backup

Post #188187

**Comment by jdent02** [comment]
Hi Marco,
I did submit a patch that partially fixes the animation issue.  Particles still won't work but cloth sims and deformation meshes should.  That being said my solution is probably not the best one so Brian may (rightly so) decide against using it.

**Comment by bsavery** [comment]
This should be fixed now?

**Comment by jdent02** [comment]
I think so.  I added in a line for the spooling op that created the output directory if it didn't exist.  If you spooled prior to that on a fresh file that had never had an IPR session launched it could fail as the output directory didn't exist.
