### ISSUE TITLE
Proposal: Remove 'local render only' option from external render

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#322]
With LocalQueue spooling mostly working (minus the deforming body/particle issues), having the additional 'local render only' seems a bit redundant given how limited it is in capabilities (even compared to internal rendering).  Pretty much all you can do is render and even that's done without any kind of progress feedback.

**Comment by bsavery** [comment]
I'd agree.

**Comment by jdent02** [comment]
Okay.  I'm working on some spooling related stuff (adding the ability to denoise AOV's through LocalQueue) so I'll add that to the list.

**Comment by jdent02** [comment]
Rolled in.  Closing.
