### ISSUE TITLE
Exporter Issue while trying to convert Cycle Scene

### ISSUE THREAD

**Issue by melMass** [bsavery/PRMan-for-Blender#340]
Hello bsavery,

Thanks for the addon! It works great on a fresh scene, but I'm trying to convert my characters from cycles and the exporter throw errors :

The errors : 
http://imgur.com/a/iHx4S

The Steps:
- Remove all shaders from the meshes and all lights in the scene. Save
- From a new scene append the Character Group
- Add Lights
- Start it IPR (the render go fine, synced with the viewport, everythng: move light, add shaders...)
- Stop the IPR (though blender UI)
- Restart the IPR (error there see the pics)
- Now the BL UI still show Stop IPR so obviously when pressed it comlains about no it process running.

Appart from that everything seem to work fine. Do you know whats going on ? How can I debug it more for you ?

Thanks

My current system:
Arch Linux
Blender 2.77a
RMAN 20.1

**Comment by bsavery** [comment]
can't seem to reproduce this.  Can you attach the scene?

Brian

**Comment by melMass** [comment]
Hello Brian, 

I'll send you a mail with the scene. 
I have realised a little other issue I had. If your scene name contains spaces in its name the exporter looses track of it.


**Scene Filename:** _Biscuit Character_v12_renderman.blend_
`Cannot change directory to /home/mel/renderman/Biscuit: No such file or directory`

**Comment by melMass** [comment]
Can't seem to find your email.


So the **errors:**

```
P38003 {ERROR}   Invalid light handle for Illuminate: "World". (at line 43 in /home/mel/renderman/Whoaw_Guy_anim_renderman/Scene.0035.rib; current identifier name: <unnamed>)
Dependency cycle detected:
  Whoaw_reshaped.001 depends on Armature through Armature Modifier.
  Armature depends on Whoaw_reshaped.001 through Driver.

Array iterator out of range: Object_material_slots_lookup_int (index 1)
Traceback (most recent call last):
  File "/home/mel/.config/blender/2.77/scripts/addons/PRMan-for-Blender-master/operators.py", line 336, in invoke
    engine.ipr.start_interactive()
  File "/home/mel/.config/blender/2.77/scripts/addons/PRMan-for-Blender-master/engine.py", line 585, in start_interactive
    write_rib(self, self.scene, self.ri, visible_objects)
  File "/home/mel/.config/blender/2.77/scripts/addons/PRMan-for-Blender-master/export.py", line 2992, in write_rib
    data_blocks, instances = cache_motion(scene, rpass)
  File "/home/mel/.config/blender/2.77/scripts/addons/PRMan-for-Blender-master/export.py", line 1903, in cache_motion
    get_instances_and_blocks(objects, rpass)
  File "/home/mel/.config/blender/2.77/scripts/addons/PRMan-for-Blender-master/export.py", line 1693, in get_instances_and_blocks
    inst_data_blocks = get_data_blocks_needed(ob, rpass, mb_on)
  File "/home/mel/.config/blender/2.77/scripts/addons/PRMan-for-Blender-master/export.py", line 1806, in get_data_blocks_needed
    1].material] if psys.settings.material and len(ob.material_slots) else []
IndexError: bpy_prop_collection[index]: index 1 out of range, size 1

location: <unknown location>:-1

location: <unknown location>:-1
```

**the file:**

[Whoaw_Guy_anim_renderman.tar.gz](https://github.com/bsavery/PRMan-for-Blender/files/415199/Whoaw_Guy_anim_renderman.tar.gz)

I think it must be datablock of propierty issues, but it is interesting to find what is really going on.

**Comment by jdent02** [comment]
The second error block (starting with Array iterator) looks like it's related to your materials.
