### ISSUE TITLE
Hemi and sky bug

### ISSUE THREAD

**Issue by theGASMASK** [bsavery/PRMan-for-Blender#341]
When I have a hemi light using an HDRI, with visibility turned off, and a sky set up in the world panel with visibility on (but all component weights as black and shadows off, just for a quick sky background), it will mix the HDRI in with the sky. Tried switching visibility for both lights on and off but it persisted, which makes me think it's a bug of some sort. The actual light and shadow contribution works fine though, it's only an issue with actual environment map visibility.

I do wonder if it's because of how Blender handles environments, because it's either/or for env and sky in the world panel, but I figured I'd post it here anyways.

**Comment by jdent02** [comment]
I think it's an issue with Renderman in that it can only have one dome 'hemi' light and if there are two it get's confused.

**Comment by bsavery** [comment]
Yes this seems like a PRMan bug.  I'll file it over on the Pixar side.

Good catch!
