### ISSUE TITLE
OBJ issue renderman

### ISSUE THREAD

**Issue by yomerol** [bsavery/PRMan-for-Blender#37]
there an issue when you import an  OBJ and the you want to shot the render it crash and say RPman exited

**Comment by bsavery** [comment]
please leave a repro case.

**Comment by yomerol** [comment]
What you mean ?

**Comment by zeffii** [comment]
@yomerol something reproducible. Like a link to an obj  + .mtl file where that always PRman always exists if you import the .obj to Blender and then render it. If you are not comfortable sharing your work, then you must make a small demo file which you can share.

Also are you saving the .blend after importing the .obj -- but before trying to render - this might be worth trying.

**Comment by yomerol** [comment]
![screen shot 2015-07-19 at 1 26 01 pm](https://cloud.githubusercontent.com/assets/9106798/8767200/4f372d22-2e1a-11e5-86e4-4fc0ca25b20e.png)
![screen shot 2015-07-19 at 1 26 09 pm](https://cloud.githubusercontent.com/assets/9106798/8767199/4f37403c-2e1a-11e5-975c-94b9e2c1c08c.png)
![Uploading Screen Shot 2015-07-19 at 7.58.54 AM.png…]()

**Comment by yomerol** [comment]
this are the images and the red code is the error that it send me

**Comment by yomerol** [comment]
also IT does not work I am using Mac with yosemite

**Comment by AtomicPerception** [comment]
This may be one of those models that actually needs "fixed" before it can
be rendered. Like the previous models I encountered that had extra vertices
but without faces.

Have you tried a different object, like the default cube?

**Comment by bsavery** [comment]
I recently made a fix to strands that detects stray vertices.  Maybe we could do the same for polys?

**Comment by bsavery** [comment]
I'm going to close this unless we can get a reproducable case here.
