### ISSUE TITLE
didn't find holdout option

### ISSUE THREAD

**Issue by idr1s** [bsavery/PRMan-for-Blender#372]
i have seen a tutorial about a holdout shader
and he used the "holdout object" option
<img src="https://tmpimg.us/images/2016/11/13/Untitled3.jpg" alt="Untitled3.jpg" border="0" />

but i didn't find that option
<img src="https://tmpimg.us/images/2016/11/13/Untitled2.jpg" alt="Untitled2.jpg" border="0" />

i have tested that in blender 2.77 , 2.78 and prman 0.9.0 , 20.11.0

**Comment by jdent02** [comment]
Hi.  That option was removed a while ago.  The way the holdout is done now is with object groups.  There is a default one named 'collector' that you can assign objects to.  Then you can set up a 'shadow' pass with the layers and have it only apply to that group.

**Comment by bsavery** [comment]
Object groups are on the scene properties BTW.

**Comment by MWY3510** [comment]
Ok I think the question was answered. I'm going to close this I think. Feel free to reopen this if there you have problems or further questions about the holdout system.
