### ISSUE TITLE
PRMan: Exited error Blender 2.78

### ISSUE THREAD

**Issue by yazhubal** [bsavery/PRMan-for-Blender#374]
I'm using now Blender 2.78v on Windows 10, 
Installed: 
Renderman ProServer 20.11
Renderman Studio 20.11 for Maya (2016)
Latest PRMan for Blender

Few seconds after starting the render process i have error PRMan: Exited
On console is nothing special
![prman](https://cloud.githubusercontent.com/assets/9074776/20298304/6f70aa04-ab15-11e6-83b2-a1a88beb37d6.png)
The scene is very simple just plane and camera, cube.

**Comment by jdent02** [comment]
Try launching blender from a command line. There is often more detail in there when an issue occurs.

Sent from my iPhone

On Nov 15, 2016, at 2:27 AM, Piotr Szuszkiewicz - Yazhubal <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm using now Blender 2.78v on Windows 10,
Installed:
Renderman ProServer 20.11
Renderman Studio 20.11 for Maya (2016)
Latest PRMan for Blender

Few seconds after render proces i have error PRMan: Exited
On console is nothing special
[prman]<https://cloud.githubusercontent.com/assets/9074776/20298304/6f70aa04-ab15-11e6-83b2-a1a88beb37d6.png>
The scene is very simple just plane and camera, cube.

-

**Comment by yazhubal** [comment]
Ok probably problem with slash in file location. 
![2016-11-15 14_15_14-wiersz polecenia - blender](https://cloud.githubusercontent.com/assets/9074776/20307115/3c8caab0-ab3e-11e6-9d22-675684cae44b.png)

**Comment by jdent02** [comment]
Those slashes are okay, so it's not that.  Just for kicks, can you replace the space in the file name with an _ and see what happens?  We recently made some updates to handle file names with spaces but it might have a bug or two in it.

**Comment by yazhubal** [comment]
Later I will try to reinstall this plugin
![blender](https://cloud.githubusercontent.com/assets/9074776/20311573/9b0aef22-ab50-11e6-9ed9-3290c867a986.png)

Below my settings in preferences:
![blender 2](https://cloud.githubusercontent.com/assets/9074776/20311609/ba535aa4-ab50-11e6-8698-5412ef6fd87d.png)

**Comment by jdent02** [comment]
Are you using an old file?  Your output directory is set to your C: drive but for some reason it's trying to save to your F: drive.  Sometimes old files can get corrupted with newer versions of addons.

**Comment by bsavery** [comment]
Have you tried this on Renderman 21?

**Comment by amyspark** [comment]
@bsavery the same happens with Renderman 21.2 when I use "Convert Cycles to Renderman" and the generated material is a PxrSurface.

**Comment by regiellis** [comment]
I can confirm that this happens even if you hard code the the paths with the variable images args. For me, it looks like it is trying to create some EXR files in the image directory to write to, but fails to properly do so. I can confirm that the plugin can find the directory; I created empty EXR files in the directory with the expected naming conversion. When I activate a render the Scene.0001.exr is deleted and never recreated, at which point the plugin starts to look for the file to write to without ever recreating it. 

Blender 2.78b
Windows 10
Renderman 21.2

![capture](https://cloud.githubusercontent.com/assets/1148310/22865255/1f4f3a54-f12e-11e6-99cf-d9782f4289dc.JPG)

**Comment by rjanvier** [comment]
Could you please check if your entities contains some spaces or other special chars, it solves the issue in my case.
