### ISSUE TITLE
Latest Renderman 21 installed, all fresh, including latest zip from Github for AddOn - FAILED

### ISSUE THREAD

**Issue by enzyme69** [bsavery/PRMan-for-Blender#375]
I tried rendering a simple scene and getting no render. Just this error message, wonder why:
![screen shot 2016-11-16 at 19 13 20](https://cloud.githubusercontent.com/assets/3952687/20339556/2c3d66a6-ac31-11e6-827f-77c60308f691.png)

**Comment by gattomanzo** [comment]
same here, installed latest addon after renderman 21 end reboot but no plugin showed in user preferences.

**Comment by bsavery** [comment]
Enzyme.  Did you install Renderman Pro server 21?  You rerorr says you're using 17

**Comment by jdent02** [comment]
Gattomanzo, if you're on Windows make sure the folder name doesn't have '21.2' in it.  For whatever reason Blender won't load an addon if that happens.  You can either download again (as this has been fixed) or you can remove the '.2' from the folder name.

**Comment by gattomanzo** [comment]
that's it! it works now. thank you very much!

**Comment by MWY3510** [comment]
Fantastic!

**Comment by enzyme69** [comment]
@bsavery I am on Mac. For unknown reason I might have installed 17, but I want 21 which I installed yesterday.

Maybe I should remove old version? How to remove it in Mac? I don't think I can uninstall?

**Comment by enzyme69** [comment]
Alright I just deleted the folder of version 17. Seems like ok and rendering now. Cheers!
