### ISSUE TITLE
Blender 2.78 - No Material Node Selected

### ISSUE THREAD

**Issue by jdbener** [bsavery/PRMan-for-Blender#376]
![image](https://cloud.githubusercontent.com/assets/9505508/20340955/ee549032-ab98-11e6-8ba3-7e3606fbf322.png)

For some reason, the addon isn't generating the proper node tree. I have tried installing both the main and devel 21 branch versions, however, any changes made in the node editor don't take effect in the material preview or IPR.

The only error I seem to be getting is a small message at the top of the material window which says "No Material Node Selected." Heading this warning I tried adding a PRMan output node to the graph which had no perceivable effect on the problem. 

I am using Blender 2.78a and Renderman Non-Commercial 21.2.

Let me know if you need any more information.

**Comment by bsavery** [comment]
I think you just need to scroll down in the node editor.  You do have a nodetree if it's showing up in the property editor.

**Comment by jdent02** [comment]
A lot of the time when you add a node tree it is placed below the Cycles tree and you have to scroll to see it

Sent from my iPhone

On Nov 16, 2016, at 6:59 AM, bsavery <notifications@github.com<mailto:notifications@github.com>> wrote:


I think you just need to scroll down in the node editor. You do have a nodetree if it's showing up in the property editor.

-

**Comment by jdbener** [comment]
This is something you may want to say in the UI somewhere. Since you are going for ease of use. :)

**Comment by bsavery** [comment]
Possible we could set the view_center on the nodetree to somewhere between the output nodes...

https://www.blender.org/api/blender_python_api_current/bpy.types.NodeTree.html
