### ISSUE TITLE
Can not switch off Incremental Render 

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#377]
I use Path Tracer mode but when i switch off Incremental Render checker, IT still give me progressive render.

**Comment by jdent02** [comment]
You using IPR?

Sent from my iPhone

On Nov 16, 2016, at 6:39 AM, MarcoCheng <notifications@github.com<mailto:notifications@github.com>> wrote:


I use Path Tracer mode but when i switch off Incremental Render checker, IT still give me progressive render.

-

**Comment by bsavery** [comment]
I see this too.  Thanks for the report.

**Comment by bsavery** [comment]
FIxed in master.

**Comment by bsavery** [comment]
https://github.com/bsavery/PRMan-for-Blender/commit/e118be28249dd03f207c2e85ce280cf0c79ec36e
