### ISSUE TITLE
Can not switch off Incremental render

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#378]
I can't switch off Incremental render in path tracing mode (seems other mode also have this problem, like occlusion mode)

**Comment by bsavery** [comment]
Sorry, didn't I just fix this issue?

**Comment by MarcoCheng** [comment]
What? Oh that's my fault. I'm sorry... I just though my computer haven't sent the post to github and i can't find the original one, so I post it again... i will try now... :P  SOrry.... I make a mistake...

**Comment by MarcoCheng** [comment]
It works fine now thanks Brian

**Comment by MarcoCheng** [comment]
It works fine now thanks Brian
