### ISSUE TITLE
Rendering Particle Sphere

### ISSUE THREAD

**Issue by enzyme69** [bsavery/PRMan-for-Blender#381]
Since there is not really a Tutorial and Example Scenes for Blender specific, I am trying to explore all obvious basic areas.

First one: Particles.

Blobby works fine, but....
![screen shot 2016-11-17 at 19 06 26](https://cloud.githubusercontent.com/assets/3952687/20380924/fa54c526-acf8-11e6-8a40-22e4f2ecd5c6.png)

Switching to Spheres and I am not getting anything.

Any idea?

**Comment by enzyme69** [comment]
BLEND:
https://www.dropbox.com/s/xui9monjbzz5qg5/renderman_test_21_002.blend?dl=0

**Comment by enzyme69** [comment]
Using Object slot, assigning 3D object in Pixar property panel also didn't seem to do anything.

**Comment by enzyme69** [comment]
![screen shot 2016-11-17 at 19 26 27](https://cloud.githubusercontent.com/assets/3952687/20381502/c2980d0c-acfb-11e6-9112-7565692d2895.png)

Rendering Particles that are set using Blender owns Dupli Object and Group seems to work with Size, Colour.

However, still, Pixar Object and Spheres are in question.

**Comment by enzyme69** [comment]
One question:
Is it possible for Renderman to see Points / Vertex Geometry as Spheres and can we assign custom variables?

**Comment by bsavery** [comment]
Thanks enzyme.  We actually have some example scenes:
https://github.com/bsavery/PRMan-for-Blender-Example-Files  but they haven't been updated to 21.  Also there a few in the example dir in the addon.  I'll take a look at the particle thing.

**Comment by bsavery** [comment]
Fixed in master
