### ISSUE TITLE
Intersection Priority in Object Properties

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#386]
We should add the intersection priority to object properties.  Maybe in the ray tracing section?  
https://renderman.pixar.com/forum/showthread.php?s=&postid=194287#post194287

**Comment by jdent02** [comment]
It's already in there......

**Comment by jdent02** [comment]
One thing I would change is not having to activate the raytrace override to use it though.....

**Comment by bsavery** [comment]
Oh, well then I would be completely embarrassed if I posted this on github.
