### ISSUE TITLE
I've tried everything, updating to 2.75, upgrading my renderman to renderman 20. Nothing works. Still getting the annoying traceback error.

### ISSUE THREAD

**Issue by PonchoVillegas** [bsavery/PRMan-for-Blender#39]
http://imgur.com/amVQiT4

**Comment by bsavery** [comment]
Do you have the RMANTREE environment variable set or PYTHONPATH?  Check out installation.txt

**Comment by bsavery** [comment]
Or you installed Renderman in a different place than C:\Program Files\Pixar....

**Comment by ohsnapitsjoel** [comment]
PonchoVillegas - the error says that it's looking for the prman module in a
RenderMan ProServer-19 directory. Check your RMANTREE environment variable,
it looks like it's pointing to version 19 still.
