### ISSUE TITLE
Can't install the RM plugin :( | traceback error

### ISSUE THREAD

**Issue by Ivcota** [bsavery/PRMan-for-Blender#392]
![capture](https://cloud.githubusercontent.com/assets/18635074/20468152/bae6a260-af50-11e6-99e3-91e9a955bb87.PNG)

Can you please help me? Thanks in Advance

**Comment by bsavery** [comment]
That tends to imply that you have the addon is registered twice, like you have two copies of it.

**Comment by Ivcota** [comment]
Thanks for quick reply! I'm so confused. So, there is another copy just lying around that I don't know about? Is it like in appdata somewhere?

**Comment by bsavery** [comment]
Yeah, probably if you go through your list of installed addons, is there another RenderMan for Blender copy perhaps?

**Comment by Ivcota** [comment]
Yeah I found another copy and deleted it. Thanks! It's working. 👍
