### ISSUE TITLE
Render just stops without warning.

### ISSUE THREAD

**Issue by enzyme69** [bsavery/PRMan-for-Blender#396]
![prtscr capture_36](https://cloud.githubusercontent.com/assets/3952687/20481259/5a09fed4-b03a-11e6-9bae-91ec58682fbb.png)

I got this a few times today while batch rendering animation. 

Render stops in random frames. No error message. I am still testing this Renderman in Blender for my own project. The render looks insanely beautiful, but small hickups like this that kind of gives me a bit of pimple.

**Comment by enzyme69** [comment]
I'll try to manually continue the batch rendering, and see what happened tomorrow morning. 410 frames to go.

**Comment by enzyme69** [comment]
I have 2 Blender opens and while PRMan rendering, I am doing something with other Blender. Wonder if this is a case.

**Comment by jdent02** [comment]
Are you rendering internally or using LocalQueue (Renderman batch controller)?

**Comment by enzyme69** [comment]
No, just normal Blender batch button (render anim).

**Comment by enzyme69** [comment]
Probably we can close this until I am batch rendering again.
