### ISSUE TITLE
Converting from Cycles still uses PxrLayer

### ISSUE THREAD

**Issue by jdbener** [bsavery/PRMan-for-Blender#400]
The title sums it up. Converting from cycles will sometimes give a PxrLayer node instead of a PxrSurface node. Which of course leads to some problem when you try to render. 
https://drive.google.com/file/d/0BzAgC2JpDb-aekFTQnI2ZEQ2djQ/view

**Comment by jdent02** [comment]
The conversion system is still very new.  It's meant to give you a good starting point for material conversions, not provide 100% accurate translations (which is pretty much unlikely to happen given how different the two engine's shading methods are).

**Comment by bsavery** [comment]
Hey JDBener,
I'd have to look at your file exactly but that shading network looks correct.  PxrLayer has the same parameters as PxrSurface, but you can only have one PxrSurface as the base.  You can't use PxrSurface as anything other the base.  

What's the problem when you try to render?

**Comment by jdbener** [comment]
The model renders out completely purple.

**Comment by jdbener** [comment]
It seams to have been the layermix

**Comment by bsavery** [comment]
Ok. If you feel it's something the conversion could handle better send s
scebe
