### ISSUE TITLE
ö, ä,ü and ß in an objects name makes PRMan crash.

### ISSUE THREAD

**Issue by Stuntkoala** [bsavery/PRMan-for-Blender#408]
If an objects name in the scene has an ö, ä, ü or ß (german letters) in it, Renderman will not render the image but "IT" displays a black image and Blender tells me PRMan: Done Rendering: elapsed Time: 00:00:00
not a big deal for me now that i know not to name my objects like that but it might screw ups some german users scenes.

**Comment by bsavery** [comment]
Yep.  It's on the list to fix this.
