### ISSUE TITLE
Renderman nodes also show up while working with Cycles

### ISSUE THREAD

**Issue by Stuntkoala** [bsavery/PRMan-for-Blender#409]
It's a great thing to have Renderman and Cycles use the same nodesystem since some cycles nodes also work in Renderman, but it is a bit distracting to have them all in the shift+a list too when you are rendering in Cycles. It's not really a bug or a big deal, but this often makes me uninstall the Renderman Addon while i am working with Cycles.

**Comment by bsavery** [comment]
Unfortunately there's no real way around this as we can't hide nodes based on the render engine setting.  I'd be willing to go so far as to call this a blender bug.  We can't do all the things we'd like if we used a custom node tree.  

Like you said the really only workaround here is to disable Renderman when you want to use cycles exclusively.  Sorry.

**Comment by Stuntkoala** [comment]
Then so be it :D having the possibility to use nodegroups and cycles osl nodes is totally worth it. Keep up the awesome work you do!
