### ISSUE TITLE
Light moved at PRMan render start

### ISSUE THREAD

**Issue by rendermouse** [bsavery/PRMan-for-Blender#41]
A light is consistently moved to a different position at start of PRMan render. Does not happen for Cycles or Blender renderer. 

Does IR cache object positions? Perhaps these coordinates are getting cached after IR exit and old coords are being pushed back into Blender UI at render start?

reference forum post: https://renderman.pixar.com/forum/showpost.php?s=&postid=166293

scene file: https://www.dropbox.com/s/86zgtdwxcm1nmc3/rman_dice.zip?dl=0

**Comment by bsavery** [comment]
I'll take a look at the scene.  Is the light animated?

**Comment by rendermouse** [comment]
I will try to get a consistent set of steps for reproducing this issue.

**Comment by rendermouse** [comment]
No animation in the scene.

**Comment by rendermouse** [comment]
I did move the light during IR, though.

**Comment by rendermouse** [comment]
I tried unloading the scene with a new empty one, then reloading my file.  Hit render, light moved.

**Comment by rendermouse** [comment]
Posted an example scene file here:
https://www.dropbox.com/s/fqe2o8hmvtmuzpd/rman_dice_dupli.zip?dl=0

**Comment by bsavery** [comment]
Thanks!  I haven't gotten a chance to work on this one yet but it's on the list!

**Comment by bsavery** [comment]
Fixed, I think.  It was just the hemi light right?

**Comment by rendermouse** [comment]
I think I linked to the wrong scene, the link should have been: 
https://www.dropbox.com/s/vx6dir1du2ayf95/rman_base.blend?dl=0

However, I got the latest code and the issue in my scene does seem to be fixed.
