### ISSUE TITLE
PxrMeshLight Intensity and Exposure Slider is too sensitive

### ISSUE THREAD

**Issue by enzyme69** [bsavery/PRMan-for-Blender#414]
Not sure what Max and Min got assigned to the slider for PxrMeshLight (it's when one wants to use Mesh to Emit), but somewhat I can set it up from 1 to 10000 in a single drag. The value is too sensitive?

![screen shot 2016-12-06 at 12 27 09](https://cloud.githubusercontent.com/assets/3952687/20909389/8b86a2b6-bbaf-11e6-9322-3110e274ba5d.png)

**Comment by bsavery** [comment]
So first of all I agree with you.  

However all the properties for shaders are automatically parsed from the xml args files in RenderMan.  If there's no min/max specified there, then Blender assumes the min/max is 10000 or -10000 I guess.  We could special case in the code, and say "if this is the intensity parameter set the min/max to this".  And it might make sense in an often used param like this, but in general we try to stay away from writing special cases in code, they're slow and always a pain to maintain.

Thoughts?

**Comment by bsavery** [comment]
Oh also one thing I do notice is that it's a slider in Meshlight and not in an actual lamp...

**Comment by enzyme69** [comment]
I guess it is alright just something to be noted in the documentation :) Cheers~
