### ISSUE TITLE
Particle System - Hair with Object/Group render

### ISSUE THREAD

**Issue by Dr4g0nBlade** [bsavery/PRMan-for-Blender#427]
I have a scene with an hair system set to "Group", in the viewport it works without problems but when I try to render, the mesh generated by the hair system doesn't gets rendered
I tried with "Object", same problem... in "Path" mode, it gets rendered :(

Is this not supported by PRMan-for-Blender? or I am doing something wrong?

[hair-problem.zip](https://github.com/bsavery/PRMan-for-Blender/files/677434/hair-problem.zip)

**Comment by MWY3510** [comment]
I'll take a look at this tomorrow. Thank you for providing an example scene.

**Comment by MWY3510** [comment]
I think I found the issue. I should have time to fix it tomorrow. Thank you for your patience.

**Comment by bsavery** [comment]
Fixed.

**Comment by bsavery** [comment]
https://github.com/bsavery/PRMan-for-Blender/commit/1791bc5b4d0261cc78c829e938b5898f7c231423
