### ISSUE TITLE
Scale/Position ingnored for PxrDomeLight

### ISSUE THREAD

**Issue by AndreasReschGFX** [bsavery/PRMan-for-Blender#428]
Hello,

we had an issue with the PxrDomeLight on the forum.

It looks like the scale and position settings of PxrDomeLight are ignored when exporting the RIB file (rotation works). By doing so, it's not possible to flip the map by negatively scaling the light in the X direction.

Cheers,
Andreas

**Comment by MWY3510** [comment]
Good day. 
Are you referring to the world settings Environment setting or the Lamp object?

I was unable to reproduce the mentioned behavior with the latest version of the addon using the Environment lamp. Understandably the position setting does nothing to a PxrDomeLight but the scale options work on my end and allows me to flip the map.

**Comment by AndreasReschGFX** [comment]
Hello,

where are the "Environment Settings" for the PxrDomeLight (or HEMI type) object? Can't find them.

I've just tried it and it doesn't work for me. I've created a PxrDomeLight (which should be called Dome LIght in Blender to avoid confusion) with a scale of [-30, 30, 30] and a position of [0.05, 0.10, 0.15] and this is what's written to the RIB file for the transformation of the light ...

Transform [ 1 0 -1.50996e-007 0  -1.32005e-014 -1 -8.74228e-008 0  1.50996e-007 -8.74228e-008 1 0  0 0 0 1 ]

As you can see, all the scale and position information is stripped from the maxtrix. You have an euler conversion in line 668 of export.py which removes all of the needed values. That conversion needs to be removed. The input matrix "m" looks fine - just convert it to the version that Renderman uses and we are good to go.

Cheers,
Andreas

**Comment by bsavery** [comment]
So more of the issue, I think we have the correct rotation on hemi lights.  I used the "Luxo Jr" env map that comes with renderman, and the name on the "Steve Jobs Building" (one of the buildings on Pixar campus is legible and the correct orientation.

**Comment by AndreasReschGFX** [comment]
Well,

and yet here are (at least) two guys where the HDRI is flipped. Fact is that Maya scales the Dome Light negatively in the X direction on creation and Blender doesn't. I guess there is a reason why Maya does this scaling.

Can you provide a scene file for us to check and compare?

Cheers,
Andreas

**Comment by bsavery** [comment]
Fixed
