### ISSUE TITLE
Animation - Expload modifier in an particle emitter 

### ISSUE THREAD

**Issue by Dr4g0nBlade** [bsavery/PRMan-for-Blender#429]
The only frame of the animation that's rendered is only the first frame that you render, the mesh doesn't gets updated
[Expload.zip](https://github.com/bsavery/PRMan-for-Blender/files/678974/Expload.zip)

**Comment by bsavery** [comment]
I think I can fix this, but doubt it will work with motion blur.

**Comment by bsavery** [comment]
jk.  It works with motion blur.  Fixed.
