### ISSUE TITLE
How to set RMANTREE to PRman 20?

### ISSUE THREAD

**Issue by PonchoVillegas** [bsavery/PRMan-for-Blender#43]
Still having issues. Where do I go to set RMANTREE to PRman 20? What files do I open? Also, how do I do this?

**Comment by MWY3510** [comment]
Please have a look here and see if that helps. https://renderman.pixar.com/forum/showthread.php?s=&postid=166400#post166400

**Comment by bsavery** [comment]
I'm marking this closed.  I've fixed the code to not allow you to set the RMANTREE to 19.0.  We've also explained a few places how to fix this.
