### ISSUE TITLE
Properties Tab suddenly missing when in Pixar layout

### ISSUE THREAD

**Issue by enzyme69** [bsavery/PRMan-for-Blender#434]
Sometimes I noticed tabs missing from Panel such as Dimension tab, Color Management tab.

I need to switch to Blender defaut "Blender Render" layout to get these back. But doing that I often forgot I am switching render and need to switch back to "Pixar Renderman".

Not sure what is causing this. It happens time to time, but keep eyes on it.

**Comment by MWY3510** [comment]
Hmm I don't see this behavior in the current Master or in the latest release. Can you tell us more about when this occurs.

**Comment by enzyme69** [comment]
Ok, I was doing live video and ....
https://www.youtube.com/watch?v=CinPAkOeufI

...around 31:50 you see those TABs are missing.

**Comment by enzyme69** [comment]
Around 30:00 I lost the Color Management.

I have a feeling maybe because I was using Sverchok, Animation Nodes, etc...

**Comment by enzyme69** [comment]
And I was not using IT for my render.

**Comment by MWY3510** [comment]
I have been unable to recreate this with just the RenderMan add-on running. I will take a look at the other add-ons you mentioned but I don't believe that it is PRMan-for-Blender add-on's fault.

Have a great day,
Ryan

**Comment by MWY3510** [comment]
I have not experienced this issue using some of the addons mentioned. I will go ahead and close this issue. If this still persists without extra addons than feel free to reopen this issue.

Thanks,
Ryan

**Comment by bsavery** [comment]
I think the correct way to implement this now is this btw:  https://developer.blender.org/rB1d81f6

**Comment by MWY3510** [comment]
So Brian you think we should use an exclusion list?

**Comment by bsavery** [comment]
Commited.
