### ISSUE TITLE
Distant light rotation axes reversed.

### ISSUE THREAD

**Issue by RonFrancis** [bsavery/PRMan-for-Blender#439]
Blender 2.78a
RenderMan 21.2 for Maya-Maya2017 (1676607)

It's difficult to believe this is a bug because I couldn't find mention of it anywhere, and it should be something that would be obvious to anyone using distant lights. 

When working with distant lights, the axes rotations are reversed.

To replicate the problem, set up a camera location (0,0,1), rotation (75,0,0).
I added a cylinder at location (0,6,0) with dimensions (0.1, 0.1,1) and put a plane underneath it to see where the shadows fell.

A distant light with an x rotation of 45 degrees.
![x 45 deg](https://cloud.githubusercontent.com/assets/15881747/21878584/4fceadcc-d8e7-11e6-8b4a-cd623681437f.jpg)
This is the result and note that the shadow is coming toward the camera rather than away from it.

Here is the blender window.
![bender window](https://cloud.githubusercontent.com/assets/15881747/21879134/b5abaa3e-d8ea-11e6-9102-e2d28bc871c6.jpg)

Setting the light's z rotation to 30, you can see that the shadow is rotating anticlockwise rather than clockwise (if looking along the z axis).

![x 45 z 30](https://cloud.githubusercontent.com/assets/15881747/21878710/347980be-d8e8-11e6-858a-d69f786820d9.jpg)

**Comment by jdent02** [comment]
This should be fixed in Renderman 21.  The 20.x exporter still has some old bugs in it and I believe this was one of them.

**Comment by RonFrancis** [comment]
Sorry, I wrote the wrong version for some reason. Probably looked at the wrong installation file.
The version of Renderman I'm having a problem with is 21.2 for Maya 2017(1676607)
I have corrected the original post.

I recently updated Blender, PRMan and Renderman to the latest versions and this problem has occurred since then.

**Comment by lyonelDahu** [comment]
Sorry to say, but I have the same issue here... I'm using Blender 2.78a, PRMan for blender 21.2, and windows 10.

**Comment by jdent02** [comment]
Just recently launched a new scene and the distant light rotation appears to work fine.  Suggest closing this one.

**Comment by RonFrancis** [comment]
What versions are you using?
That is, Renderman, PRMan and Maya?
I had given up on this.

**Comment by jdent02** [comment]
Latest master and Blender 2.78b with Renderman 21.3.  I know that existing distant lights can get messed up when the exporter is updated.  I've seen it happen before and the only real solution was to delete the light and create a new one.  Got no clue why that is.

**Comment by RonFrancis** [comment]
Updating wasn't the issue because I created a new file for the images above.
The only part of the installation I was unsure about was which version of Maya I should use, but went for the latest in the list, but I didn't think it would make a difference in this case. That is, I just chose the latest version.
I see that Renderman has been updated to 21.3. I'll update everything when I get a chance and see how it goes.
Thanks for the feedback.

**Comment by RonFrancis** [comment]
OK, I uninstalled and deleted everything to do with Renderman, Blender and PRMan from my PC, including the registry and any files and folders left over. Did a clean install of with the latest versions, and the distant light is working as expected.

**Comment by jdent02** [comment]
That's good.  It may have been a 21.2 Renderman bug for all we know.
