### ISSUE TITLE
Command line rendering does not work.

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#44]

**Comment by bsavery** [comment]
When doing rib only.  It seems that blender expects some image output.

**Comment by Lightye** [comment]
There will be an empty image exported to /tmp. Had the same issue with Ebb's plugin. Just a bit annoying, but not a hinder. See 0:36 in video (http://sawe.asuscomm.com/published/scripts/batch/batch_render_720p.mov)

**Comment by bsavery** [comment]
I claim this is a "won't fix".  In the future rib only will be used for queuing
