### ISSUE TITLE
Blender crash when using "Convert All Cycles to Renderman" while IPR on

### ISSUE THREAD

**Issue by amyspark** [bsavery/PRMan-for-Blender#440]
Renderman version: `21.2`
Blender version: `2.78a`
Addon version: 2cdf5f8

Just enable IPR with the default scene, and while it is rendering, click on the cube. Then click on "Convert All Cycles to Renderman".

The following error is printed, and Blender exits:

```
A08021 {SEVERE}  k__write: FATAL: Write failed. (Out of disk space?) (System Error: Invalid argument)
```

**Comment by bsavery** [comment]
I'm going to assume that this is related to the other issue with PxrSurface?  As the convert script takes advantage of PxrSurface.
