### ISSUE TITLE
An idea to fix SSE4 support

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#444]
There's an easy python module called cpuinfo:  https://pypi.python.org/pypi/py-cpuinfo#downloads

Would be fairly easy to use this to detect when the user is on a non-sse4 machine.  

import cpuinfo
print(cpuinfo.get_cpu_info['flags'])

['acpi', 'aes', 'apic', 'clfsh', 'cmov', 'cx16', 'cx8', 'de', 'ds', 'dscpl', 'dtes64', 'est', 'fpu', 'fxsr', 'htt', 'mca', 'mce', 'mmx', 'mon', 'msr', 'mtrr', 'pae', 'pat', 'pbe', 'pcid', 'pclmulqdq', 'pdcm', 'pge', 'popcnt', 'pse', 'pse36', 'sep', 'smx', 'ss', 'sse', 'sse2', 'sse3', 'sse4.1', 'sse4.2', 'ssse3', 'tm', 'tm2', 'tpr', 'tsc', 'vme', 'vmx']

Using that we could make the defualt bxdf PxrDisney when sse4.1/4.2 isn't there.  Of course this would disable cycles conversion.  But might prevent some headaches.

**Comment by bsavery** [comment]
If someone has an AMD phenom machine I'm curious what the output is there.

**Comment by amyspark** [comment]
In my case (AMD A6-3670 w/o SSE4) I get:
```python
{ 'arch': 'X86_64',
  'bits': 64,
  'brand': u'AMD A6-3670 APU with Radeon(tm) HD Graphics',
  'count': 4,
  'extended_family': 0,
  'extended_model': 0,
  'family': 0,
  'flags': [ 'clflush',
             'cmov',
             'de',
             'dts',
             'fxsr',
             'ia64',
             'mca',
             'mmx',
             'mtrr',
             'pse36',
             'sep',
             'sepamd',
             'serial',
             'ss',
             'sse',
             'sse2',
             'tm'],
  'hardware': '',
  'hz_actual': '2.6990 GHz',
  'hz_actual_raw': (2699000000L, 0),
  'hz_advertised': '0.0000 Hz',
  'hz_advertised_raw': (0, 0),
  'l2_cache_associativity': 0,
  'l2_cache_line_size': 0,
  'l2_cache_size': 0,
  'model': 0,
  'processor_type': 0,
  'raw_arch_string': u'AMD64',
  'stepping': 0,
  'vendor_id': u'AuthenticAMD'}
```

**Comment by bsavery** [comment]
Thanks!  Yeah no SSE4 in the flags :(  Thats ok.  Great we could use this to disable PxrSurface in that case.
