### ISSUE TITLE
PRman not working with Blender 2.78a

### ISSUE THREAD

**Issue by Thereza07** [bsavery/PRMan-for-Blender#446]
I just installed Renderman 21 and PRman but not working with my Blender 2.78a. Preview in material panel not working. When I click add Renderman nodetree it says no material node selected. I'm in, by default in Renderman engine. When I try to render, PRman exited. 

![2017-01-22 18](https://cloud.githubusercontent.com/assets/25277316/22180994/ad05031a-e0bc-11e6-9507-bce37a0498b9.png)

**Comment by jdent02** [comment]
Launch Blender from a command line and see if any more detailed errors are generated. Also if you could include a file that would be great.

Sent from my iPhone

On Jan 22, 2017, at 1:57 AM, Thereza07 <notifications@github.com<mailto:notifications@github.com>> wrote:


I just installed Renderman 21 and PRman but not working with my Blender 2.78a. Preview in material panel not working. When I click add Renderman nodetree it says no material node selected. I'm in by default in Renderman engine. When I try to render, PRman exited.

-

**Comment by bsavery** [comment]
Are you using an amd phenom processor?

**Comment by Thereza07** [comment]
Ah. . its ok now. I try so search deeper yesterday after posting this and I saw the post that saying to delete the 21.2 or at least .2 in the Renderman filename. I do it and everything is already fine. Well I'm using laptop. Its a little slow and crashes but working. I know it crashes because my ram capacity. Thanks for the help too. I saw the post here tooin closed post.
