### ISSUE TITLE
object groups

### ISSUE THREAD

**Issue by lyonelDahu** [bsavery/PRMan-for-Blender#447]
Hi there,

First of all, thank you for implemanting PRMan into blender. This is really awesome.

I'm trying PRMan for blender because I'm looking for a strong and versatile renderer from blender. One of the feature I'm really missing with Cycles is lightlinking, and PRMan for blender works really great for that. I'm having trouble with the object groups though. I simply cannot add any object of my scene (even a simple and new one) to an object group... Is it the same on your side ? What am I missing ?

I'm using the latest build (PRMan for blender 21.2), with Blender 2.78a, on windows 10.

Please, let me now if you have any idea about this. And thank you very much for all this good work !

**Comment by lyonelDahu** [comment]
Ok, for some reason, it's now working... Weird... I just restarted my computer and I can esealy create object groups.

Sorry about that.

**Comment by MWY3510** [comment]
I'm glad it's working for you now. Feel free to reopen this if it comes back.
