### ISSUE TITLE
Export Multilayer and deep data

### ISSUE THREAD

**Issue by MattRM2** [bsavery/PRMan-for-Blender#450]
Hi,

I tried Export Multilayer with and without deep and the result is the same in Nuke : 
- The primary beauty exr works
- The multilayer exr return only black datas and nan (with or without deep)

Without using Export Multilayer, all the passes are good and readable but no deep datas.

In attachment : 
- The blend file setuped in Export Multilayer and Use Deep Data
- The two exr files from this setup
- Somes screenshot with a strange warning from Local queue

If you have an idea to output a dtex file, I get it in waiting of a fix or a retake from your side on my setup (in blender or nuke) ;)

Best Regards,

Matt

![capture_002](https://cloud.githubusercontent.com/assets/25594057/22663407/c767cf98-ecac-11e6-9891-26b788e0e820.PNG)
![capture_001](https://cloud.githubusercontent.com/assets/25594057/22663408/c76ea93a-ecac-11e6-8581-c6e2b7d30437.PNG)
[images.zip](https://github.com/bsavery/PRMan-for-Blender/files/755676/images.zip)
[test_deep.zip](https://github.com/bsavery/PRMan-for-Blender/files/755678/test_deep.zip)

**Comment by jdent02** [comment]
Can you include the scene RIB file?  Renderman isn't liking something about the channel display declaration.

**Comment by MattRM2** [comment]
Hi,

Of courses, here in attachment ;)
You've : 
- all the rib datas freshly created
- The output image (with multilayer "on" but only one frame output this time, forget to say it prevously, quite random)
- An other screenshot from the setup that output all this datas
- And the blend file that output this freshly datas

Tell me if you need others datas
A++

Matt

![capture](https://cloud.githubusercontent.com/assets/25594057/22748645/fe6370d6-ee2a-11e6-868f-38ca7b15fce4.PNG)

[test_deep.zip](https://github.com/bsavery/PRMan-for-Blender/files/761397/test_deep.zip)
[test_deep_blend.zip](https://github.com/bsavery/PRMan-for-Blender/files/761412/test_deep_blend.zip)

**Comment by jdent02** [comment]
Yeah somethings going wrong with the display channel declaration and it isn't matching up with the image output declaration.  That equals unhappy Renderman.  I'll take a look at it.

**Comment by jdent02** [comment]
Try it now.  Hopefully should be fixed
