### ISSUE TITLE
2.77/2.78 Hair render fail...

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/PRMan-for-Blender#454]
I've do some hair test on RMS 20.11 With 20.X addon... But when i add hair system my geometry, no hair was rendered... but the strangest is, when i enable Interpolated, Renderman can render my hair...

![bugs](https://cloud.githubusercontent.com/assets/15306113/23130975/4af27630-f7c3-11e6-9287-a2251be61698.jpg)
Left: No hair was rendered. Middle: Viewport. Right: Use Interpolated
I've been tested on 2.77 and 2.78... same problem

[Fur_Bugs.zip](https://github.com/bsavery/PRMan-for-Blender/files/787865/Fur_Bugs.zip)

**Comment by bsavery** [comment]
This is fixed in 21 I think.   Please move to the new version.
