### ISSUE TITLE
Error installing addon for Blender 2.78c in Debian Linux

### ISSUE THREAD

**Issue by ialebedev** [bsavery/PRMan-for-Blender#463]
Hi

Here is an error, which I get when I try to install the addon.
![prman_error](https://cloud.githubusercontent.com/assets/16067800/24217120/2f74bf56-0f58-11e7-85a4-8e0a4147a01f.png)

**Comment by bsavery** [comment]
What version prman are you using?

Brian

**Comment by ialebedev** [comment]
21.0

**Comment by bsavery** [comment]
There was a bug in 21.0, just run the renderman installer to get 21.3!

**Comment by bsavery** [comment]
(closing because I know this is the issue)
