### ISSUE TITLE
"Only Render Selected" option still renders child objects

### ISSUE THREAD

**Issue by lewis2e** [bsavery/PRMan-for-Blender#466]
Hi

The option "Only Render Selected" (in the Render settings tab) will still render child objects of parent objects that are not selected.

To reproduce, create a scene with three cubes (cube1, cube2 and cube3). Parent cube2 to cube3, and select cube1 and enable "Only Render Selected".

Cube1 will render (which is correct), but so will cube2 (which is incorrect).

Many thanks for all the work on this amazing project.

**Comment by bsavery** [comment]
OK Thanks I'll take a look.  That's fairly clear.

**Comment by lewis2e** [comment]
Fantastic, thanks.

**Comment by bsavery** [comment]
https://github.com/bsavery/PRMan-for-Blender/commit/34da32afd6a072cdb8bcb671d58657568562efbc  fixe.
