### ISSUE TITLE
Particle instance

### ISSUE THREAD

**Issue by Sanekum** [bsavery/PRMan-for-Blender#467]
Particle system renders RIB container insted of RIB archive

**Comment by bsavery** [comment]
Sorry I'm not sure what exactly you mean, can you attach a scene?

**Comment by Sanekum** [comment]
I cant attach scene because of link for the RIB archive, but it is easy to recreate problem.
So 1 picture - I create a RIB archive from Suzanne mesh, made it look like a box, when I render I see Suzanne
2 - I made simple particle instance with my suzanne RIB archive, when I render I see boxes instead of Suzannes
Sorry for bad english
![Uploading proxy.jpg…]()

**Comment by bsavery** [comment]
No, that's clear.  I can reproduce that!  Thanks

**Comment by bsavery** [comment]
fixed.  https://github.com/bsavery/PRMan-for-Blender/commit/fdbc55e6f268596998cd8cb32358880b900ad817
