### ISSUE TITLE
Need better visual feedback of area lights in viewport.

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#47]
Particularly the size/shape.

**Comment by zeffii** [comment]
with a BGL overlay drawing?

**Comment by bsavery** [comment]
Perhaps.  Where's the entrypoint for doing that?
Part of the issue is that we write the rib for area lights based on the transform alone.  The area lights in RIB geometry wise are all 1 unit, and to make a 4x4 rectangular light you would scale it.  ex:

Scale 4 4 4
Geometry "rectlight"

So we're using the objects transform to set the size.
Now, what could be done is add to the light object properties a shape (rectangle, sphere, etc) and a size property.  Use those for size, and base the drawing overlay on that property.

**Comment by MWY3510** [comment]
I have adjusted the area light to display the correct size in the viewport. This only works for the rectangle and square shapes. Any other shapes must be drawn by the plugin.

**Comment by bsavery** [comment]
I'm going to call this "closed" for now.  Also I made it so that when you add the renderman node tree it switched from point type to area.
