### ISSUE TITLE
Smooth shading doesn't render on object with 2 materials

### ISSUE THREAD

**Issue by boboalice** [bsavery/PRMan-for-Blender#471]
when rendering a mesh with 2 materials, the smooth shading wont render.

![untitled-1](https://cloud.githubusercontent.com/assets/27031391/24821115/626de9ba-1bf5-11e7-94cb-261797b35dc6.png)

**Comment by bsavery** [comment]
As jdent02 mentioned on forums, please attach a scene.

**Comment by boboalice** [comment]
Blend file:

http://s000.tinyupload.com/download.php?file_id=91264460124297322516&t=9126446012429732251698003

**Comment by bsavery** [comment]
So wait, the ball on the right is smooth, and the one on the left is not smooth?  Or the one on the left is smooth?

**Comment by boboalice** [comment]
they are both smooth shaded before the render. but when rendering, only the ball wit h1 material (right) renders smooth.

**Comment by bsavery** [comment]
Fixed:
https://github.com/bsavery/PRMan-for-Blender/commit/72d16883c3b38948ec32632e5c0413e4e7f92f41

**Comment by jdent02** [comment]
Brian I think I found the issue but I don't know when I'll have time to bug test it. The multi material mesh export function uses the term 'varying normals N' as a condition for an 'if' loop.  Everywhere else that I can see uses the term 'facevarying normals N'.  So it might just be a typo.

Sent from my iPhone

On Apr 7, 2017, at 5:08 PM, boboalice <notifications@github.com<mailto:notifications@github.com>> wrote:


they are both smooth shaded before the render. but when rendering, only the ball wit h1 material (right) renders smooth.

**Comment by bsavery** [comment]
Already saw that ;)

**Comment by bsavery** [comment]
and fixed it.

**Comment by boboalice** [comment]
wow, great. thanks !!!

**Comment by jdent02** [comment]
Yeah the fix notice popped up five seconds after I hit send :)

Sent from my iPhone

On Apr 7, 2017, at 6:16 PM, boboalice <notifications@github.com<mailto:notifications@github.com>> wrote:


wow, great. thanks !!!
