### ISSUE TITLE
Motion  Blur & Curves

### ISSUE THREAD

**Issue by Sanekum** [bsavery/PRMan-for-Blender#473]
Objects paranted to Cuvre objects with Ctrl+P Follow Path ingnore motion blur

**Comment by bsavery** [comment]
As always please attach a scene...

**Comment by Sanekum** [comment]
Sorry, cannot attach zip, github send message about unsupported file format
![scr](https://cloud.githubusercontent.com/assets/26864751/24924097/12a5d59e-1f0d-11e7-869d-92fa89c77296.jpg)

Cube-1 moving with Ctrl-P attachment to the NurbsPath object
Cube-2 moving with keyframes animation

**Comment by bsavery** [comment]
Weird, zip files worked before unless github changed.  Either putting it on dropbox or posting the file on https://renderman.pixar.com/forum/forumdisplay.php?s=&forumid=166  would help.  Thanks!

**Comment by Sanekum** [comment]
Here it is
https://www.dropbox.com/s/ia63ii3v7ehrjiw/MotionBlur.blend?dl=0

**Comment by bsavery** [comment]
Fixed.  Download the latest addon.
