### ISSUE TITLE
Ramp UI needs work

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#48]
Unfortunately you can't use the Blender Ramp UI easily.  We'll have to make our own.

**Comment by MWY3510** [comment]
This is not a solution, but worth considering if we don't have time to make our own. http://blender.stackexchange.com/questions/19289/are-ui-color-ramps-possible-through-python

**Comment by bsavery** [comment]
I actually tried that (found the same stack exchange thread ;) ) and couldn't get it to work.  The other issue is that had to make a "dummy" node with a ramp in it.  

http://www.theallium.com/engineering/computer-programming-to-be-officially-renamed-googling-stackoverflow/

**Comment by MWY3510** [comment]
Oh well sorry about that. How high is this issue on this list because coding a new ramp is quite time consuming. Also I whole heartily agree with the name change :-) I don't know how many times I have to go there for programming stuff.

**Comment by bsavery** [comment]
I dunno maybe I'll give another try.  But I could create a dummy "ramp"
node but couldn't display the ramp attribute.

On Thursday, July 23, 2015, MWY3510 <notifications@github.com> wrote:

> Oh well sorry about that. How high is this issue on this list because
> coding a new ramp is quite time consuming. Also I whole heartily agree with
> the name change :-) I don't know how many times I have to go there for
> programming stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/48#issuecomment-124243373>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
Weird.  I tried again and was able to make this hack work.  Need to polish it a bit more.  Also talking to blender guys about getting Color ramp natively in python api.

**Comment by bsavery** [comment]
Hacky.  But should work now.
