### ISSUE TITLE
Binding of Primitive Variables by PxrOSL nodes

### ISSUE THREAD

**Issue by ma0mpt** [bsavery/PRMan-for-Blender#487]
Hi,

I am using your very fine 'PRMan-for-Blender' addon.  Impressive :-)

My issue is with binding primitive variables in OSL shader code.

I have set up a cube geom' and have textured some vertices.  If I use a PxrPrimvar node then I can use the exported colors (Cs) without a problem.  However, I would like to be able to export more variables and use them within a shader without having to add a PxrPrimvar node for each one.

According to the Pixar/OSL doc's I should be able to do this:

shader binding_test(
    color Cs = 0 [[int lockgeom = 0]],
    output color Cs_out = 0
)

{
    Cs_out = Cs;
}

and this should bind Cs in my shader code.  But it doesn't - I just get black.

Am I missing a crucial point here?

**Comment by bsavery** [comment]
Ok.  I see there's a bug when we generate rib for osl shaders with lockgeom.  I'll fix that in a few.

**Comment by bsavery** [comment]
So here's a question.  

The basic assumption when you have a parameter with the [[int lockgeom = 0]] meta data is that you DON't hook up anything to it (and that it doesn't show up in the rib)  Would you have an issue if the input didn't show up in the node when that lockgeom is set?

**Comment by bsavery** [comment]
https://github.com/bsavery/PRMan-for-Blender/commit/0c93ad269e6edea08ccb3e241432ec14d76cbb57  see latest commit.

**Comment by bsavery** [comment]
You'll have to hit shader refresh on the node.

**Comment by ma0mpt** [comment]
Hi,

V quick response.  Wasn't expecting that.  I have been out and have only just seen your replies and fix.

The OSL shader architecture now works as advertised and that is very cool/useful. 

As far as not being to override the bound primvars is concerned: it wouldn't be an issue for me.  The doc's don't really make it clear if these vars should/could be overridden by outputs from other nodes.  The only hint is that if they are not defined on the primitive then they should return 0.

Thank you very much for cracking this so quickly.

Incidentally, if you think you could use any additional effort to fix things things like this then I would be keen/happy to learn and assist. Would need a few dev' pointers though.

M

**Comment by bsavery** [comment]
Right.  Well officially, you CAN override them by emitting them into the rib (which happens when the input is present on the node), however if you want to get the primvar, you CANNOT emit them into the rib...

**Comment by bsavery** [comment]
And we are always looking for developers.  Are you ok with python?
