### ISSUE TITLE
OSL support. 

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#49]
Currently You can attach an osl node but have no way to set the outputs.  Perhaps we could introspect the oso file?  Also being able to compile them in blender would be great.

**Comment by MWY3510** [comment]
The cycles python files have a good implementation of osl compilation (Cycles\osl.py). I am not sure that its implementation for node generation will work for our purposes though.

**Comment by MWY3510** [comment]
The latest commit to my fork has an example of blender compiling the osl code. It uses part of cycles code just so you are aware.

**Comment by bsavery** [comment]
This is awesome.  I'll have to take a look.  I'm working on the Multimaterial export (already made that a bit faster today).  Also would like to take a look at curves rib gen a bit.  Are you still working on that?

**Comment by MWY3510** [comment]
I can take a look at the curves code. I do not know how much I can do but I will see. Also I might have a solution for generating the node properties for osl.

**Comment by bsavery** [comment]
If you want to take the osl project that would be great.  I'll focus on curves.

**Comment by MWY3510** [comment]
Ok i'll see what I can do.

**Comment by MWY3510** [comment]
I have basic export work done and have started on dynamic nodes. A side benefit might be that blender could dynamically load any development changes to nodes without restarting (useful for RIS plugin testing.)

**Comment by bsavery** [comment]
Awesome!

**Comment by MWY3510** [comment]
I have separated the update osl and update other shaders into different operator buttons. Do you want the update all button on the properties panel or on the material panel? The update osl button will be attached to the node.

**Comment by bsavery** [comment]
I thought the update shaders was just for .sl shaders?  Or does it reload
Args files? Either way the update osl on the mode sounds great

On Thursday, July 23, 2015, MWY3510 <notifications@github.com> wrote:

> I have separated the update osl and update other shaders into different
> operator buttons. Do you want the update all button on the properties panel
> or on the material panel? The update osl button will be attached to the
> node.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/49#issuecomment-124128626>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
It can reload args files. I am also adding this because I spending some time writing custom shaders and i like to leave blender open during testing.

**Comment by MWY3510** [comment]
Export system complete and it works quite fast. Unfortunately it looks like I have to build my own node refresh system. The cycles node refresh causes an instant crash. The existing framework will make this easy. I project that the system will be in place tomorrow and ready for testing.

**Comment by bsavery** [comment]
Really excited to see this!

**Comment by MWY3510** [comment]
Quick update the node gen is looking good just a few more things to go.

**Comment by MWY3510** [comment]
Another update the node update is not done. Still writing but the inital shape is done. Here is an image. Let me know what you think.
![oslnode](https://cloud.githubusercontent.com/assets/9410101/8887845/5001c1da-3262-11e5-9860-5e58e38dbaaa.jpg)

**Comment by bsavery** [comment]
First of all great job.  
So is the workflow that users will code an osl shader and then point to the compiled oso there with that node?  And then how do you get the inputs and outputs?  

Or are you compiling the osl file yourself?  The alternative if you were is that they could do the coding in the node itself similar to how an .slbox works in slim.

**Comment by MWY3510** [comment]
The workflow as I see it will be for the user to write the osl shader then put that path in the node. When the button is pressed the osl code will be compiled and the node will set will all the necessary properties and outputs. 

I am compiling the osl file using blender's built in osl compiler. It is a little behind the version pixar is using (pixar: 1.6dev,  Blender: 1.5.11) but in my tests it has not caused prman any issues and renders correctly. If you know of any problems with this let me know.

I am getting the input and output nodes from the compiled oso file. It has lines that clearly defines if a parameter should be in or out. The only thing I cant get is whether they should be connectable or not. I will probably make them all connectable unless I can think of a way to figure out which should be and which should not.

Hopefully this makes sense.

**Comment by bsavery** [comment]
AFIAK all connections to an osl shader are connectable... It would be nice eventually to have people type in a text editor in blender, and compile that code, but that workflow works fine!  

I'm not current on the osl versions well enough to be honest about the differences. The integration to PRMan will be better going forward, so this work will become even more useful.

**Comment by MWY3510** [comment]
There is an option to use data blocks in blender using its text editor. But I am just working on basic support first with that as a secondary objective. Cycles has the option to use ether internal or external files so it is possible just more work.

**Comment by bsavery** [comment]
Agreed, that's a second step ;)  Sounds awesome though!

**Comment by MWY3510** [comment]
Progress is being made just so people know. It will probably take another day or two. Dynamic generation is mostly in and the .oso parser is written. Just need to finish the input generator. This is a picture of the carbonfiber osl shader outputs. Thanks Pixar for the wonderful example files.
![nodeoutputs](https://cloud.githubusercontent.com/assets/9410101/8922877/33d56b68-34b7-11e5-9fe7-5eea1de22ec8.jpg)

**Comment by MWY3510** [comment]
UI is mostly done. The node will rename itself to whatever the shader name is also for easy identification. This picture shows the carbonfiber node in all its glory.
![oslnodesui](https://cloud.githubusercontent.com/assets/9410101/8949894/ae256bcc-3587-11e5-8eaf-098aca23de94.jpg)

**Comment by bsavery** [comment]
nice!

**Comment by MWY3510** [comment]
I can now safely say that the dynamic ui is almost finished. I had to repair some memory leakages that i made. So I am up to reworking the export system to deal with the location I store dynamic properties in. Now that I have the UI working I can show off all the nodes. (Let the hype train commence.) 
![osl nodes](https://cloud.githubusercontent.com/assets/9410101/8975301/83386e64-364a-11e5-802d-032526f0b999.jpg)

**Comment by bsavery** [comment]
If you can get at least a WIP to me by noonish tomorrow, I'd really like to work this into SIGGRAPH presentation!

**Comment by MWY3510** [comment]
That's fine. I am finishing it up today. There are some problems with the UI it at the moment. They should not affect your presentation however.

**Comment by MWY3510** [comment]
Ok, what was holding up a majority of my progress was a funny bug (not in least bit funny when hunting for it) that would cause memory exceptions when new materials or a preview render was called for. Currently to avoid this bug (incomplete preview export) I have prevented the plugin from exporting osl shaders in preview mode. Also if you are using interactive rendering mode OSL will not work even with a successful export and there is a 50/50 chance that it will crash blender (so use with extreme care or not at all). I'm not sure if this is my exporter or PRMan itself.

**Comment by bsavery** [comment]
That sounds like a prman bug. I'll definitely track it down.

On Thursday, July 30, 2015, MWY3510 <notifications@github.com> wrote:

> Ok, what was holding up a majority of my progress was a funny bug (not in
> least bit funny when hunting for it) that would cause memory exceptions
> when new materials or a preview render was called for. Currently to avoid
> this bug (incomplete preview export) I have prevented the plugin from
> exporting osl shaders in preview mode. Also if you are using interactive
> rendering mode OSL will not work even with a successful export and there is
> a 50/50 chance that it will crash blender (so use with extreme care or not
> at all). I'm not sure if this is my exporter or PRMan itself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/49#issuecomment-126557785>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
Thanks Brian, Now that my problems other problems are mostly sorted I have cool pictures to show off. This image was made using four different OSL shaders (mixcolor, oak, marble and voronoi.) There are only a few things that I don't have working correctly (mostly related to textures.)
![oslmadness](https://cloud.githubusercontent.com/assets/9410101/9000593/bb5158c4-3717-11e5-993b-cafbe5dc89c9.jpg)

**Comment by bsavery** [comment]
Oh wait. Is interactive updating while the compile is happening?  I could
see that crashing things

On Thursday, July 30, 2015, MWY3510 <notifications@github.com> wrote:

> Ok, what was holding up a majority of my progress was a funny bug (not in
> least bit funny when hunting for it) that would cause memory exceptions
> when new materials or a preview render was called for. Currently to avoid
> this bug (incomplete preview export) I have prevented the plugin from
> exporting osl shaders in preview mode. Also if you are using interactive
> rendering mode OSL will not work even with a successful export and there is
> a 50/50 chance that it will crash blender (so use with extreme care or not
> at all). I'm not sure if this is my exporter or PRMan itself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/49#issuecomment-126557785>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
No, the shader is compiled when the node is generated I do not compile the shader when a render is called for. Only the properties of the node are changed during interactive rendering. Great thought though.
I have made some changes to make the node generation even more efficient. The oak shader only takes half a second to compile and generate!!
Unfortunately I don't think I will have time to make export as effective. Currently on smaller scenes export and setup can take twice as long as the same scene without osl shaders.

**Comment by bsavery** [comment]
That's fine.

On Fri, Jul 31, 2015 at 5:53 AM, MWY3510 <notifications@github.com> wrote:

> No, the shader is compiled when the node is generated I do not compile the
> shader when a render is called for. Only the properties of the node are
> changed during interactive rendering. Great thought though.
> I have made some changes to make the node generation even more efficient.
> The oak shader only takes half a second to compile and generate!!
> Unfortunately I don't think I will have time to make export as effective.
> Currently on smaller scenes export and setup can take twice as long as the
> same scene without osl shaders.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/49#issuecomment-126681650>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
I have finished up almost everything that should be included at this point. The only thing that is missing is texture support. It should be in before too long but since you wanted the OSL code before noon I will push it later.

**Comment by MWY3510** [comment]
Since I have created a pull request to add this in I am marking this issue closed.
