### ISSUE TITLE
Rendering produces noisy rendering with even simple materials. Image comparison between blender and maya.

### ISSUE THREAD

**Issue by PonchoVillegas** [bsavery/PRMan-for-Blender#54]
I set up a simple scene to test stuff out. Here's what I got:
Blender:
![noisy2](https://cloud.githubusercontent.com/assets/12225954/8863372/54d03042-3155-11e5-8e65-bc05697149ee.png)

Here's a similar render made in Maya:
![mayaversion](https://cloud.githubusercontent.com/assets/12225954/8863377/690c2d5e-3155-11e5-9cd6-cb7e3a1828c0.jpg)

**Comment by bsavery** [comment]
Do you have the same settings and materials in both scenes?  What are your sampling settings?  Are you using the same lights?  

Both the blender addon and RenderMan for Maya use the same RenderMan on the backend, if your scene is set up the same they should come out similarly.  However the defaults may be different.

**Comment by bsavery** [comment]
I'm going to close this issue, it's probably better handled on the forum:

https://renderman.pixar.com/forum/forumdisplay.php?s=&forumid=166
