### ISSUE TITLE
Add txmake options

### ISSUE THREAD

**Issue by MWY3510** [bsavery/PRMan-for-Blender#55]
Add extra buttons to nodes that use textures to control the txmake process. Currently I should have this done in two days or less. Just adding the issue for tracking purposes.

**Comment by MWY3510** [comment]
Hello I just wanted to update this with the information that I almost have some options working. I was wondering what are the most wanted options for txmake?

**Comment by bsavery** [comment]
Texture periodic, or clamp modes. -srgb. Mipmap options. Float vs byte
depth. And type (openexr vs tiff vs Pixar)

On Thursday, August 6, 2015, MWY3510 <notifications@github.com> wrote:

> Hello I just wanted to update this with the information that I almost have
> some options working. I was wondering what are the most wanted options for
> txmake?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/55#issuecomment-128552469>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
Ok, thanks.

**Comment by MWY3510** [comment]
bsavery, when you say -srgb what do you mean? Also the current plan is to implement most of these using enum properties.

**Comment by MWY3510** [comment]
I have made some progress tonight, but no results until sometime ether tomorrow or the day after.

**Comment by MWY3510** [comment]
A picture of the progress that has been made. 
![textureoptions](https://cloud.githubusercontent.com/assets/9410101/9148885/b4b6ca6c-3d5c-11e5-8e4c-bd359657160f.jpg)
Let me know if you have any questions.

**Comment by jdent02** [comment]
I like it.  For what that's worth.....

**Comment by ohsnapitsjoel** [comment]
Chiming in here - could the new txmake options be hidden in a group that
can be opened like a subpanel?  I can't remember what that's called in the
UI backend at the moment, but some of the other nodes have this feature
(PxrBump, etc).  It's a pretty great feature, one that I didn't even
realize could be added to nodes until I saw the nodes that Brian was
creating.  It really makes working with nodes less of an eyesore.

**Comment by MWY3510** [comment]
Thanks for the feed back everyone. 
Joel, I agree with you that having them in a group would be the best option. This will be easy for the standard nodes but I was trying to come up with something that will work for OSL nodes also. 

In addition there are more options that I have yet to implement. For now those options that are in the image are the ones I will focus on getting working.

**Comment by jdent02** [comment]
Just curious, what other options are you looking at?  The ones on the mockup seem pretty comprehensive.

**Comment by MWY3510** [comment]
jdent02, 
I have yet to add mipmap options or in the case of environment textures, the ability to use cube textures.

**Comment by bsavery** [comment]
I wonder if we could move them from the node to the texture properties, to make it more of a "blender" like workflow?  

Similar to this: 
https://www.blender.org/manual/render/cycles/materials/texture_editing.html

What do you think?  I think the basic code to do that might be in the original code from Matt Ebb?

**Comment by jdent02** [comment]
Personally I'd rather have the option in the node.  Less tab browsing.  I'm used to working almost exclusively in the node tree thanks to cycles.

**Comment by MWY3510** [comment]
Here is the options in a subprop.
![texoptions](https://cloud.githubusercontent.com/assets/9410101/9241434/71137b32-4141-11e5-8435-b3f3ed47063f.png)

**Comment by bsavery** [comment]
I'm going to merge the pull but I'd change the label to "Txmake options"

**Comment by MWY3510** [comment]
Ok, this was only a rough draft to see how people liked the options. Any more ideas to better the UI would be greatly appreciated.

**Comment by Lightye** [comment]
Looking good! The current state of the plugin expect a flattened RGB with an alpha as separate channel (when exporting from PS). Cycles expect a single, non-flattened, layer and use the transparency baked into that layer (that can be "lifted" out again in PS). Adding a separate Layer Mask or alpha channel will create very bad artifacts (outlines) in Cycles. So, adding the option to use "alpha in layer" (new feature) or "alpha in channel" (current) for Txmake options would integrate with current Cycles behavior and support a mixed pipeline. Cheers!

**Comment by MWY3510** [comment]
The option for resizing has been added to the txmake options.

**Comment by MWY3510** [comment]
More options have been added sblur and tblur to be exact.

**Comment by MWY3510** [comment]
Just because most of the important options have been added I am closing this issue. If there are any more it should be a simple task since the system is in place. Feel free to reopen this if you have a problem.
