### ISSUE TITLE
Changing material selection results in odd render

### ISSUE THREAD

**Issue by Aurosutru** [bsavery/PRMan-for-Blender#56]
In the hair.blend example, changing Suzanne's material selection from diffuse to harimat results in this render:

![untitled](https://cloud.githubusercontent.com/assets/5417800/8874453/cd7c3b92-322e-11e5-998c-378c0aa5913e.png)

This didn't happen yesterday.  Changing the selection back to diffuse gives a normal render.  I'm not yet using IT.

BTW, the crash when rendering my Blender start-up file twice no longer happens, and never occurred with the Blender factory start-up file, only my simple file.  My start-up file is from an old version of Blender and that might make a difference.

**Comment by MWY3510** [comment]
Ok, I took a quick look through the export code. It looks like the export archive code will use whatever the active material is. I'm not sure if this is truly an issue or not.

**Comment by MWY3510** [comment]
I should clarify a little bit. Only objects that are exported as a static archive will have the active material applied. The only way this can have confusing results is when this is used in conjugation with particles (As seen above.) I don't think that a simple solution is available. Ether we can always use the active material, the first or last material, or add a material selection bar like the one in particles.

**Comment by bsavery** [comment]
Hmmm how does cycles do it?  Does it just grab the first one?

**Comment by MWY3510** [comment]
I think that cycles reads the assigned materials based on the faces. Like how our multi material system works. By default the first material to be added to an object is assigned to all the faces of the object. This results in the first material being used in a multi material system that has not changed the material assignment. If the first material is removed the faces are assigned to the next highest material and so on.

Short answer: Cycles I think uses the material_index per face.

**Comment by bsavery** [comment]
It sounds like you're saying the correct behavior in our case then if we weren't to go and look for materials attached to faces would be to select the first in the list.

**Comment by MWY3510** [comment]
Yes. I do like the option of using the active material though. But using the first would be the least confusing to most users.

**Comment by bsavery** [comment]
easy fix then.

**Comment by bsavery** [comment]
Fixed
