### ISSUE TITLE
Should we output all materials at the beginning of the ribgen?

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#57]
Currently we do this in rib:

(output object geometry data to /static/object.rib)
in main rib:
....
#for each object
ReadArchive static/object.rib
Bxdf "PxrDisney" "material_id"

We could do:
(output object geometry data to /static/object.rib)
(output all materials to static/materials.rib)

ReadArchive materials.rib

#for each object
ReadArchive static/object.rib
Restore State for material_id

This would clean up the rib files dramatically and make ribgen a bit faster.  The only downside would be if you had a ton of unused materials in your scene, but on any real scene this would be a huge net win I think

**Comment by MWY3510** [comment]
The idea sounds great. It will make tracking down material issues much easier.

**Comment by bsavery** [comment]
Ok.  Going to do this today, as well as set the used material to the first, not the active material to fix the other issue.

**Comment by bsavery** [comment]
Fixed
