### ISSUE TITLE
We need a set of simple test scenes/expected images

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#58]
To make sure we don't break things with checkin (I'm the most guilty here.)

A start of list of scenes/features:
Hair
smoke
duplis
multi-material objects
motion blur - transform
motion blur - deform
dof
light emission
"standard" lights
some simple shader node tree
scene with all geometry types: poly, subdiv etc
particles

**Comment by MWY3510** [comment]
I'll make one up later today. I think that as the feature set grows we need to continue to update the scene. I will post the finished scene on the forums when it is done. Do you think that it would be wise to include it in the plugin itself?

**Comment by bsavery** [comment]
yes in the plugin in a examples/ directory.  I was saying a number of small scenes and maybe one big one.

**Comment by MWY3510** [comment]
Ok, For the big one can I make it a benchmark scene (Heavy render time.)

**Comment by MWY3510** [comment]
There are some hold ups. The depth of field does not work at the moment (See my issue on this.) Also particles are broken at the moment (no testing done yet though, might just be me.)

**Comment by bsavery** [comment]
DOF doesn't work?  Hmmm I have that working here I thought last night.  Is it getting into the rib?

**Comment by bsavery** [comment]
I'll take a look at those, I'm editing the export code.  If you have a simple particles example that would be good.  Hair seems working fine here

**Comment by MWY3510** [comment]
Hair works fine but emmiter type particles do not show up. An example has been posted to the forums.

**Comment by bsavery** [comment]
DOF should be working.  However its subtle now because I'm respecting the scene units in the camera settings.  So the focal length is "shorter".  Its actually phsyically correct now but you might need a smaller fstop

**Comment by bsavery** [comment]
Did particles emitters ever work?  ;)  I could get something working today

**Comment by MWY3510** [comment]
I thought emitters at one point had a constant material but I might be mistaken. I still for some reason cannot get DOF working.

**Comment by apiruq** [comment]
I can build some usable demo scenes too.

A number of small scenes sounds better than one monolith monster scene. Of course there is some features which can and should be in same scene, but It's easier to new users to learn different features from smaller and simpler setups.

**Comment by bsavery** [comment]
That would be great if you could help with that!  I vote for a bunch of small tests and maybe one "everything but the kitchen sink" scene.

**Comment by MWY3510** [comment]
I have made a few up. One deals with hair. The other two are the shader node tree, and volumes respectively .

**Comment by apiruq** [comment]
Some simple scenes can be found from here: https://github.com/apiruq/Blender-to-PRMan-scenes

Hair seems to render always with guide/parent strands. I think those should be off when using child particles.

**Comment by MWY3510** [comment]
Great, thanks apiruq. I will get that packaged and into the next pull I do. Just as a note I will replace the hdri that you included with the motion blur deform scene. The site that it came from says that it cannot be redistributed, so to be on the safe side I will replace it with another one that can be redistributed. Thanks again for the scenes.

MWY3510

**Comment by MWY3510** [comment]
I have merge apiruq's examples with mine and they will be merged tomorrow along with OSL support.

**Comment by MWY3510** [comment]
Just letting everyone know that most of the provided example scenes have been reviewed and merged into my fork. I think we need a separate branch for the examples. The plugin download might become too large otherwise. I will try to merge the examples and my OSL improvements tonight.

**Comment by bsavery** [comment]
I have another repo:  
https://github.com/bsavery/PRMan-for-Blender-Example-Files  

Anyone have an issue moving these there?

**Comment by MWY3510** [comment]
Sounds great! I should have more files to put there later.

**Comment by bsavery** [comment]
Ok.  I'll move stuff now.

On Fri, Aug 14, 2015 at 10:47 AM, MWY3510 <notifications@github.com> wrote:

> Sounds great! I should have more files to put there later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/58#issuecomment-131193006>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
They are now in https://github.com/bsavery/PRMan-for-Blender-Example-Files
