### ISSUE TITLE
Camera Settings are not exported

### ISSUE THREAD

**Issue by MWY3510** [bsavery/PRMan-for-Blender#59]
Confirmed problems: Depth of field, Physical Camera (only FOV, Tilt Angle, roll angle.)

**Comment by apiruq** [comment]
I don't have any problems with dof. 
Please note that your scene must be on scale (1 blender unit = 1m) to get correct results. 

![dof](https://cloud.githubusercontent.com/assets/7015075/8883732/c3234426-3259-11e5-866d-20d97447821c.jpg)

**Comment by bsavery** [comment]
Also I THINK that physical camera is working correctly.  I set it up to only output the parameters that are not the defualt.

**Comment by MWY3510** [comment]
Ok I am an idiot. I was messing with the wrong Depth of Field option. The physical camera works too. Sorry about all this. I just needed some sleep.
