### ISSUE TITLE
Textures are not applied correctly. Even when UV unwrapped.

### ISSUE THREAD

**Issue by PonchoVillegas** [bsavery/PRMan-for-Blender#61]
Ex. If you apply a brick texture to a large plane, the texture will cover a rectangular area in the middle of the plane, but leaves two black rectangles above and below the texture. The texture does not stretch across the entire plane.

**Comment by bsavery** [comment]
Please attach a scene.

**Comment by PonchoVillegas** [comment]
This can be fixed by scaling the UV coordinates. However, in the Maya version, one does not need to do so.

**Comment by PonchoVillegas** [comment]
![rendermanforblenderuverror](https://cloud.githubusercontent.com/assets/12225954/8886331/93372a72-3225-11e5-9df7-4d2f6d98bb85.png)
This is what I am talking about comrade.

**Comment by bsavery** [comment]
I'm asking for a scene file example.  It's much easier to diagnose things when I can run a scene and see what happens, sadly I'm a horrible artist!

**Comment by PonchoVillegas** [comment]
http://www.filedropper.com/rendermantest

**Comment by PonchoVillegas** [comment]
Wait dont use that file! Sorry about that. 

http://www.filedropper.com/showdownload.php/rendermantest_1

**Comment by PonchoVillegas** [comment]
Theres your scene file

**Comment by bsavery** [comment]
Thanks, I'll take a look monday.

**Comment by AtomicPerception** [comment]
The problem may be in the wrapping/clipping of UV coordinates, my guess.
Blender is unique in that it allows UV coordinates to exists outside of the 0-1 range. They are simply wrapped back into 0-1 if the go over or under.

This image was rendered by Blender Internal and I scaled the single UV face to twice the size of the UV space, thus creating coordinates beyon the range of 0-1. It maps as intended.
![blender_internal_checker](https://cloud.githubusercontent.com/assets/1889590/8894094/3545a94e-3378-11e5-92ad-e90541e64323.jpg)


Here is the same plane rendered in PRMan. Notice that none of the texture beyond the 0-1 is considered for rendering.
![prman_checker-2](https://cloud.githubusercontent.com/assets/1889590/8894095/41a808b2-3378-11e5-899c-168f44f9e361.jpg)

**Comment by pleprince** [comment]
Can you check the texture's mode ? It looks like it is not in periodic mode.
To check type in a shell : txinfo texturename.tex
sample output :
```
txinfo ~/Documents/maya/projects/default/sourceimages/grid.tex
TextureInfo: file "/Users/plp/Documents/maya/projects/default/sourceimages/grid.tex"
Type:   plain texture
Version:       3 (4)
Maxchan:       0 (8)
Channels:      3
Minrpow:       0 (0)
Maxrpow:       0 (14)
Resolutions: [2 x 2] to [512 x 512]
Tile size:  4096 (4096)
Total of 270 tiles.
s mode: PERIODIC
t mode: PERIODIC
Channel datatype: TX_BYTE TX_BYTE TX_BYTE 
Pixel aspect ratio correction factor: 1.000000

    S:                  
    S: 1 2 3 4 5 6 7 8 9
T  1:  *                
T  2:    *              
T  3:      *            
T  4:        *          
T  5:          *        
T  6:            *      
T  7:              *    
T  8:                *  
T  9:                  *

No shadow matrices.
```

**Comment by ohsnapitsjoel** [comment]
I'm experiencing the same issue with UV-mapped textures now; oddly, I
wasn't experiencing these issues prior to pulling the latest changes (by
"latest" I mean I hadn't updated in about a week or so).  Have there been
some new commits that change the options passed to txmake, by any chance?
Or to the export of UVs?

**Comment by bsavery** [comment]
I just changed the options to Txmake to make the Periodic as PLP mentioned above... 
also poncho can you try your scene but attach a PxrManifold2D to the manifold slot on the pxrtexture nodes.  I made it so by default now when you add a pxrtexture you get the manifold as well now.

**Comment by bsavery** [comment]
Also don't have your textures...

**Comment by bsavery** [comment]
Does using the PxrManifold2D work?

**Comment by ohsnapitsjoel** [comment]
Hey Brian, I could be mistaken since there may be something I'm failing to do, but I don't know that the PxrManifold2D node solves the issue (at least the one I'm experiencing).  UVs still seem to be scaled;  has this been confirmed fixed?

**Comment by bsavery** [comment]
It seems like when no UV is applied, the ST's go from -1 1, you can use a PxrManifold with offset set to 1, scale x .5 in that case....  

With no UV applied, not sure what else we can do in that case.

**Comment by bsavery** [comment]
Are you seeing this on multi-material meshes?  If so I might have a fix...

**Comment by ohsnapitsjoel** [comment]
Yes, I'm seeing this on multi-material meshes.  Actually, it wasn't even a multi-material "mesh" per se, it was an object that had a material applied to all the faces, as well as another material the hair system was using.  But once I removed the hair material, it renders fine.

**Comment by bsavery** [comment]
Ok, that makes sense.

**Comment by ohsnapitsjoel** [comment]
Err, I take that back.  It renders, but I have to have "Invert T" unchecked and the PxrManifold2D node has to be set to a scale of 1 and an st offset of 1.0.  I admit I'm still pretty unfamiliar with how UVs are handled in PRMan, so this was just trial and error.

**Comment by bsavery** [comment]
What if you use a scale of .5?  

Background.  I noticed when no ST is written in the rib, they go from -1 to 1 on the object where PxrTexture wants them 0-1, so setting the scale to .5 offset 1 gets it right. 

I'm working on this though.
