### ISSUE TITLE
Blender crash when attempting to Interactive Render

### ISSUE THREAD

**Issue by amyspark** [bsavery/PRMan-for-Blender#63]
Blender version: 2.75 (release)
PRMan addon: 9aecc8ba32755302c1c87701db1165d67dbf47b4
RenderMan version: 20.1 (non commercial)
Platform: Windows 7 x64

I am unable to use the Interactive Render mode, as one out of two things happen:

* Blender crashes without any `blender.crash.log` file being produced (only an `Error: EXCEPTION_ACCESS_VIOLATION` being produced)
* PRMan renders to It, but Blender crashes as above when I cancel said rendering

When running from the command line, these are the logs I get.

For the second error (crash after cancelling render): 
```log
d:\Program Files\Blender Foundation\Blender>blender -d
Switching to fully guarded memory allocator.
Blender 2.75 (sub 0)
Build: Wed 07/08/2015 10:38 AM Windows
argv[0] = blender-app.exe
argv[1] = -d

Note: No (valid) 'C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\2.75\config\start
up.blend' found, fall back to built-in default.

read file
  Version 272 sub 2 date unknown hash unknown

ordered
 OBCube
 OBLamp
 OBCamera
read file C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\2.75\config\userpref.blen
d
  Version 275 sub 0 date 2015-07-07 14:56 hash c27589e
Read new prefs: C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\2.75\config\userpre
f.blend
found bundled python: d:\Program Files\Blender Foundation\Blender\2.75\python
read file
  Version 262 sub 3 date unknown hash
read file
  Version 268 sub 5 date unknown hash
read blend: C:\Users\Amy\Desktop\TPs\untitled.blend
read file C:\Users\Amy\Desktop\TPs\untitled.blend
  Version 275 sub 0 date 2015-07-07 14:56 hash c27589e

ordered
 OBLamp B
 OBLamp G
 OBLamp R
 OBBottom plane
 OBLamp
 OBTop plane
 OBLeft plane
 OBRight plane
 OBBack plane
 OBSphere
 OBCube
 OBCamera
Info: PRMan: Done Rendering. (elapsed time: 00:00:05)
Info: Packed 1 files

ED_undo_push: Pack All Into .blend
Evaluate all animation - 0.000000
        No Actions, so no animation needs to be evaluated...
R90007 {SEVERE}  DisplayWindow failed to send display data (System Error: Invalid argument)
R56005 {SEVERE}  Renderer completing shutdown request. (System Error: Invalid argument)
Error: EXCEPTION_ACCESS_VIOLATION
```
For the first error (straight crash):
```log
d:\Program Files\Blender Foundation\Blender>blender -d
Switching to fully guarded memory allocator.
Blender 2.75 (sub 0)
Build: Wed 07/08/2015 10:38 AM Windows
argv[0] = blender-app.exe
argv[1] = -d

Note: No (valid) 'C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\2.75\config\start
up.blend' found, fall back to built-in default.

read file
  Version 272 sub 2 date unknown hash unknown

ordered
 OBCube
 OBLamp
 OBCamera
read file C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\2.75\config\userpref.blen
d
  Version 275 sub 0 date 2015-07-07 14:56 hash c27589e
Read new prefs: C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\2.75\config\userpre
f.blend
found bundled python: d:\Program Files\Blender Foundation\Blender\2.75\python
read file
  Version 262 sub 3 date unknown hash
read file
  Version 268 sub 5 date unknown hash
read blend: C:\Users\Amy\Desktop\TPs\untitled.blend
read file C:\Users\Amy\Desktop\TPs\untitled.blend
  Version 275 sub 0 date 2015-07-07 14:56 hash c27589e

ordered
 OBLamp B
 OBLamp G
 OBLamp R
 OBBottom plane
 OBLamp
 OBTop plane
 OBLeft plane
 OBRight plane
 OBBack plane
 OBSphere
 OBCube
 OBCamera
Error: EXCEPTION_ACCESS_VIOLATION
```

The scene I am using to test is this one: https://www.dropbox.com/s/o7xvd8snkd7jtuf/untitled.blend?dl=0

**Comment by bsavery** [comment]
Hi Amy.  Just to confirm.  You mention rendering to 'it' but the above file seems like you're rendering to openexr when you're getting those errors.  The files should be written to your My Documents/prman_for_blender/{file name}/images/ directory.  It kind of sounds like that directory isn't working?  You can set the output directory in the preferences for the addon.

**Comment by MarshallRoss** [comment]
Not sure if this is your problem, but instead of toggling the usual interactive rendering button at the bottom of your window pane (from wireframe mode, or shaded mode, to render mode), use the button in the upper right near the top of the screen labeled "Start Interactive Rendering".  You can toggle this on and off.

**Comment by amyspark** [comment]
@bsavery The scene gets rendered to OpenEXR succesfully; the only problem is the Interactive Rendering mode.
@MarshallRoss Yes, I'm using that button.

**Comment by bsavery** [comment]
Hmmm, I can't reproduce this.  I'll have to try it tomorrow with a windows 7 machine.

**Comment by bsavery** [comment]
Can you try with latest build.

**Comment by amyspark** [comment]
Tried with cd10c7db6dc7d96c97b415ce65239b5374eae763: Blender still crashes as soon as I press ```Start Interactive Rendering```.

**Comment by bsavery** [comment]
do you have renderman studio installed?  What is the directory it is installed under?

**Comment by amyspark** [comment]
Yes, I've got version 20.1 installed under ```C:\Program Files\Pixar\RenderManStudio-20.1-maya2016```.

**Comment by amyspark** [comment]
@bsavery : I was able to reliably reproduce the second crash with the following steps. Make sure the ```Material``` panel's ```Preview``` tab is open when working with the .blend file.

2. Open a new Blender instance, load said .blend file.
3. While the Material preview RIB is being rendered (check it's a black box), click ```Start Interactive Rendering```.
3. ```Error: EXCEPTION_ACCESS_VIOLATION```, and Blender exits.

For the first one:
1. ```Interactive Render``` any .blend file.
2. Cancel the render with ```Esc``` and close It without stopping the render process in Blender.
3.
```
R90007 {SEVERE}  DisplayWindow failed to send display data (System Error: Invalid argument)
R56005 {SEVERE}  Renderer completing shutdown request. (System Error: Invalid argument)
A08021 {SEVERE}  k__write: FATAL: Write failed. (Out of disk space?) (System Error: Invalid argument)
AL lib: (EE) alc_cleanup: 1 device not closed
```
and Blender closes.

Tested with 52184a2e43f2619b08e6f2de6e2954657a88e336.

**Comment by JoseConseco** [comment]
I had same problem with same error 'Invalid argument' etc.
It was problem with license. 'It' could not be started, because license was in E:/Program Files/Pixar/pixar.license.   So I copied it to C:/Program Files/Pixar/pixar.license
And now it works!
I have dig dipper into IT  - it seems to update only when material, light change.  When I translate geomtry, dupilcate etc. It is not updating in preview...
