### ISSUE TITLE
NURBS

### ISSUE THREAD

**Issue by JSKjaer** [bsavery/PRMan-for-Blender#65]
Are NURBS objects supported? I ask because they are not visible in the render even after doing a convert to mesh operation.

**Comment by bsavery** [comment]
I would assume after converting to mesh they would work!  Otherwise no.

**Comment by JSKjaer** [comment]
I agree. Odd that conversion didn't do the trick. I deleted and created new poly object then it renders fine.

**Comment by AtomicPerception** [comment]
Auto Nurbs conversion can occur. Internally they could be considered a POLYMESH because they do have a valid to_mesh() method that could be called.

**Comment by bsavery** [comment]
Fixed.

**Comment by JSKjaer** [comment]
render of object converted from NURBS to poly works, thanks :)
