### ISSUE TITLE
Connecting or disconnecting LMLayer node while IR is running causes Blender to crash

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#67]
Log dump:

WM: failed to allocate texture for triple buffer drawing (out of memory).
Error: EXCEPTION_ACCESS_VIOLATION
R05004 {WARNING} RiEnd called before its proper nesting level.

C:\Program Files\Blender Foundation\Blender>An application exception has occurred in PRMAN.EXE.
  Error codes: 0x000000006D756964 0xC0000005 0x00000000 (0x00000008) (0x6D756964
)
*** exception ***

**Comment by bsavery** [comment]
Eek!  Yes actually I was working on something today that will fix this as well.  However need to test it more.

**Comment by bsavery** [comment]
https://github.com/bsavery/PRMan-for-Blender/issues/60  see item 2

**Comment by jdent02** [comment]
Just for clarification, is the inability to replace the shader nodetree a shortcoming of PRMan itself or the exporter?

**Comment by bsavery** [comment]
The exporter.  There's basically two ways you can do an update to a shader when interactive rendering.  
1.  Update a parameter(property)
2.  Re write the whole shader tree.  

Right now we just do 1, I'm testing whether doing 2 all the time is slower

**Comment by bsavery** [comment]
Fixed.

**Comment by jdent02** [comment]
What did you go with, out of curiosity?

**Comment by bsavery** [comment]
I figured out a way to distinguish between shader parameter edits (say
changing the diffuse color from green to blue) and changes to the Node tree
structure like connecting a lmlayer while running ipr. They are treated
differently in the calls to prman.

On Wednesday, July 29, 2015, jdent02 <notifications@github.com> wrote:

> What did you go with, out of curiosity?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/67#issuecomment-126149645>
> .
>


-- 
brian.savery@gmail.com
508-274-8700
