### ISSUE TITLE
not showing up

### ISSUE THREAD

**Issue by bmbjr59** [bsavery/PRMan-for-Blender#69]
I cant find renderman at all in blender ,I have followed the instuctions where to put it when I get everything which I have,followed to the letter
I also get some kind of error message when I start blender,its been suggested to me that I google this up,i wouldn't know how to list it,or even start for that matter.
I have been looking around in blender ,even with the problems it appears everything is working like its supposed to& everything is there except for renderman
the message it gives is nuts if was the case none of the video,or pictures would work I don't think & everything is working, so I don't know
I have a clip of what I get when I start blender
![3d a](https://cloud.githubusercontent.com/assets/13548497/8948991/6e56af38-3573-11e5-883d-4adf5f3452f9.jpg)
any ideas?
1 other thing I have not used any 3d stuff in a long time so bear with me
thankx for your time

**Comment by MWY3510** [comment]
Did you install and activate the add-on? If so what is the error message you receive when you try?

**Comment by bmbjr59** [comment]
when you are referring to activate ,are you referring to renderman? if so I think I have done this but im not sure ,as I say its not showing up at all in blender,all of this is a new ball of wax to me ,as I say bear with me

**Comment by bmbjr59** [comment]
in blender I have looked in the disabled enabled sections,nothing is there when I tried to physically find it in blender still nothing is there ,I know its in the addons like its supposed to be, that's where I put it,since this is happened ive checked to make sure of it

**Comment by MWY3510** [comment]
Ok, First, here is a picture of what I mean when I say activate the renderman plugin. In blender the renderman tools will not show until the plugin is active. You can get to the user preferences by pressing control-alt-u
![uishow](https://cloud.githubusercontent.com/assets/9410101/8949168/c2e820c2-357d-11e5-80ce-3cfe29b41849.jpg)

**Comment by bmbjr59** [comment]
nope I don't have this at all when I hit the add ons I have a whole list of them ,even on all no renderman there,shows a bunch of other stuff though

**Comment by bmbjr59** [comment]
this is what I have
![addon](https://cloud.githubusercontent.com/assets/13548497/8949254/6dd5f5e8-3576-11e5-98df-4afba30ec82b.JPG)

**Comment by MWY3510** [comment]
Did you try searching for it? Type PRman into the search box. Did you follow the instructions in the installation.txt file?

**Comment by bmbjr59** [comment]
this is what I get
![blank](https://cloud.githubusercontent.com/assets/13548497/8949293/34457ba4-3577-11e5-874e-609c955235b5.JPG)

**Comment by bmbjr59** [comment]
txt file goes im not too sure about that

**Comment by MWY3510** [comment]
Sorry, I just wanted to get the easy answer out of the way first. As for the file, I just wanted to know if you installed the plugin according to the instructions in that txt file.

**Comment by bmbjr59** [comment]
as far as I can tell I did ,I got all of the files,ect put them in as far as the text file goes I just now looking for it I cannot seem to find it

**Comment by bmbjr59** [comment]
i was looking at some notes that i got as i was getting this stuff if was a standard instillation i shouldn't have to do anything ,which it was ,im of the opion to let windows put it where it needs to go,so i have been doing stuff that way for years

**Comment by bmbjr59** [comment]
this computer i use,it crashed on me several months ago & i had a new drive & updated the  ram on it since igot it back sometimes it does some odd things on top of it i just moved as well,i got my computer back then the following week i moved don't know if that would have anything to do with it thought it might be worth a mention though

**Comment by MWY3510** [comment]
Ok, How I install the plugin is like this. First, download the zip file from github. Second, extract the zip into whatever folder you want. Third, locate the folder that has the .py files in it you want to move this folder. Fourth, locate where you installed blender at (in my case it is C:\Program Files\Blender Foundation\Blender-2.75a  .) Fifth, go into the addons folder (my full path C:\Program Files\Blender Foundation\Blender-2.75a\2.75\scripts\addons  .) Sixth, Put the folder you located in step three into the addons folder. Seventh, startup blender and activate the addon.

Let me know if this works for you.

**Comment by bmbjr59** [comment]
i got all of this ,let me go & check this from blender part ,i will see if i did the rest of it will be back shortly

**Comment by MWY3510** [comment]
Just wanted to let you know that I will be out until tomorrow. If that solution does not work please post any additional problems or information you might have. Ether I or someone else will reply as quickly as possible.

Have a great day,
MWY3510

**Comment by bmbjr59** [comment]
ok i checked all of this did not solved the problem ,but i have some more info here that will follow

**Comment by bmbjr59** [comment]
![blender1](https://cloud.githubusercontent.com/assets/13548497/8950152/17c18818-3583-11e5-97d8-9325c7cda6fc.JPG)
this is what i do to find renderman in blender

**Comment by bmbjr59** [comment]
picture on the far right is to show you that's its there

**Comment by bmbjr59** [comment]
![addon2](https://cloud.githubusercontent.com/assets/13548497/8950178/65e1ad66-3583-11e5-85c0-5f028fb3ea08.JPG)
i just don't get it,going to call it a night as well its late where im at

**Comment by MWY3510** [comment]
Try removing the -master from the folder name.

**Comment by jdent02** [comment]
Actually you don't have to remove the -master.  I never have and it works fine.

**Comment by MWY3510** [comment]
Sorry, I wasn't thinking when I got up. jdent02 is correct the -master will not make a difference. Something that might be causing a problem though is if you have another folder between the folder with the .py files and the folder in the addons directory. Like so,  addons/PRMan-for-Blender-master/PRMan-for-Blender-master/init.py  it should be addons/PRMan-for-Blender-master/init.py .

**Comment by bmbjr59** [comment]
sorry i had to work ,when i get off because of the wack-ball hours i work i tend to sleep for a while
you was right it was a folder within a folder so i got rid of 1 of them ,its still doing the same thing its still not showing up
another thing,before i forget again the version of blender i have its saying its 2.75, not "a" i dont know if would have anything to do with it

**Comment by bmbjr59** [comment]
before i started to ask about my problem here, i asked about it on the renderman site its been sugguested that you can download it here as well.
where i got renderman from in the 1st place was i got it from pixar site at the time i got it ,i dinnt have any 3d program at all ,no maya,blender nothing after i got it thats when i found out you needed something like that to make it work ,thought it was a standalone thing ,so i found out about blender , dinnt want to use maya, last version i used was 7 i could never figure out how to use it, so i got blender ,from what i have seen as of yet i havnt made with anything with it yet, but i can make stuff , i have been watching a ton of stuff on you tube about it.
is it possible the way i did everything ,which i think its backwards now ,causing my problem ?
otherwords downloaded renderman,installed it,downloaded blender installed it

**Comment by bmbjr59** [comment]
where i got blender from im not sure but its not from here

**Comment by bsavery** [comment]
Hi.  the order of installation and where to get everything should be right here:
https://github.com/bsavery/PRMan-for-Blender/blob/master/installation.txt

**Comment by bmbjr59** [comment]
hi
sorry been working again & have had my grandkids here so quiet is not in their job description to say the least
they are not here today & had some quiet time since i got up ,i h ave looked for some of that "rmantree" mentioned in the how to stuff,i don have that ,nor does it have the other either $RMANTREE/bin

**Comment by MWY3510** [comment]
Hello again,

The $RMANTREE refers to an environment variable. These can be found in the start menu by typing in environment and clicking on "Edit the system environment variables" button. You can look at this for pictures and more information. https://renderman.pixar.com/forum/showthread.php?s=&postid=166400#post166400

**Comment by bsavery** [comment]
Still an issue?

**Comment by bmbjr59** [comment]
yeah i just aint had the time to see what else to do with it,i have been slammed at work since school started around here ,get up for a while heard out the door again,then around here they had wreck around here it wiped out everybodys internet for a couple of days,its there but it just will not show up i have done this like it was supposed to be done ,im beginning to think im going to have to take this to the shop where i had all the hardware  updates done to it,guy is real smart with this stuff,its getting more than i know what to do with,been doing bussiness with him for years

**Comment by MWY3510** [comment]
bmbjr59,

I hope you can get this resolved. We'll keep this issue open for a few more days if you need to ask any other questions.

MWY3510
