### ISSUE TITLE
Metaballs/Blob support

### ISSUE THREAD

**Issue by rendermouse** [bsavery/PRMan-for-Blender#70]
Blender Metaballs are not currently exported, so I decided to try and implement this as a way for me to learn more about coding for Blender and Renderman. I figured I'd create a GitHub issue to track progress and be able to discuss metaball solutions with all of you experts.

I have a fork of the plugin with a modified export.py that outputs all Blender Metaballs to the primary RIB as a single Blobby/Implicit Surface definition. If you're curious, you can find the fork here:
https://github.com/rendermouse/PRMan-for-Blender

I am having trouble attaching shaders to these implicit surfaces, and could really use some suggestions. I tried using the _mpoint_ method stated in [this Pixar appnote](https://renderman.pixar.com/resources/current/RenderMan/appnote.31.html), but have yet to produce results.

![image](https://cloud.githubusercontent.com/assets/1102555/8960685/3d0beeb8-35df-11e5-9fde-e9a0177fcfcd.png)

**Comment by MWY3510** [comment]
Hello Andy great to have you on board,

Your work looks pretty good. I have not gotten a chance to look at the code but the exporter works well. For the material, I have gotten this to work by applying the shader directly before the Blobby definition. I don't honestly know why the Read archive call is not working (paging bsavory.) As for the differing colors in the appnote I don't think that it is supported in RIS rendering (the note was written for REYES rendering.) It may not be pretty but the material is working.
![meta](https://cloud.githubusercontent.com/assets/9410101/8961491/87eb4e48-35e3-11e5-87d1-0bad4cbd9075.jpg)

**Comment by MWY3510** [comment]
Never mind I figured out why the read archive was not working. You need to have a call to tell the read archive system where the arcive is first. Like so (ReadArchive "C:\\Users\\_____\\My Documents\\prman_for_blender\\MetaTest1/archives/static/materials.rib") Underscore added.

**Comment by bsavery** [comment]
Awesome!  Thanks andy.  I can integrate the code today.

**Comment by rendermouse** [comment]
I should note that I had to set the "Threshold" of each metaball in my Blender scene to 0.800 in order to get it to match the PRMan metaball sizes. I could not figure out how to tell PRMan to adjust that param blob by blob.

**Comment by rendermouse** [comment]
Also, for PRMan renders, we could show a "Volume" checkbox in the Blender Metaball properties panel.  This would set the RIB opcode to 8 instead of 0. [reference](http://renderman.pixar.com/resources/current/RenderMan/volume_rendering.html#riblobby-support)

**Comment by bsavery** [comment]
Sorry, I'll integrate this tomorrow.

**Comment by rendermouse** [comment]
MWY, thanks for the tip! Your example helped me get the blob material working. Sooooo happy right now.  

Right now it just grabs the material from the first blob it finds and uses that for the whole set.  

I committed this fix and then merged latest from Brian into my repo.

**Comment by MWY3510** [comment]
Glad to be of help. I will love to see meta object export support in this plugin. Thank you for working on this.

MWY3510

**Comment by rendermouse** [comment]
Next, I'll see if I can split metas into "families" as Blender calls them, for export. [reference](http://www.blender.org/manual/modeling/metas/editing.html#object-families) This would allow for multiple groups of blobs to each have their own shader and influence.

**Comment by bsavery** [comment]
Can you attach the scene with the blobbys?  Just a bit busy here to recreate it.  Thanks!  Working on integrating.

Brian

**Comment by rendermouse** [comment]
Here's a scene with a single set of blobs shaded with PxrGlass:
https://www.dropbox.com/s/yrjvg20zfom0lj4/rman_blob.blend?dl=0

**Comment by rendermouse** [comment]
I added support for outputting metaball families as separate Rman blobbies. I committed my changes and pushed my repo:
https://github.com/rendermouse/PRMan-for-Blender

Sample multi-family scene:
https://www.dropbox.com/s/q5raf3s7sj8g3l3/rman_blob_families.blend?dl=0

One family:
![image](https://cloud.githubusercontent.com/assets/1102555/9000906/554faad4-371d-11e5-823e-574c2d0b940b.png)

Two families:
![image](https://cloud.githubusercontent.com/assets/1102555/9000951/21eeb350-371e-11e5-8471-da89b9256ab6.png)

**Comment by MWY3510** [comment]
Do you mind if I merge your changes into my branch and clean it up a little bit before pushing it into the master?

**Comment by bsavery** [comment]
I'm actually working on a fairly epic code cleanup/rewrite of the export
code that I'm hoping to get done this weekend. That code has gotten to be a
mess...

On Friday, July 31, 2015, MWY3510 <notifications@github.com> wrote:

> Do you mind if I merge your changes into my branch and clean it up a
> little bit before pushing it into the master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/70#issuecomment-126725858>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
But if you want to merge and push go ahead. Should overlap a little bit.

**Comment by rendermouse** [comment]
I won't be able to work on this stuff again for a few days.

**Comment by bsavery** [comment]
Cool.  I'll take your latest and integrate it this weekend with the export code rewrite.

**Comment by bsavery** [comment]
This looks great so far!  Nice work. 

The only thing I think could be improved is the family naming.  My understanding is you use the ob.name to set the family.  What if we added an object property for blobby family and material (and only show when meta type)

Or is that naming convention the way blender normally makes blobbys?

Brian

**Comment by rendermouse** [comment]
That crazy dot syntax is how Blender decided to do it. More info about that here:
http://www.blender.org/manual/modeling/metas/editing.html#object-families

**Comment by bsavery** [comment]
Wow... so if you make a typo when changing the object name it doesn't work?

**Comment by rendermouse** [comment]
That is correct. Also, if you want to move 75 metaballs to a separate family, you get to rename each and every one of them.

**Comment by MWY3510** [comment]
Ha ha, this is funnest thing I have read all day. Thanks for the laugh rendermouse. But in all seriousness not the best way of doing things.

**Comment by rendermouse** [comment]
Yeah, not the best way. But I felt that I had to follow the existing Blender convention, in order to maintain compatibility with existing Blender metaball projects.

**Comment by rendermouse** [comment]
I'm obviously open to any improved solution.  :)

**Comment by MWY3510** [comment]
Currently I think that the solution you have is fine. The problem lies with the blender method not your decision to maintain compatibility. Still quite funny though.

**Comment by bsavery** [comment]
Let me know if the merge works for you!

**Comment by rendermouse** [comment]
Ok, I can check tonight.

**Comment by rendermouse** [comment]
Metaball positions are not correct in the RIB output. I'll take a look.

**Comment by rendermouse** [comment]
The Mball RIB is correct. The main RIB is including a transform on the Blobby that doesn't need to be there, because the same transform is also written to the blobs in the MBall RIB.

**Comment by rendermouse** [comment]
I added a check that prevents writing the object transform to the main RIB for metaballs. This fixed the positioning issue in both static and animated scenes.

**Comment by rendermouse** [comment]
Created pull request for this fix.
