### ISSUE TITLE
Issues with recent IPR commits

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#71]
Bug with new IPR features:

Opened my material test, activated IPR.  Got this error but it still launched:

X00002 {ERROR}   Plugin error: PxrPathTracer: invalid parameter sampleMode).  

Went to the node editor and added in a LMLayer node.  IPR did not refresh to show the new inputs.  Went to select the material tab and Blender crashes.

Log:
Error: EXCEPTION_ACCESS_VIOLATION
R05004 {WARNING} RiEnd called before its proper nesting level.

C:\Program Files\Blender Foundation\Blender>An application exception has occurre
d in PRMAN.EXE.
  Error codes: 0x0000006D75696465 0xC0000005 0x00000000 (0x00000008) (0x75696465
)
*** exception ***

If the material tab is already open when IPR is launched, trying to add a node in the node editor gives me this:

WM: failed to allocate texture for triple buffer drawing (out of memory).
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.75\scripts\modules\nodeite
ms_utils.py", line 99, in draw_node_item
    item.draw(item, col, context)
AttributeError: type object 'RendermanOutputNode' has no attribute 'draw'

After that I tried different ways of adding and removing a LMLayer.  Adding the layer in the material tab triggers a refresh in IPR and shows the new shading.  Deleting the layer in the material tab (by selecting 'remove' in the dropdown) does not trigger a refresh.  After creating the LMLayer in the material tab, clicking on the node in the node editor crashes Blender with this error:

Error: EXCEPTION_ACCESS_VIOLATION

C:\Program Files\Blender Foundation\Blender>R05004 {WARNING} RiEnd called before
 its proper nesting level.
An application exception has occurred in PRMAN.EXE.
  Error codes: 0x000000006D756964 0xC0000005 0x00000000 (0x00000008) (0x6D756964
)
*** exception ***

Close to the same, but one different error code.......

**Comment by bsavery** [comment]
X00002 {ERROR} Plugin error: PxrPathTracer: invalid parameter sampleMode).  
This sounds somewhat suspect.... What's your RMANTREE set to?

**Comment by bsavery** [comment]
To be more clear sampleMode is definitely a parameter of PxrPathTracer...

**Comment by jdent02** [comment]
RMANTREE is C:\Program Files\Pixar\RenderManProServer-20.0\

**Comment by jdent02** [comment]
Windows 7 if it helps.  I'm running a Linux Mint OS as well but I haven't tried this on that one yet.

**Comment by bsavery** [comment]
I don't have a windows machine at home to test on...  Can you verify on linux?

**Comment by jdent02** [comment]
Sure.  Give me a bit.

**Comment by MWY3510** [comment]
I can confirm that this error happens on windows 7. I do not have time to do extensive testing tonight but I get the same error as jdent02. For me interactive rendering refreshes before blender crashes.

**Comment by bsavery** [comment]
I offhandedly noticed a crash consistantly once when you do IPR with the surface preview window open.  Any chance that was the case?

**Comment by jdent02** [comment]
Got it to crash under identical circumstances (adding a LMLayer node in the node editor).  No IPR refresh occurs.  Selecting the material tab crashes Blender with the following error:

R05004 {WARNING} RiEnd called before its proper nesting level.
*** received SIGSEGV ***

And no, I did not have the surface preview open on either system due to that bug.

**Comment by bsavery** [comment]
Ayite.  I see this too.

**Comment by bsavery** [comment]
Alright.  So here's whats happening.  For some reason blender is calling the update method for the RenderEngine after interactive has started which is basically stomping on ri contexts.  It's actually a similar problem to the above described issue with having the preview panel open... basically the same exact problem.  

I'm going to put in a quick fix tonight.  And fix it for real tomorrow.  Leaving this open.

**Comment by bsavery** [comment]
Basically prman doesn't like 2 RI contexts going from the same thread.

**Comment by bsavery** [comment]
Did that works for you guys?

**Comment by jdent02** [comment]
Sorry Brian, I didn't get a chance to try it out this morning.  I can give it a spin this evening...

**Comment by jdent02** [comment]
Quick test with Windows and it looks like the problem was fixed.  I tried multiple additions and removals of LMLayer nodes through both the material tab and the node editor and the IPR refreshed with the new material and didn't crash Blender.  Opening the preview window in the material tab didn't cause a crash either.  Nice work Brian.  Will test Linux later this evening.
