### ISSUE TITLE
multiple materials regression

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#75]
Can't use light emission on objects with multiple materials.  Basically an object can have multiple materials on it, but if you enable light emission on any of them (by using PxrStndAreaLight) the material goes black and does not emit light.  It used to work but something broke in the last few days of updates.  Solo material light emission works fine.

Also something is up with mesh exporting.  I created a sphere and no matter what settings I use (export smooth normals, setting the export to subdivision mesh), I get a faceted sphere when rendering if multiple materials are used.  With solo material export works fine.

Edit: I downloaded the latest version about an hour ago.

Photos:
Multi material with emission on lower part of sphere:
![multi material light](https://cloud.githubusercontent.com/assets/13521172/9016647/4bc8bb92-3798-11e5-9cf0-82849f564616.png)

Multi material with no emission:
![multi material plastic](https://cloud.githubusercontent.com/assets/13521172/9016666/66ac4672-3798-11e5-8808-a9ca2a954fb9.png)

Solo material with emission:
![solo material](https://cloud.githubusercontent.com/assets/13521172/9016675/73ddf304-3798-11e5-8715-57ea8b6e33ca.png)

Faceted sphere with multi material:
![multi material facet](https://cloud.githubusercontent.com/assets/13521172/9016685/828204f4-3798-11e5-9b76-7028d831a756.png)

Smooth sphere with solo material:
![solo material](https://cloud.githubusercontent.com/assets/13521172/9016718/c11bd884-3798-11e5-896b-d5977edc7db8.png)

**Comment by jdent02** [comment]
More stuff:
It appears that when light emission is enabled the exporter is converting that material to a holdout.  Here's what I got when I put an HDRI backdrop in and set up one of the two materials on Suzanne to be an emitter.

![hole](https://cloud.githubusercontent.com/assets/13521172/9018476/d5266324-37a4-11e5-9468-ca6cdd39dc54.png)

**Comment by bsavery** [comment]
Yes.  I'm aware.  Actually should take care of that this weekend:

https://github.com/bsavery/PRMan-for-Blender/issues/73

BTW did this EVER work correctly?  Perhaps it did, I did change the multi-material export recently.

**Comment by jdent02** [comment]
The emitter thing did work a while back since I took the Cornell box demo and added in a light in the ceiling using multiple materials. Not sure about the mesh export one though.  I had never tried that before

**Comment by bsavery** [comment]
Light emission doesn't work on multis still but the subdiv should work on them now.

**Comment by jdent02** [comment]
Great!  Will test this one as well.

**Comment by jdent02** [comment]
Worked for me.  I created a sphere with multiple materials and successfully exported a subdivision object.  Again, nice work Brian.
