### ISSUE TITLE
OSL shaders are not supported by interactive rendering mode.

### ISSUE THREAD

**Issue by MWY3510** [bsavery/PRMan-for-Blender#76]
Currently I have tried a number of different syntax options to point PRMan to the shaders. So far the only one that works with the engine is ./shaders:@ any other including the full path will give a shader not found error. Interactive rendering will not accept any version of this. Let me know if you need any more information.

**Comment by bsavery** [comment]
Does my latest changes for this work for you?  You were adding spaces to the search path which is a no no.

**Comment by MWY3510** [comment]
Thanks for the information about the search path. So far, your and my attempts at getting interactive rendering to accept osl has resulted in the same error message. (Plugin Error: Could not open shader "shader name" [File "file name" could not be found.])

**Comment by bsavery** [comment]
Can you paste the search path in your scene.rib file?

On Friday, July 31, 2015, MWY3510 <notifications@github.com> wrote:

> Thanks for the information about the search path. So far, your and my
> attempts at getting interactive rendering to accept osl has resulted in the
> same error message. (Plugin Error: Could not open shader "shader name"
> [File "file name" could not be found.])
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/76#issuecomment-126854788>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
Sure, 
This works ["./shaders:@://C/Program Files/Pixar/RenderManProServer-20.0/lib/RIS/pattern://C/Program Files/Pixar/RenderManProServer-20.0/lib/RIS/bxdf://C/Program Files/Pixar/RenderManProServer-20.0/lib/rsl/shaders://C/Program Files/Blender Foundation/Blender-2.75a/2.75/scripts/addons/PRMan-for-Blender/shaders"]

This does not work ["//C/Users/____/My Documents/prman_for_blender/Advanced3//shaders:@://C/Program Files/Pixar/RenderManProServer-20.0/lib/RIS/pattern://C/Program Files/Pixar/RenderManProServer-20.0/lib/RIS/bxdf://C/Program Files/Pixar/RenderManProServer-20.0/lib/rsl/shaders://C/Program Files/Blender Foundation/Blender-2.75a/2.75/scripts/addons/PRMan-for-Blender/shaders"]

Underscore added in place of my username.
Removing or moving the colons or @ 's don't change anything.
Now that I think about it do you think the colon after the drive letter might make the difference?
Anyway I'm going to bed so have a great evening.
