### ISSUE TITLE
Env map is reversed

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#78]
I didn't see this one mentioned.

Seems like env maps are mirrored from how they appear in Cycles.  I don't see a way of flipping the texture

examples:
![prman](https://cloud.githubusercontent.com/assets/13521172/9021858/3f6e4866-3820-11e5-902a-25ef1495ab25.png)
PRMan render

![cycles](https://cloud.githubusercontent.com/assets/13521172/9021859/4edf9e26-3820-11e5-998e-459227333ca5.png)
Cycles render

**Comment by MWY3510** [comment]
This may sound hackish but you can scale the environment light to negative one X. This produces a flipped texture. Not the best solution but effective

**Comment by jdent02** [comment]
That hack didn't work for me.  Even tried checking 'always recompile textures' in the options tab.

**Comment by jdent02** [comment]
Hold up, might have been user error.  I think I made a mistake with the hemi lamp settings.  I deleted the existing one, added a new one and rendered.  Now it's matching up with Cycles after a 90 degree rotation along the Z axis.  Sorry for the false issue.

**Comment by bsavery** [comment]
Yes i should be flippig by default...
