### ISSUE TITLE
Blender crashes when launching interactive render

### ISSUE THREAD

**Issue by matthewphilyaw** [bsavery/PRMan-for-Blender#79]
I at first thought this was when any time that the preview material is render, but it seems to crash when you first load blender and the materials are initializing and the previews are rendering. i have noticed though if I wait till the preview shows up then render it doesn't crash. 

I will try to get a sample scene where it does it reliably to give more detail.

**Comment by bsavery** [comment]
Have you synced the latest updates?  Should have fixed IPR crashing when preview material is open

**Comment by matthewphilyaw** [comment]
Looking at change log I have the latest as of 7/31 that contains the merge from the pull request as well.

I'm using Blender 2.75a and running mac os x 10.10.4 -- it seems to only be when I load a scene and seems like it goes through and loads the materials, actually I need to check but it was a cycles scene at one time so perhaps the conversion is in process not sure, but have saved it since I switched Renderman. 

I could not reproduce it by adding a new material and hit interactive render while the preview is blank, it seems to work with out crashing that way. I will see if I can't provide a scene that does it reliably. Don't mean to be as vague, I know it will help to see it.

**Comment by matthewphilyaw** [comment]
https://drive.google.com/file/d/0B1GplrdFdoo-TTlROG5oZ1BEem8/view?usp=sharing

Took the default scene, simply changed the default render and saved it. Click new scene, so resets to the default scene, open the file and clicked interactive render and it crashes. Note that the preview section is blank, no black box or anything, then once it turns black and renders I can click interactive render and it works no problem.

**Comment by bsavery** [comment]
I think this is somewhat related (or the fix will be) to the switching scene while IPR is running.  Basically we need to remove the menu item, I guess, if the render engine isn't prman.  And do some cleanup if changing files if ipr is running.

**Comment by bsavery** [comment]
Fixed.
