### ISSUE TITLE
can't stop interactive renderer if left on and start a new scene

### ISSUE THREAD

**Issue by matthewphilyaw** [bsavery/PRMan-for-Blender#80]
Noticed this as well:
* Take default scene (using it for example)
* Switch to render man
* click the start interactive button in blender
* close the IT window (optional, don't think it will change the out come, but what I was doing)
* do NOT stop the interactive renderer in Blender
* Start a new project
* Switch to renderman
* Notice that it still asks you stop the interactive renderer, if you click it you get the error below. 

I have to close Blender for this to go away.

Traceback (most recent call last):
  File "/Applications/Blender/blender.app/Contents/Resources/2.75/scripts/addons/PRMan-for-Blender-master/operators.py", line 142, in invoke
    bpy.app.handlers.scene_update_post.remove(engine.ipr.issue_transform_edits)
ValueError: list.remove(x): x not in list

location: <unknown location>:-1

Traceback (most recent call last):
  File "/Applications/Blender/blender.app/Contents/Resources/2.75/scripts/addons/PRMan-for-Blender-master/operators.py", line 141, in invoke
    bpy.types.SpaceView3D.draw_handler_remove(engine.ipr_handle, 'WINDOW')
ValueError: callback_remove(handle): NULL handle given, invalid or already removed

location: <unknown location>:-1

Blender (hash): c27589e
Renderman: 20.1 and renderman for maya 2016 I think. 
PRman: 92933cfd4f

**Comment by bsavery** [comment]
Fixed.
