### ISSUE TITLE
How is renderman for blender installed

### ISSUE THREAD

**Issue by mknorr** [bsavery/PRMan-for-Blender#81]
Hi,
I just tried to follow the instructions. I d/l the PRMan-for-Blender-Master.zip and unzipped it in the addons folder. I keep getting an error message Unable to process "PRMan-for-Blender-master\"

I then unzipped it into an empty folder on the desktop and moved the contents to the addons folder.
When I start blender and go to addons to enable it, I see the render: PRMan Render Engine. Trying to check the box right of the stick figure lists all these errors. I assume this has something to do with the Pixar file.

The README.md says to "download this project" but it's a zip file not a project.

The renderman file from Pixar doesn't do anything as it is an stl file so cannot be run like an exe could.

If anyone has some clear instructions on installing this, I'd really appreciate it.

**Comment by MWY3510** [comment]
Hello mknorr,

It sounds like you installed the blender add-on but not Renderman Pro Server. It is available from Pixar's site http://rendermansite.pixar.com/view/get-renderman. It would also be helpful to have as screen shot of the errors you are getting in Blender.

Have a great day,
MWY3510

**Comment by mknorr** [comment]
Thanks for your reply MWY3510.

Yes, this is probably my issue. I don't know how to run it when it keeps insisting to save as an STL. I even downloaded it on my iPad and forwarded it as an email attachment. On the iPad it was an MSI but the attachment was an STL again. What type of file should it be and how do I show it in win7?

**Comment by MWY3510** [comment]
Great, let me know if you need any more assistance.

**Comment by bsavery** [comment]
Still an issue?
