### ISSUE TITLE
Proposal for multi-material objects

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#83]
So I've been working over how to create multi-material meshes when rib exporting.  Previously we were creating new meshes (1 per material) adding them to bpy.data exporting, then emitting each rib separately with the corresponding material.  Ok fine, this worked, however it split up meshes, which I claim may have issue on subdiv meshes.  Also seemed to have issues with UV, as well as scene updates which were slow on big scenes.

I have a proposal that seems to work with only ONE (biggish) downside.  It won't support emissive geometry on multi-materials, yet.

Here's the trick.  Just emit the geometry as for a normal object, emit a per face material id primvar.
Emit all the Bxdfs/materials for the geometry, then use the PxrBxdfBlend (keying the mask parameter off the material id primvar) to switch between the Bxdfs.  

I could probably even write a light shader .sl to do the same thing fairly easily as well to make it support multiple materials objects that also have emmissivity in them.  But for now we could give the caveat to not use emmisive multi-material Objects.  

Thoughts?

**Comment by bsavery** [comment]
BTW I should mention the bxdfblend hookup would all happen behind the scenes.  If that wasn't clear.

**Comment by jdent02** [comment]
As far as I'm concerned, as long as the no emissive multi material limitation is known about and communicated, it can be worked around.  From the sound of it, your solution will solve a number of other problems that are more frequently encountered anyway.

**Comment by bsavery** [comment]
Exactly.  And I think I can write a shader to deal with emmisivity anyway.

**Comment by MWY3510** [comment]
I like this idea. It is unfortunate that there is a downside, but if there has to be one that is ok. Great job Brian!

**Comment by bsavery** [comment]
Works like a charm... 
![untitled](https://cloud.githubusercontent.com/assets/1892220/9031450/ff4f20f4-3967-11e5-8950-0d5b968d3a7f.jpg)

**Comment by bsavery** [comment]
Here's the shader rib for anyone interested:

Pattern "PxrPrimvar" "read_material_id" "string varname" ["material_id"]
Pattern "PxrSeExpr" "mat_mask_0" "string expression" ["$input == 0"] "reference float input" ["read_material_id:resultF"]
Pattern "PxrSeExpr" "mat_mask_1" "string expression" ["$input == 1"] "reference float input" ["read_material_id:resultF"]
Bxdf "PxrBxdfBlend" "multi_material" "reference bxdf[2] lobe" ["Material.PxrGlass" "Material.001.PxrDisney"] "reference float[2] mask" ["mat_mask_0:resultF" "mat_mask_1:resultF"]

PointsPolygons [4 4 4 4 4 4] [0 1 2 3 4 7 6 5 0 4 5 1 1 5 6 2 2 6 7 3 4 0 3 7] "uniform float material_id" [0 0 0 1 0 0] "P" [1 1 -1 1 -1 -1 -1 -1 -1 -1 1 -1 1 0.999999 1 0.999999 -1 1 -1 -1 1 -1 1 1]

**Comment by jdent02** [comment]
Is that bxdf blend available in the add on?  I see a few different mixers and layer nodes but they're all rgb color operators. It would be great to be able to blend different Disney bxdf's using a noise pattern or similar

**Comment by bsavery** [comment]
So here's the other "hitch" with this plan.  BxdfBlend is a bit "deprecated" in PRMan 20.0 and is hidden by default.  I can make it available for multi materials, but with the scenario you describe BxdfBlend doesn't really work (it does work ok if you have masks that only 0 or 1 like above)

You should use the PxrLMMixer and mix layered PxrLM materials, or if you want to use PxrDisney, the bxdf is designed around the principle of mixing inputs, not the bxdf.  https://disney-animation.s3.amazonaws.com/library/s2012_pbs_disney_brdf_notes_v2.pdf

Furthermore I might even edit the BxdfBlend node specifically for using with this multi-material scenario in mind and put it in the blender addon distribution.  If done correctly we could take out the seexpr nodes described above...

**Comment by jdent02** [comment]
Good to know on the BxdfBlend.  

There's an implementation of the Disney BRDF in another renderer that I play around with and they have it explicitly set up as a layer based system so I just assumed that this was the way it was supposed to work, as opposed to their own interpretation of it.  My bad.

if the BxdfBlend is deprecated it probably should remain hidden as it is now, especially since Pixar seemingly prefers we use the LM system instead.

**Comment by bsavery** [comment]
Ha, layering materials is a topic that we could debate for months.  Luckily here we're merely "switching" between bxdfs

**Comment by jdent02** [comment]
More than happy to leave that debate up to the people who do this stuff for a living, not cowboy hobbyists like myself :)

Playing devil's advocate here, but if the BxdfBlend is deprecated, is that going to cause issues with your multi material switch solution down the line?

**Comment by bsavery** [comment]
I'm probably going to rewrite it for specifically this purpose, and put it in the github distribution as "BxdfSwitch" (or BxdfSelect)

**Comment by MWY3510** [comment]
Sounds great. Just a note you might have to adjust the code for detecting shaders in the plugin's directory to prevent the user from using it in the material editor (displacement tab.) This is shaping up to be great!

**Comment by bsavery** [comment]
Leaving this open as I still want to get that bxdf rewritten.  Anyone want to learn to write bxdfs? ;)

**Comment by MWY3510** [comment]
Yes please. I have a basic understanding of the api and I mostly know how the PxrConstant shader works so any more information would be great!

**Comment by jdent02** [comment]
Just a note of a bug I've found with the new multi material export and IPR.  Everything looks fine at first, but if you add or delete any nodes on the material that you're editing the entire object will then show that material (other materials appear to get overridden when the refresh is triggered).  I have to restart IPR to get the rest of the materials back.  This bug does not happen if you only edit parameters (such as color).

**Comment by bsavery** [comment]
So coming back around here.  In the near future with renderman the way to do things like this is to use hierachical subdivs for multi material shader attachments (and keep the way we're doing on polys).  I'm going to rename the issue.
