### ISSUE TITLE
Unable to enable in Blender 2.75

### ISSUE THREAD

**Issue by ericdraws** [bsavery/PRMan-for-Blender#84]
Earlier today, I was able to enable Pixar's Renderman add-on for Blender 2.71. I then decided to update to Blender 2.75, but when I tried re-enabling Renderman, I got this message:

![blender](https://cloud.githubusercontent.com/assets/13623405/9036339/a6cad99a-39ae-11e5-98ef-a81decf952c3.jpg)

I've been able to get Renderman to work with previous versions of Blender up to 2.74.

**Comment by bsavery** [comment]
Did you install a 32 bit version of blender perhaps?  That's what that error implies...

**Comment by ericdraws** [comment]
Nope, I've tried reinstalling v2.75 64 bit twice to double check, still nothing.

**Comment by bsavery** [comment]
Or you don't have a 32 bit version of windows?

**Comment by ericdraws** [comment]
I'm running the 64 bit version of Windows 8.1 for sure.

**Comment by bsavery** [comment]
Hmm, I'm not sure then.  The only time I've seen that error is either in a 32 bit version of windows or blender.

**Comment by bsavery** [comment]
Still an issue?

**Comment by ericdraws** [comment]
Yeah, I've switched back to 2.74 for the time being.
