### ISSUE TITLE
Improvment: Seperate AOV passes for each light/object

### ISSUE THREAD

**Issue by MWY3510** [bsavery/PRMan-for-Blender#85]
As described in this post https://renderman.pixar.com/forum/showthread.php?s=&threadid=28622 , the ability to add separate AOV passes for each object/light. I probably will not get the time to do this in the near future so if anyone wants to take a swing at it be my guest.

**Comment by bsavery** [comment]
Here's a hint... light groups:
https://renderman.pixar.com/resources/current/RenderMan/risLPEs.html#light-groups

**Comment by MWY3510** [comment]
Thanks bsavery, I am continually amazed by the information in the renderman documentation that I have not read yet.

**Comment by jdent02** [comment]
Thanks for putting this on the list!

**Comment by bsavery** [comment]
Overlaps with this issue:
https://github.com/bsavery/PRMan-for-Blender/issues/98

**Comment by bsavery** [comment]
In that I'm not sure on a good way to add "passes" to blenders renderlayers

**Comment by jdent02** [comment]
What are you referring to as passes?  Isolated light passes like mentioned above or element passes like direct diffuse shading?

**Comment by bsavery** [comment]
Prman gives you the ability to do both. Rgba per light or direct diffuse
per light. I suppose the simple way to implement this would be to add a
"light group" property to each layer so you could set per layer which
lights to use.

On Monday, August 17, 2015, jdent02 <notifications@github.com> wrote:

> What are you referring to as passes? Isolated light passes like mentioned
> above or element passes like direct diffuse shading?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/85#issuecomment-132014079>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
Just spitballing here but there is already a text box for each light that allows you to assign it to a light group (or so the helper says).  You could add some options to the passes section that tells PRMan whether or not to save these light group AOV's during rendering and what elements of the light group (diffuse, specular, indirect, etc...) to use.  

The layer assignment box at the top of that tab is traditionally used to isolate objects and lights for later manipulation in the compositor, but it creates these images by invoking the render engine for each layer one at a time, not by rendering once and then separating the render data into AOV's.

I hope this rambling makes sense.

**Comment by bsavery** [comment]
Hmmm yes that's a very good point/thought.  I'll have to think up a good ui for this.  Basically what I'm thinking is a section per render layer for "per-light group aovs".

**Comment by jdent02** [comment]
That could work, so long as a user is allowed to access and output any combination of groups in a layer.  Being that the current layer system renders each layer sequentially, there wouldn't be much benefit in allowing only one light group per layer.

I thought a bit more about the idea I mentioned above.  I'll just toss it out there and you can determine if any of it is useful.  I apologize for not being able to provide any pictures or mockups, but I'm no good at writing code.

The customization options of AOV's would make using dropdown menus risky, since the interface could easily get cluttered if too many groups are created or if a user wants to assign a light/object to several groups.

So the answer is to keep the current method of assignment, which is typing a group name in the object/light text box.  Multiple group assignments can be separated by a comma or similar mark.  the user will have to mind spelling and caps, but that shouldn't be too much to ask.

In the render layer panel a new section called 'AOV' is added.  You can create any number of AOV's and title them in this panel.  When an AOV is selected, three text boxes appear (light groups, object groups, lighting elements) as well as a section for specifying the output format and location.  A user can then enter an arbitrary number of light/object groups and elements into the respective textboxes for each AOV (once again separating multiple entries by a comma).  it would be helpful if a list of the lighting elements was somewhere in this panel (maybe hiding behind a hover over point) since there are so many options and the Renderman documentation is a bit dense on what is available.

This type of setup would allow a user to largely bypass Blender's layer system (which IMHO is a relic of the scanline renderer and not very suitable for a modern path tracer) and render everything in one pass, and then split it out however they want.  It isn't the simplest way to go about it, but it gives you the most flexibility.

**Comment by bsavery** [comment]
I think we're thinking the same thing.... I'll see if I can mock that up today.

**Comment by bsavery** [comment]
So it turns out this is more difficult than I hoped. 

Here's the main problem.  SceneRenderLayers in blender are not extensible.  We can't add properties to a layer, but can add them to the scene.  For instance this is how the Holdout aovs are added.  However you can't add them per layer.  Kinda lame.  

So I could do what you describe above and basically bypass the render layer system, however you then would have issues when reading back in the render result both to the Image Editor and the compositor :(

**Comment by jdent02** [comment]
Yikes.  Legacy code strikes again.

I know the Luxrender guys have found a workaround for adding in the custom passes that their LuxCore engine supports, but their system isn't as customizable as PRMan's.  Basically they have the additional passes selectable in the layer tab.  When LuxCore finishes rendering, it loads all the selected passes as image files into Blender's UV viewer.  Those image files are then accessible from within Blender's compositor by using an image read node.  It works, but the system is a simple on/off toggle for each pre defined pass, there's nowhere near the same level of customization (hence why this solution may not work here).  Also, I don't know what the internal process of the exporter is, so there may be some fancy behind the scenes juggling to get around the layers limitation you described.

**Comment by bsavery** [comment]
I'll look at what they do.

**Comment by bsavery** [comment]
Ok I see, yeah and like I mentioned they are adding those extra light groups and passes to the Scene rather than the renderlayers which aren't customizable.

**Comment by jdent02** [comment]
Well, that would certainly reduce the options for integrating AOV's......

On the plus side, I don't see people complaining in the Lux forums about the way they handle the custom passes so they're approach seems to be acceptable to the community (or at least the ones that use Luxrender).  I think most users are aware that Blender doesn't play nice with some plugin features so they cut them some slack.

Maybe you could hide the AOV options behind an 'advanced' checkbox on the layer tab, and if a user activates it the layer assignment panel could be replaced with a warning that says something like "render layers cannot be used with RenderMan AOV's......."  Just an idea anyway...

**Comment by bsavery** [comment]
Ok I think I have a way to do this, basically this:

Custom AOV sets:  Each aov set will be a list of aovs to output.  Also each aov set can be attached to whatever layer you want - *ALTERNATIVELY* we could limit it to one aov set per layer.

AOVS:  Each aov set has a list of aovs, each aov has a channel name, type, or custom input:

![screen shot 2015-08-18 at 5 52 25 pm](https://cloud.githubusercontent.com/assets/1892220/9346483/4d5f735e-45d2-11e5-9c18-513935619680.png)

**Comment by bsavery** [comment]
![screen shot 2015-08-18 at 5 55 45 pm](https://cloud.githubusercontent.com/assets/1892220/9346493/668f2ce8-45d2-11e5-9200-941519de810c.png)

**Comment by bsavery** [comment]
BTW the type will be some set of standard predefined aovs.  

I'm kinda 50/50 on whether each layer should have it's own custom aov set or you can create one and share between all layers OR you could create as many as you want and attach them to whatever layers.  Obviously the last way is more complicated both to implement and work with, but most flexible.

**Comment by bsavery** [comment]
The other nice thing with multiple aov sets is that you could combine them all to one output:

i.e, output all the diffuse, spec, etc into one exr file with one aov set and then the shadow, reflection, etc in another aov set to another openexr file.  

Ok, I'll call it a day.  Thoughts?

**Comment by jdent02** [comment]
I'm a bit confused just looking at the mockup how it would work.  If you choose to make a single 'pool' of AOV's, how would they be assigned to the layers?  

I think I see how the AOV section works but I'd like to clarify: You can create a general AOV output (like diffuse) which would output everything on the layer, or specify a light group lpe using the 'custom' option?  That makes sense, but how would you do something like output only the diffuse element of, say, light group 'rim_light'?  Also, does 'combine the outputs' mean an AOV set would be exported as a multilayer .exr?

**Comment by bsavery** [comment]
Yeah, sorry for the stream of conciousness explanation, and maybe the names aren't very clear either.  Think of an "AOV set" as a file output.

Each AOV set could be assigned to any number of render layers.  I don't think I made that obvious in the ui.  That way if you had some aov set/output it could be turned on for any number of render layers.  I would imagine if had an aov set, you'd possibly want it on all layers or just some.

Further confusing the the layer terminology yes each aov set would be the equivalent of a multilayer openexr (which is a confusing term: http://blender.stackexchange.com/questions/16152/save-all-render-passes-to-a-single-exr-image)  but yes you would combine all aovs in an aov set to one openexr file.

And I didn't add it to the ui mockup yet but yes we could add per aov group or light group.

Does that make sense?

**Comment by jdent02** [comment]
Yep, it does.  Looks like a good start

**Comment by bsavery** [comment]
Maybe more clear terms would be to substitute "Custom outputs" for "AOV sets" and "Channels" for AOVs

**Comment by jdent02** [comment]
That's a bit clearer

**Comment by bsavery** [comment]
Maybe this is better?  Right now you have to manually enter the light/lpe group names but I think I can solve that.

![screen shot 2015-08-19 at 8 54 04 am](https://cloud.githubusercontent.com/assets/1892220/9361378/0c9e30ca-4650-11e5-9964-ee4665d4f1e3.png)

**Comment by bsavery** [comment]
Non-advanced view:

![screen shot 2015-08-19 at 8 56 44 am](https://cloud.githubusercontent.com/assets/1892220/9361433/41efae34-4650-11e5-99fa-6631653b5d32.png)

**Comment by jdent02** [comment]
That looks promising. I take it the 'do output' checkbox is how you would assign an aov set to a layer?

**Comment by bsavery** [comment]
Just updated the plugin.  Let me know if that works.

**Comment by jdent02** [comment]
Trying out some of the built in AOV's.  Indirect diffuse produces an output but 'diffuse' only gives me a black image (two surfaces in the test shot are diffuse).  lpe groups seem to work, but I realized I have no idea how to assign an object to an lpe.

**Comment by jdent02** [comment]
Custom LPE strings don't seem to work.  Although I'm not sure exactly what to type, I tried 'diffuse', 'lpe:diffuse', 'CD<L.>' and 'lpe:CD<L.>'.  In every case I got an 'exited' error with the following:


Traceback (most recent call last):
  File "c:\Program Files\Blender Foundation\Blender\2.75\scripts\addons\PRMan-fo
r-Blender-master\__init__.py", line 68, in update
    engine.update(self, data, scene)
  File "c:\Program Files\Blender Foundation\Blender\2.75\scripts\addons\PRMan-fo
r-Blender-master\engine.py", line 107, in update
    engine.render_pass.gen_rib(engine=engine)
  File "c:\Program Files\Blender Foundation\Blender\2.75\scripts\addons\PRMan-fo
r-Blender-master\engine.py", line 515, in gen_rib
    write_rib(self, self.scene, self.ri)
  File "c:\Program Files\Blender Foundation\Blender\2.75\scripts\addons\PRMan-fo
r-Blender-master\export.py", line 2397, in write_rib
    export_display(ri, rpass, scene)
  File "c:\Program Files\Blender Foundation\Blender\2.75\scripts\addons\PRMan-fo
r-Blender-master\export.py", line 2282, in export_display
    source = aov.lpe_string
AttributeError: 'RendermanAOV' object has no attribute 'lpe_string'

location: <unknown location>:-1

location: <unknown location>:-1
ERROR:  ('Export path [C:\\Users\\Jon\\My Documents\\prman_for_blender\\material
_test/images/Scene_0001.exr] does not exist.',)
Info: Texture generation took 00:00:00
Error: PRMan: Exited

**Comment by bsavery** [comment]
Both are fixed.  Thanks for testing!

On Thu, Aug 20, 2015 at 8:28 PM, jdent02 <notifications@github.com> wrote:

> Custom LPE strings don't seem to work. Although I'm not sure exactly what
> to type, I tried 'diffuse', 'lpe:diffuse', 'CD' and 'lpe:CD'. In every case
> I got an 'exited' error with the following:
>
> Traceback (most recent call last):
> File "c:\Program Files\Blender
> Foundation\Blender\2.75\scripts\addons\PRMan-fo
> r-Blender-master__init__.py", line 68, in update
> engine.update(self, data, scene)
> File "c:\Program Files\Blender
> Foundation\Blender\2.75\scripts\addons\PRMan-fo
> r-Blender-master\engine.py", line 107, in update
> engine.render_pass.gen_rib(engine=engine)
> File "c:\Program Files\Blender
> Foundation\Blender\2.75\scripts\addons\PRMan-fo
> r-Blender-master\engine.py", line 515, in gen_rib
> write_rib(self, self.scene, self.ri)
> File "c:\Program Files\Blender
> Foundation\Blender\2.75\scripts\addons\PRMan-fo
> r-Blender-master\export.py", line 2397, in write_rib
> export_display(ri, rpass, scene)
> File "c:\Program Files\Blender
> Foundation\Blender\2.75\scripts\addons\PRMan-fo
> r-Blender-master\export.py", line 2282, in export_display
> source = aov.lpe_string
> AttributeError: 'RendermanAOV' object has no attribute 'lpe_string'
>
> location: :-1
>
> location: :-1
> ERROR: ('Export path [C:\Users\Jon\My Documents\prman_for_blender\material
> _test/images/Scene_0001.exr] does not exist.',)
> Info: Texture generation took 00:00:00
> Error: PRMan: Exited
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/85#issuecomment-133267613>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
Still going......

Looks like specular has the same problem as diffuse.  Indirectspecular shows the same image as reflection.

**Comment by bsavery** [comment]
Specular is fixed.  Sorry about the typo in the lpe!  IndirectSpecular and reflection should be the same.... reflection is meant for collecting from holdouts.  

BTW I haven't tested the light group and object groups features too much.  You can add the object group with the same way you add the holdout group for now.  Would you prefer a better way to add it?

**Comment by jdent02** [comment]
Doesn't need to be. I figured out that the holdout box could be used for group assignments. Only suggestion would be renaming it to something more general. One other thing I noticed is that if you enable 'advanced' aov options (the light and object groups) and enter something in the field, it will still be exported even if you uncheck the 'advanced' option again.  You might even be able to remove that checkbox if you wanted.

Side note: the shadow pass looks like it's inverted from what a shadow pass usually looks like (it's a black background with lighter grey areas where the shadows are). Is this correct?

**Comment by jdent02** [comment]
Everything seems to work on the custom AOV's, including custom lpe light groups.  Haven't experimented much with the group lpe's yet.

**Comment by bsavery** [comment]
Ok, yeah I think your comment on the lpe group on objects is spot on.  Will do that today.

**Comment by jdent02** [comment]
Also haven't had a chance to play with the custom lpe string today.  Just out of curiosity what is the right syntax to use there?

**Comment by bsavery** [comment]
Great question.  And I had two thoughts and kinda enabled both.  Basically you're using the lpe syntax:
https://renderman.pixar.com/resources/current/RenderMan/risLPEs.html#id1

Now here's the trick:
1.  You can type your own light group name or lpe group in the lpe string directly when doing a custom one.  I kinda figured anyone who was going to write their own lpe strings would enter the light group themselves in it.
OR 
2.  You can use the custom light group setting and use a %LG or %G for light group or lpe group respectively.  for example this would be for diffuse:
lpe:C<.D%G><L.%LG>
see more examples here:
https://github.com/bsavery/PRMan-for-Blender/blob/master/properties.py#L322-L336

**Comment by jdent02** [comment]
Okay, so correct me if I'm wrong, but if I wanted to take the "left_light" group and create an AOV with just that light and all it's scattering events, which would be the proper format:

<L.left_light>
<L.'left_light'>
lpe:<L.left_light>
or lpe:<L.'left_light'>

Sorry for the question, I'm not all that well versed on code and the documentation is unclear.

**Comment by bsavery** [comment]
By all scattering events you mean the beauty for left_light?

**Comment by jdent02** [comment]
Yep. It's mentioned at the bottom of that page you linked to.

**Comment by bsavery** [comment]
I believe that would be:

```
C[DS]*[<L.'left_light'>O] 

```

**Comment by jdent02** [comment]
Oh. I see. According to that page the beauty pass without any special lighting was just some variation of L.  

Back on topic though everything I tried this morning worked fine.

**Comment by bsavery** [comment]
Rethought about this. I actually don't like the way this is implemented. So I think I'm going to just skip using the built in render layers altogether. And use a sub type we make of render layers. Really I think this will be the best solution. 

Problem with the current implementation is if you make a bunch of custom aovs and then rename the render layer, the custom stuff will kinda be lost.

**Comment by jdent02** [comment]
I rarely use the render layer system when actually rendering so I didn't notice that glitch.

Like I mentioned it is old code in Blender and designed for the scanline renderer.  Even the devs stated at one point that it's functionality was greatly reduced once Cycles was launched.

**Comment by jdent02** [comment]
A side note but something in the same vein: in the 'passes' area can you add checkboxes for the AOV's that aren't lpe dependent, like the position passes?

**Comment by bsavery** [comment]
This is in .9
