### ISSUE TITLE
Not established Rendermen. How to get rid of this error?

### ISSUE THREAD

**Issue by Jex1202** [bsavery/PRMan-for-Blender#93]
![1](https://cloud.githubusercontent.com/assets/13686464/9126136/27ee4416-3cb2-11e5-9fcd-8538632549e7.jpg)
![321dsadas](https://cloud.githubusercontent.com/assets/13686464/9126153/7cea7fd4-3cb2-11e5-9c0a-596462aad59f.png)

**Comment by jdent02** [comment]
Is the addon looking in the right place for renderman?

**Comment by bsavery** [comment]
Sorry this is not an issue for the blender add on. It's fairly clear what your issue is though. The RenderMan non commercial license allows you to install it on 5 computers. Seems like you've gone over that. You should contact rendermansales@pixar.con
