### ISSUE TITLE
Strange result

### ISSUE THREAD

**Issue by mifth** [bsavery/PRMan-for-Blender#97]
Hi.

I installer the PRman on linux ubuntu and i get strange rendering result.
http://i.imgur.com/3AzpQRy.png

https://dl.dropboxusercontent.com/u/26887202/blender/temp_prman.blend

Is it ok or this is an issue?

**Comment by MWY3510** [comment]
This is not really an issue per say. The alpha hole you see is caused by the camera clipping option. If you set it to about 1000 the problem will be resolved.
![pannel](https://cloud.githubusercontent.com/assets/9410101/9151716/c0f0659e-3dda-11e5-865d-bbbbc7a74bc7.jpg)

**Comment by mifth** [comment]
I tried some renderers but i have never got such a strange result even with lower clipping values.

**Comment by MWY3510** [comment]
Did these other tests involve using the sky dome? I have always had to reset the clipping value for the  sky dome.

**Comment by mifth** [comment]
No there were no sky dome. Just simple scenes.
Like some cubes an a light.

**Comment by MWY3510** [comment]
Can you post a blend file of one of those scenes please.

**Comment by bsavery** [comment]
You actually do have a "sky dome" light in the scene it looks like from your screen shots.  The one named "Sky".  "Sky" and "Hemi" lights in RenderMan use the same geometry.

**Comment by mifth** [comment]
Sorry, i misunderstood i guess.
I had to switch sky light visibility off. To get correct result.

Btw, I think it's better to have light visibility switched off by default. When we create a lightNode.

**Comment by mifth** [comment]
I guess we can close this issue.
