### ISSUE TITLE
z depth issue

### ISSUE THREAD

**Issue by mifth** [bsavery/PRMan-for-Blender#98]
Hi.

I found strange issue. If i set Normalize Node in Cycles - i see the depth.
But if i set Noralize Node In PRMan - i see no depth.
Is this an issue?

http://i.imgur.com/jfnF192.png
http://i.imgur.com/ud0IE4U.png

**Comment by MWY3510** [comment]
Hello mifth,

We have never had the z-depth buffer in a working order. So the issue with the compositor is that it has no information on the z channel. 
This would make a great improvement for anyone who wants to tackle it though.

Sincerely,
MWY3510

**Comment by mifth** [comment]
Ok. How can i get z pass then?

**Comment by bsavery** [comment]
Just be clear here.  Is Blender looking for z info in the main render output?  If so all that needs to happen is the main render has to output rgbaz instead of rgba for the channel name.  

Or is it looking for the z output separately?

**Comment by mifth** [comment]
Sorry i dunno know. I'm just a humble user.

There is a checkbox "Z" in Cycles render passes. I hope it can help somehow.

**Comment by bsavery** [comment]
No it is helpful.  If you take a look in the folder where stuff is output (~/Documents/prman_for_blender/$SCENE_NAME/)  You'll see that there is an images directory where images are written out.  If you check that same Z checkbox you'll get a Z output in that directory.  That should work.  You'll also get a "beauty" pass that has RGBA in it.  My general question to all replying to this thread was if 

A:  Blender is looking for Z in the beauty pass (I.e RGBAZ)
B:  Blender is looking for the Z output separately and we're just not loading it back in (we aren't).

**Comment by MWY3510** [comment]
bsavery, the problem as I see it is that the blender is loading the z depth information from the output.z.file_extension file but the file itself does not have any information in it. In other words there is no z depth info for blender to load. 
mifth, To answer the question currently you cannot get the z pass.

**Comment by bsavery** [comment]
Ah ok.  Then that's different.

If you view the image in "it" there's no Z information?? Maybe it's just not in a format that blender recognizes.

**Comment by MWY3510** [comment]
There is no depth info in IT ether.

**Comment by bsavery** [comment]
![z](https://cloud.githubusercontent.com/assets/1892220/9152511/16435246-3de9-11e5-921e-cce991043bbb.jpg)

Hmmm I'm seeing z depth.  (Pay no attention to pinholes)

**Comment by MWY3510** [comment]
Strange, I get depth in the physical camera example but not in a default render. Might the difference be the physical camera?

**Comment by bsavery** [comment]
Ah ok.   

I see what's going on blender.  They're looking for all the AOVs to be in one file.  RGBA, Z, and any other aovs in the renderlayer.  That should be fine, when rendering to "it" that won't work great, so we'll have to do things differently in that case.

(Basically scenario A I mentioned above)

**Comment by bsavery** [comment]
Furthermore.... we'd like to be able to add more pass types to a layer... hmmm I'll have to investigate this more.
