### ISSUE TITLE
Not sure, but depth of field doesn't appear to be working now....

### ISSUE THREAD

**Issue by MarshallRoss** [bsavery/PRMan-for-Blender#99]
...maybe user error, but I can't seem to get depth of field to work anymore.  Does it work for the rest of you?  I have the latest zip as of 10 minutes ago.

**Comment by bsavery** [comment]
testing...

**Comment by bsavery** [comment]
Seems to be working.  I just tried the physical camera example file...

https://github.com/bsavery/PRMan-for-Blender/blob/master/examples/physical_camera/physical_camera.jpg

**Comment by MarshallRoss** [comment]
yea... that example works...so I must have set something up incorrectly in my scene...I'll track it down.  Thanks!  

M

**Comment by MarshallRoss** [comment]
Yea...seems to work on my scene if I set the f-stop value low enough.  I finally noticed the effect when f-stop was < 4.0.  Thanks for checking.  Great work on the addon, btw.  It just keeps getting better.

**Comment by bsavery** [comment]
Keep in mind we are using the camera focal length now too.

On Saturday, August 8, 2015, MarshallRoss <notifications@github.com> wrote:

> Yea...seems to work on my scene if I set the f-stop value low enough. I
> finally noticed the effect when f-stop was < 4.0. Thanks for checking.
> Great work on the addon, btw. It just keeps getting better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/99#issuecomment-129055243>
> .
>


-- 
brian.savery@gmail.com
508-274-8700
